#!/bin/bash

BUILD_BOOST=true
BUILD_XGBOOST=true
BUILD_LIGHTGBM=true
BUILD_ALGOMARKER=true

BOOST_FPIC_DIR=/nas1/Work/Libs/Boost/boost_1_67_0-fPIC
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BLDDIR="${DIR}/Build"
STATIC_LIBS_TARGET="${BLDDIR}/lib"

if [[ "`which sudo 2>>/dev/null`" ]]; 
then 
export SUDO="`which sudo`"
else
export SUDO=''
fi

echo "SUDO=${SUDO}"
echo "BOOST_FPIC_DIR=${BOOST_FPIC_DIR}"
echo "DIR=${DIR}"
echo "BLDDIR=${BLDDIR}"
echo "STATIC_LIBS_TARGET=${STATIC_LIBS_TARGET}"

mkdir -p "${STATIC_LIBS_TARGET}"

if [ "$BUILD_BOOST" = true ] ; then
pushd ${BOOST_FPIC_DIR}
$SUDO ./b2 --clean
$SUDO ./b2 link=static variant=release linkflags=-static-libstdc++ -j8 cxxflags="-fPIC" --stagedir="${BLDDIR}"
popd
fi

if [ "$BUILD_XGBOOST" = true ] ; then
pushd $MR_ROOT/Libs/External/xgboost
make clean
#The clean doesn't delete .a files
find . -name '*.a' -exec rm {} \;
make -j8
cp ./lib/libxgboost.a ${STATIC_LIBS_TARGET}
cp ./rabit/lib/librabit_empty.a ${STATIC_LIBS_TARGET}
cp ./dmlc-core/libdmlc.a ${STATIC_LIBS_TARGET}
popd
fi

if [ "$BUILD_LIGHTGBM" = true ] ; then
mkdir -p ${BLDDIR}/LightGBM/
cp ${DIR}/Resources/LightGBM/LightGBM_CMakeLists_file ${BLDDIR}/LightGBM/CMakeLists.txt
pushd ${BLDDIR}/LightGBM/
cmake .
make -j8
popd
fi

if [ "$BUILD_ALGOMARKER" = true ] ; then
cp ${DIR}/Resources/AlgoMarker/AlgoMarker_TopLeveL_CMakeLists ${DIR}/../CMakeLists.txt
cp ${DIR}/Resources/AlgoMarker/AlgoMarker_CMakeLists ${DIR}/../AlgoMarker/CMakeLists.txt
mkdir -p ${BLDDIR}/AlgoMarker/CMakeBuild/Linux/Release
pushd ${BLDDIR}/AlgoMarker/CMakeBuild/Linux/Release
cmake ${DIR}/..
make -j8
cp ${BLDDIR}/AlgoMarker/CMakeBuild/Linux/Release/AlgoMarker/libdyn_AlgoMarker.so ${DIR}/../Linux/Release/
strip ${DIR}/../Linux/Release/libdyn_AlgoMarker.so
nm -CD ${DIR}/../Linux/Release/libdyn_AlgoMarker.so | grep " T " > ${BLDDIR}/AlgoMarker/AlgoMarker.public_symbols
ldd ${DIR}/../Linux/Release/libdyn_AlgoMarker.so > ${BLDDIR}/AlgoMarker/AlgoMarker.ldd
echo "AlgoMarker Shared Objecy file written to ${DIR}/../Linux/Release/libdyn_AlgoMarker.so"
popd
fi

exit 0


