var searchData=
[
  ['dart_0',['dart',['../classxgboost_1_1gbm_1_1Dart.html',1,'xgboost::gbm::Dart'],['../classLightGBM_1_1DART.html',1,'LightGBM::DART']]],
  ['darttrainparam_1',['DartTrainParam',['../structxgboost_1_1gbm_1_1DartTrainParam.html',1,'xgboost::gbm']]],
  ['daskdevicequantiledmatrix_2',['DaskDeviceQuantileDMatrix',['../classxgboost_1_1dask_1_1DaskDeviceQuantileDMatrix.html',1,'xgboost::dask']]],
  ['daskdmatrix_3',['DaskDMatrix',['../classxgboost_1_1dask_1_1DaskDMatrix.html',1,'xgboost::dask']]],
  ['daskpartitioniter_4',['DaskPartitionIter',['../classxgboost_1_1dask_1_1DaskPartitionIter.html',1,'xgboost::dask']]],
  ['daskquantiledmatrix_5',['DaskQuantileDMatrix',['../classxgboost_1_1dask_1_1DaskQuantileDMatrix.html',1,'xgboost::dask']]],
  ['daskscikitlearnbase_6',['DaskScikitLearnBase',['../classxgboost_1_1dask_1_1DaskScikitLearnBase.html',1,'xgboost::dask']]],
  ['daskxgbclassifier_7',['DaskXGBClassifier',['../classxgboost_1_1dask_1_1DaskXGBClassifier.html',1,'xgboost::dask']]],
  ['daskxgbranker_8',['DaskXGBRanker',['../classxgboost_1_1dask_1_1DaskXGBRanker.html',1,'xgboost::dask']]],
  ['daskxgbregressor_9',['DaskXGBRegressor',['../classxgboost_1_1dask_1_1DaskXGBRegressor.html',1,'xgboost::dask']]],
  ['daskxgbrfclassifier_10',['DaskXGBRFClassifier',['../classxgboost_1_1dask_1_1DaskXGBRFClassifier.html',1,'xgboost::dask']]],
  ['daskxgbrfregressor_11',['DaskXGBRFRegressor',['../classxgboost_1_1dask_1_1DaskXGBRFRegressor.html',1,'xgboost::dask']]],
  ['data_12',['data',['../classcs__unittest_1_1TestConfidenceClass_1_1Data.html',1,'cs_unittest.TestConfidenceClass.Data'],['../structData.html',1,'Data'],['../unionGenericValue_1_1Data.html',1,'GenericValue&lt; Encoding, Allocator &gt;::Data'],['../structMARGINAL_1_1data.html',1,'MARGINAL::data'],['../classTrainSet0002Dat_1_1Data.html',1,'TrainSet0002Dat.Data']]],
  ['datafloat_13',['DataFloat',['../classcs__unittest_1_1TestCbAdfClass_1_1DataFloat.html',1,'cs_unittest::TestCbAdfClass']]],
  ['datafloatadf_14',['DataFloatADF',['../classcs__unittest_1_1TestCbAdfClass_1_1DataFloatADF.html',1,'cs_unittest::TestCbAdfClass']]],
  ['dataframe_15',['DataFrame',['../classlightgbm_1_1compat_1_1DataFrame.html',1,'lightgbm::compat']]],
  ['dataiter_16',['dataiter',['../classdmlc_1_1DataIter.html',1,'dmlc::DataIter&lt; DType &gt;'],['../classxgboost_1_1core_1_1DataIter.html',1,'xgboost.core.DataIter']]],
  ['dataiter_3c_20arrayadapterbatch_20_3e_17',['DataIter&lt; ArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20arrowcolumnarbatchvec_20_3e_18',['DataIter&lt; ArrowColumnarBatchVec &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20cscadapterbatch_20_3e_19',['DataIter&lt; CSCAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20cscarrayadapterbatch_20_3e_20',['DataIter&lt; CSCArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20csradapterbatch_20_3e_21',['DataIter&lt; CSRAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20csrarrayadapterbatch_20_3e_22',['DataIter&lt; CSRArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20datatableadapterbatch_20_3e_23',['DataIter&lt; DataTableAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20denseadapterbatch_20_3e_24',['DataIter&lt; DenseAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20fileadapterbatch_20_3e_25',['DataIter&lt; FileAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20rowblock_3c_20indextype_2c_20real_5ft_20_3e_20_3e_26',['DataIter&lt; RowBlock&lt; IndexType, real_t &gt; &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20rowblock_3c_20uint32_5ft_2c_20real_5ft_20_3e_20_3e_27',['DataIter&lt; RowBlock&lt; uint32_t, real_t &gt; &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiterproxy_28',['DataIterProxy',['../classxgboost_1_1data_1_1DataIterProxy.html',1,'xgboost::data']]],
  ['dataiterproxy_3c_20dataiterresetcallback_2c_20xgdmatrixcallbacknext_20_3e_29',['DataIterProxy&lt; DataIterResetCallback, XGDMatrixCallbackNext &gt;',['../classxgboost_1_1data_1_1DataIterProxy.html',1,'xgboost::data']]],
  ['datalistener_30',['DataListener',['../classTrainSet0002Dat_1_1DataListener.html',1,'TrainSet0002Dat']]],
  ['dataloader_31',['dataloader',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1util_1_1DataLoader.html',1,'ml.dmlc.xgboost4j.java.example.util.DataLoader'],['../classCommonTestingTools_1_1DataLoader.html',1,'CommonTestingTools::DataLoader']]],
  ['dataparalleltreelearner_32',['DataParallelTreeLearner',['../classLightGBM_1_1DataParallelTreeLearner.html',1,'LightGBM']]],
  ['datapartition_33',['DataPartition',['../classLightGBM_1_1DataPartition.html',1,'LightGBM']]],
  ['dataset_34',['dataset',['../classlightgbm_1_1basic_1_1Dataset.html',1,'lightgbm.basic.Dataset'],['../classLightGBM_1_1Dataset.html',1,'LightGBM::Dataset']]],
  ['datasetloader_35',['DatasetLoader',['../classLightGBM_1_1DatasetLoader.html',1,'LightGBM']]],
  ['datasplitmode_36',['DataSplitMode',['../classxgboost_1_1core_1_1DataSplitMode.html',1,'xgboost::core']]],
  ['datastring_37',['DataString',['../classcs__unittest_1_1TestCbAdfClass_1_1DataString.html',1,'cs_unittest::TestCbAdfClass']]],
  ['datastringadf_38',['DataStringADF',['../classcs__unittest_1_1TestCbAdfClass_1_1DataStringADF.html',1,'cs_unittest::TestCbAdfClass']]],
  ['datatable_39',['DataTable',['../classlightgbm_1_1compat_1_1DataTable.html',1,'lightgbm::compat']]],
  ['datatableadapter_40',['DataTableAdapter',['../classxgboost_1_1data_1_1DataTableAdapter.html',1,'xgboost::data']]],
  ['datatableadapterbatch_41',['DataTableAdapterBatch',['../classxgboost_1_1data_1_1DataTableAdapterBatch.html',1,'xgboost::data']]],
  ['datatype_42',['datatype',['../enumml_1_1dmlc_1_1xgboost4j_1_1java_1_1Communicator_1_1DataType.html',1,'ml.dmlc.xgboost4j.java.Communicator.DataType'],['../classMPI_1_1Datatype.html',1,'MPI::Datatype']]],
  ['datelogger_43',['DateLogger',['../classdmlc_1_1DateLogger.html',1,'dmlc']]],
  ['datetime_44',['DateTime',['../structDateTime.html',1,'']]],
  ['db_45',['Db',['../structDb.html',1,'']]],
  ['dbfixer_46',['DbFixer',['../structDbFixer.html',1,'']]],
  ['dbl_5fidx_47',['dbl_idx',['../structdbl__idx.html',1,'']]],
  ['dblquotestr_48',['DblquoteStr',['../structDblquoteStr.html',1,'']]],
  ['dcgcalculator_49',['DCGCalculator',['../classLightGBM_1_1DCGCalculator.html',1,'LightGBM']]],
  ['decimal_50',['Decimal',['../structDecimal.html',1,'']]],
  ['decision_5ffunction_51',['decision_function',['../structdecision__function.html',1,'']]],
  ['decisionserviceinteraction_52',['DecisionServiceInteraction',['../structDecisionServiceInteraction.html',1,'']]],
  ['decisionservicestate_53',['DecisionServiceState',['../classDecisionServiceState.html',1,'']]],
  ['decrement_5fsize_54',['decrement_size',['../structEigen_1_1internal_1_1decrement__size.html',1,'Eigen::internal']]],
  ['default_5fpacket_5ftraits_55',['default_packet_traits',['../structEigen_1_1internal_1_1default__packet__traits.html',1,'Eigen::internal']]],
  ['defaultstate_56',['DefaultState',['../classDefaultState.html',1,'']]],
  ['dense_57',['Dense',['../structEigen_1_1Dense.html',1,'Eigen']]],
  ['dense2dense_58',['Dense2Dense',['../structEigen_1_1internal_1_1Dense2Dense.html',1,'Eigen::internal']]],
  ['dense2triangular_59',['Dense2Triangular',['../structEigen_1_1internal_1_1Dense2Triangular.html',1,'Eigen::internal']]],
  ['dense4bitsbin_60',['Dense4bitsBin',['../classLightGBM_1_1Dense4bitsBin.html',1,'LightGBM']]],
  ['dense4bitsbiniterator_61',['Dense4bitsBinIterator',['../classLightGBM_1_1Dense4bitsBinIterator.html',1,'LightGBM']]],
  ['dense_5fassignment_5floop_62',['dense_assignment_loop',['../structEigen_1_1internal_1_1dense__assignment__loop.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20defaulttraversal_2c_20completeunrolling_20_3e_63',['dense_assignment_loop&lt; Kernel, DefaultTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01DefaultTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20defaulttraversal_2c_20innerunrolling_20_3e_64',['dense_assignment_loop&lt; Kernel, DefaultTraversal, InnerUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01DefaultTraversal_00_01InnerUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20defaulttraversal_2c_20nounrolling_20_3e_65',['dense_assignment_loop&lt; Kernel, DefaultTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01DefaultTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20innervectorizedtraversal_2c_20completeunrolling_20_3e_66',['dense_assignment_loop&lt; Kernel, InnerVectorizedTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01InnerVectorizedTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20innervectorizedtraversal_2c_20innerunrolling_20_3e_67',['dense_assignment_loop&lt; Kernel, InnerVectorizedTraversal, InnerUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01InnerVectorizedTraversal_00_01InnerUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20innervectorizedtraversal_2c_20nounrolling_20_3e_68',['dense_assignment_loop&lt; Kernel, InnerVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01InnerVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20lineartraversal_2c_20completeunrolling_20_3e_69',['dense_assignment_loop&lt; Kernel, LinearTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20lineartraversal_2c_20nounrolling_20_3e_70',['dense_assignment_loop&lt; Kernel, LinearTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20linearvectorizedtraversal_2c_20completeunrolling_20_3e_71',['dense_assignment_loop&lt; Kernel, LinearVectorizedTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearVectorizedTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20linearvectorizedtraversal_2c_20nounrolling_20_3e_72',['dense_assignment_loop&lt; Kernel, LinearVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20slicevectorizedtraversal_2c_20nounrolling_20_3e_73',['dense_assignment_loop&lt; Kernel, SliceVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01SliceVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fiterator_74',['dense_iterator',['../classdense__iterator.html',1,'']]],
  ['dense_5fparameters_75',['dense_parameters',['../classdense__parameters.html',1,'']]],
  ['dense_5fproduct_5fbase_76',['dense_product_base',['../classEigen_1_1internal_1_1dense__product__base.html',1,'Eigen::internal']]],
  ['dense_5fproduct_5fbase_3c_20lhs_2c_20rhs_2c_20option_2c_20innerproduct_20_3e_77',['dense_product_base&lt; Lhs, Rhs, Option, InnerProduct &gt;',['../classEigen_1_1internal_1_1dense__product__base_3_01Lhs_00_01Rhs_00_01Option_00_01InnerProduct_01_4.html',1,'Eigen::internal']]],
  ['dense_5fxpr_5fbase_78',['dense_xpr_base',['../structEigen_1_1internal_1_1dense__xpr__base.html',1,'Eigen::internal']]],
  ['dense_5fxpr_5fbase_3c_20derived_2c_20arrayxpr_20_3e_79',['dense_xpr_base&lt; Derived, ArrayXpr &gt;',['../structEigen_1_1internal_1_1dense__xpr__base_3_01Derived_00_01ArrayXpr_01_4.html',1,'Eigen::internal']]],
  ['dense_5fxpr_5fbase_3c_20derived_2c_20matrixxpr_20_3e_80',['dense_xpr_base&lt; Derived, MatrixXpr &gt;',['../structEigen_1_1internal_1_1dense__xpr__base_3_01Derived_00_01MatrixXpr_01_4.html',1,'Eigen::internal']]],
  ['denseadapter_81',['DenseAdapter',['../classxgboost_1_1data_1_1DenseAdapter.html',1,'xgboost::data']]],
  ['denseadapterbatch_82',['DenseAdapterBatch',['../classxgboost_1_1data_1_1DenseAdapterBatch.html',1,'xgboost::data']]],
  ['densebase_83',['DenseBase',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20arraywrapper_3c_20expressiontype_20_3e_20_3e_84',['DenseBase&lt; ArrayWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20homogeneous_3c_20matrixtype_2c_20_5fdirection_20_3e_20_3e_85',['DenseBase&lt; Homogeneous&lt; MatrixType, _Direction &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20matrixwrapper_3c_20expressiontype_20_3e_20_3e_86',['DenseBase&lt; MatrixWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20solve_3c_20decomposition_2c_20rhstype_20_3e_20_3e_87',['DenseBase&lt; Solve&lt; Decomposition, RhsType &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebin_88',['DenseBin',['../classLightGBM_1_1DenseBin.html',1,'LightGBM']]],
  ['densebiniterator_89',['DenseBinIterator',['../classLightGBM_1_1DenseBinIterator.html',1,'LightGBM']]],
  ['densecoeffsbase_90',['DenseCoeffsBase',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20arraywrapper_3c_20expressiontype_20_3e_20_3e_91',['DenseCoeffsBase&lt; ArrayWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20directaccessors_20_3e_92',['DenseCoeffsBase&lt; Derived, DirectAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20directwriteaccessors_20_3e_93',['DenseCoeffsBase&lt; Derived, DirectWriteAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectWriteAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20readonlyaccessors_20_3e_94',['DenseCoeffsBase&lt; Derived, ReadOnlyAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20writeaccessors_20_3e_95',['DenseCoeffsBase&lt; Derived, WriteAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20homogeneous_3c_20matrixtype_2c_20_5fdirection_20_3e_20_3e_96',['DenseCoeffsBase&lt; Homogeneous&lt; MatrixType, _Direction &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20matrixwrapper_3c_20expressiontype_20_3e_20_3e_97',['DenseCoeffsBase&lt; MatrixWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20solve_3c_20decomposition_2c_20rhstype_20_3e_20_3e_98',['DenseCoeffsBase&lt; Solve&lt; Decomposition, RhsType &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecolumniter_99',['DenseColumnIter',['../classxgboost_1_1common_1_1DenseColumnIter.html',1,'xgboost::common']]],
  ['denseshape_100',['DenseShape',['../structEigen_1_1DenseShape.html',1,'Eigen']]],
  ['densesparseproductreturntype_101',['DenseSparseProductReturnType',['../structEigen_1_1DenseSparseProductReturnType.html',1,'Eigen']]],
  ['densestorage_102',['DenseStorage',['../classEigen_1_1DenseStorage.html',1,'Eigen']]],
  ['densestorage_3c_20scalar_2c_20base_3a_3amaxsizeatcompiletime_2c_20base_3a_3arowsatcompiletime_2c_20base_3a_3acolsatcompiletime_2c_20options_20_3e_103',['DenseStorage&lt; Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options &gt;',['../classEigen_1_1DenseStorage.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_200_2c_200_2c_20_5foptions_20_3e_104',['DenseStorage&lt; T, 0, 0, 0, _Options &gt;',['../classEigen_1_1DenseStorage.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20_5frows_2c_20_5fcols_2c_20_5foptions_20_3e_105',['DenseStorage&lt; T, 0, _Rows, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01__Rows_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20_5frows_2c_20dynamic_2c_20_5foptions_20_3e_106',['DenseStorage&lt; T, 0, _Rows, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01__Rows_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20dynamic_2c_20_5fcols_2c_20_5foptions_20_3e_107',['DenseStorage&lt; T, 0, Dynamic, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01Dynamic_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20dynamic_2c_20dynamic_2c_20_5foptions_20_3e_108',['DenseStorage&lt; T, 0, Dynamic, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01Dynamic_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20dynamic_2c_20_5frows_2c_20dynamic_2c_20_5foptions_20_3e_109',['DenseStorage&lt; T, Dynamic, _Rows, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Dynamic_00_01__Rows_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20dynamic_2c_20dynamic_2c_20_5fcols_2c_20_5foptions_20_3e_110',['DenseStorage&lt; T, Dynamic, Dynamic, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Dynamic_00_01Dynamic_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20dynamic_2c_20dynamic_2c_20dynamic_2c_20_5foptions_20_3e_111',['DenseStorage&lt; T, Dynamic, Dynamic, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Dynamic_00_01Dynamic_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20size_2c_20_5frows_2c_20dynamic_2c_20_5foptions_20_3e_112',['DenseStorage&lt; T, Size, _Rows, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Size_00_01__Rows_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20size_2c_20dynamic_2c_20_5fcols_2c_20_5foptions_20_3e_113',['DenseStorage&lt; T, Size, Dynamic, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Size_00_01Dynamic_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20size_2c_20dynamic_2c_20dynamic_2c_20_5foptions_20_3e_114',['DenseStorage&lt; T, Size, Dynamic, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Size_00_01Dynamic_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densetimesparseproduct_115',['DenseTimeSparseProduct',['../classEigen_1_1DenseTimeSparseProduct.html',1,'Eigen']]],
  ['densifyparser_116',['DensifyParser',['../classdmlc_1_1data_1_1DensifyParser.html',1,'dmlc::data']]],
  ['dependent_117',['Dependent',['../classDependent.html',1,'']]],
  ['deprecatedgblinearmodelparam_118',['DeprecatedGBLinearModelParam',['../structxgboost_1_1gbm_1_1DeprecatedGBLinearModelParam.html',1,'xgboost::gbm']]],
  ['deque_3c_20t_2c_20eigen_5faligned_5fallocator_3c_20t_20_3e_20_3e_119',['deque&lt; T, EIGEN_ALIGNED_ALLOCATOR&lt; T &gt; &gt;',['../classstd_1_1deque_3_01T_00_01EIGEN__ALIGNED__ALLOCATOR_3_01T_01_4_01_4.html',1,'std']]],
  ['derivedclass_120',['DerivedClass',['../structxgboost_1_1common_1_1DerivedClass.html',1,'xgboost::common']]],
  ['detector_121',['detector',['../structdetail_1_1detector.html',1,'detail']]],
  ['detector_3c_20default_2c_20void_5ft_3c_20op_3c_20args_2e_2e_2e_20_3e_20_3e_2c_20op_2c_20args_2e_2e_2e_20_3e_122',['detector&lt; Default, void_t&lt; Op&lt; Args... &gt; &gt;, Op, Args... &gt;',['../structdetail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html',1,'detail']]],
  ['determinant_5fimpl_123',['determinant_impl',['../structEigen_1_1internal_1_1determinant__impl.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_201_20_3e_124',['determinant_impl&lt; Derived, 1 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_011_01_4.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_202_20_3e_125',['determinant_impl&lt; Derived, 2 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_012_01_4.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_203_20_3e_126',['determinant_impl&lt; Derived, 3 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_013_01_4.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_204_20_3e_127',['determinant_impl&lt; Derived, 4 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_014_01_4.html',1,'Eigen::internal']]],
  ['deviceauccache_128',['DeviceAUCCache',['../structxgboost_1_1metric_1_1DeviceAUCCache.html',1,'xgboost::metric']]],
  ['devicematrixoneapi_129',['DeviceMatrixOneAPI',['../structxgboost_1_1predictor_1_1DeviceMatrixOneAPI.html',1,'xgboost::predictor']]],
  ['devicemodeloneapi_130',['DeviceModelOneAPI',['../classxgboost_1_1predictor_1_1DeviceModelOneAPI.html',1,'xgboost::predictor']]],
  ['devicenodeoneapi_131',['DeviceNodeOneAPI',['../structxgboost_1_1predictor_1_1DeviceNodeOneAPI.html',1,'xgboost::predictor']]],
  ['deviceord_132',['DeviceOrd',['../structxgboost_1_1DeviceOrd.html',1,'xgboost']]],
  ['devicequantiledmatrix_133',['DeviceQuantileDMatrix',['../classxgboost_1_1core_1_1DeviceQuantileDMatrix.html',1,'xgboost::core']]],
  ['devicesym_134',['DeviceSym',['../structxgboost_1_1DeviceSym.html',1,'xgboost']]],
  ['dgnrtfeatureremvoer_135',['DgnrtFeatureRemvoer',['../classDgnrtFeatureRemvoer.html',1,'']]],
  ['diabetesfindergenerator_136',['DiabetesFinderGenerator',['../classDiabetesFinderGenerator.html',1,'']]],
  ['diagonal_137',['Diagonal',['../classEigen_1_1Diagonal.html',1,'Eigen']]],
  ['diagonal2dense_138',['Diagonal2Dense',['../structEigen_1_1internal_1_1Diagonal2Dense.html',1,'Eigen::internal']]],
  ['diagonal2sparse_139',['Diagonal2Sparse',['../structEigen_1_1internal_1_1Diagonal2Sparse.html',1,'Eigen::internal']]],
  ['diagonal_5fproduct_5fevaluator_5fbase_140',['diagonal_product_evaluator_base',['../structEigen_1_1internal_1_1diagonal__product__evaluator__base.html',1,'Eigen::internal']]],
  ['diagonal_5fproduct_5fevaluator_5fbase_3c_20lhs_2c_20rhs_3a_3adiagonalvectortype_2c_20product_3c_20lhs_2c_20rhs_2c_20lazyproduct_20_3e_2c_20ontheright_20_3e_141',['diagonal_product_evaluator_base&lt; Lhs, Rhs::DiagonalVectorType, Product&lt; Lhs, Rhs, LazyProduct &gt;, OnTheRight &gt;',['../structEigen_1_1internal_1_1diagonal__product__evaluator__base.html',1,'Eigen::internal']]],
  ['diagonal_5fproduct_5fevaluator_5fbase_3c_20rhs_2c_20lhs_3a_3adiagonalvectortype_2c_20product_3c_20lhs_2c_20rhs_2c_20lazyproduct_20_3e_2c_20ontheleft_20_3e_142',['diagonal_product_evaluator_base&lt; Rhs, Lhs::DiagonalVectorType, Product&lt; Lhs, Rhs, LazyProduct &gt;, OnTheLeft &gt;',['../structEigen_1_1internal_1_1diagonal__product__evaluator__base.html',1,'Eigen::internal']]],
  ['diagonalbase_143',['DiagonalBase',['../classEigen_1_1DiagonalBase.html',1,'Eigen']]],
  ['diagonalbase_3c_20diagonalmatrix_3c_20_5fscalar_2c_20sizeatcompiletime_2c_20maxsizeatcompiletime_20_3e_20_3e_144',['DiagonalBase&lt; DiagonalMatrix&lt; _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime &gt; &gt;',['../classEigen_1_1DiagonalBase.html',1,'Eigen']]],
  ['diagonalbase_3c_20diagonalwrapper_3c_20_5fdiagonalvectortype_20_3e_20_3e_145',['DiagonalBase&lt; DiagonalWrapper&lt; _DiagonalVectorType &gt; &gt;',['../classEigen_1_1DiagonalBase.html',1,'Eigen']]],
  ['diagonalindexreturntype_146',['DiagonalIndexReturnType',['../structEigen_1_1MatrixBase_1_1DiagonalIndexReturnType.html',1,'Eigen::MatrixBase']]],
  ['diagonalintreturntype_147',['DiagonalIntReturnType',['../structEigen_1_1internal_1_1BandMatrixBase_1_1DiagonalIntReturnType.html',1,'Eigen::internal::BandMatrixBase']]],
  ['diagonalmatrix_148',['DiagonalMatrix',['../classEigen_1_1DiagonalMatrix.html',1,'Eigen']]],
  ['diagonalpreconditioner_149',['DiagonalPreconditioner',['../classEigen_1_1DiagonalPreconditioner.html',1,'Eigen']]],
  ['diagonalproduct_150',['DiagonalProduct',['../classEigen_1_1DiagonalProduct.html',1,'Eigen']]],
  ['diagonalshape_151',['DiagonalShape',['../structEigen_1_1DiagonalShape.html',1,'Eigen']]],
  ['diagonalwrapper_152',['DiagonalWrapper',['../classEigen_1_1DiagonalWrapper.html',1,'Eigen']]],
  ['dictionary_5finfo_153',['dictionary_info',['../structdictionary__info.html',1,'']]],
  ['dictionaryexamplebyte_154',['DictionaryExampleByte',['../classcs__unittest_1_1DictionaryExampleByte.html',1,'cs_unittest']]],
  ['dictionaryexamplebytebyte_155',['DictionaryExampleByteByte',['../classcs__unittest_1_1DictionaryExampleByteByte.html',1,'cs_unittest']]],
  ['dictionaryexamplebytedouble_156',['DictionaryExampleByteDouble',['../classcs__unittest_1_1DictionaryExampleByteDouble.html',1,'cs_unittest']]],
  ['dictionaryexamplebyteint16_157',['DictionaryExampleByteInt16',['../classcs__unittest_1_1DictionaryExampleByteInt16.html',1,'cs_unittest']]],
  ['dictionaryexamplebyteint32_158',['DictionaryExampleByteInt32',['../classcs__unittest_1_1DictionaryExampleByteInt32.html',1,'cs_unittest']]],
  ['dictionaryexamplebyteint64_159',['DictionaryExampleByteInt64',['../classcs__unittest_1_1DictionaryExampleByteInt64.html',1,'cs_unittest']]],
  ['dictionaryexamplebytesbyte_160',['DictionaryExampleByteSByte',['../classcs__unittest_1_1DictionaryExampleByteSByte.html',1,'cs_unittest']]],
  ['dictionaryexamplebytesingle_161',['DictionaryExampleByteSingle',['../classcs__unittest_1_1DictionaryExampleByteSingle.html',1,'cs_unittest']]],
  ['dictionaryexamplebytestring_162',['DictionaryExampleByteString',['../classcs__unittest_1_1DictionaryExampleByteString.html',1,'cs_unittest']]],
  ['dictionaryexamplebyteuint16_163',['DictionaryExampleByteUInt16',['../classcs__unittest_1_1DictionaryExampleByteUInt16.html',1,'cs_unittest']]],
  ['dictionaryexamplebyteuint32_164',['DictionaryExampleByteUInt32',['../classcs__unittest_1_1DictionaryExampleByteUInt32.html',1,'cs_unittest']]],
  ['dictionaryexamplebyteuint64_165',['DictionaryExampleByteUInt64',['../classcs__unittest_1_1DictionaryExampleByteUInt64.html',1,'cs_unittest']]],
  ['dictionaryexampleint16_166',['DictionaryExampleInt16',['../classcs__unittest_1_1DictionaryExampleInt16.html',1,'cs_unittest']]],
  ['dictionaryexampleint16byte_167',['DictionaryExampleInt16Byte',['../classcs__unittest_1_1DictionaryExampleInt16Byte.html',1,'cs_unittest']]],
  ['dictionaryexampleint16double_168',['DictionaryExampleInt16Double',['../classcs__unittest_1_1DictionaryExampleInt16Double.html',1,'cs_unittest']]],
  ['dictionaryexampleint16int16_169',['DictionaryExampleInt16Int16',['../classcs__unittest_1_1DictionaryExampleInt16Int16.html',1,'cs_unittest']]],
  ['dictionaryexampleint16int32_170',['DictionaryExampleInt16Int32',['../classcs__unittest_1_1DictionaryExampleInt16Int32.html',1,'cs_unittest']]],
  ['dictionaryexampleint16int64_171',['DictionaryExampleInt16Int64',['../classcs__unittest_1_1DictionaryExampleInt16Int64.html',1,'cs_unittest']]],
  ['dictionaryexampleint16sbyte_172',['DictionaryExampleInt16SByte',['../classcs__unittest_1_1DictionaryExampleInt16SByte.html',1,'cs_unittest']]],
  ['dictionaryexampleint16single_173',['DictionaryExampleInt16Single',['../classcs__unittest_1_1DictionaryExampleInt16Single.html',1,'cs_unittest']]],
  ['dictionaryexampleint16string_174',['DictionaryExampleInt16String',['../classcs__unittest_1_1DictionaryExampleInt16String.html',1,'cs_unittest']]],
  ['dictionaryexampleint16uint16_175',['DictionaryExampleInt16UInt16',['../classcs__unittest_1_1DictionaryExampleInt16UInt16.html',1,'cs_unittest']]],
  ['dictionaryexampleint16uint32_176',['DictionaryExampleInt16UInt32',['../classcs__unittest_1_1DictionaryExampleInt16UInt32.html',1,'cs_unittest']]],
  ['dictionaryexampleint16uint64_177',['DictionaryExampleInt16UInt64',['../classcs__unittest_1_1DictionaryExampleInt16UInt64.html',1,'cs_unittest']]],
  ['dictionaryexampleint32_178',['DictionaryExampleInt32',['../classcs__unittest_1_1DictionaryExampleInt32.html',1,'cs_unittest']]],
  ['dictionaryexampleint32byte_179',['DictionaryExampleInt32Byte',['../classcs__unittest_1_1DictionaryExampleInt32Byte.html',1,'cs_unittest']]],
  ['dictionaryexampleint32double_180',['DictionaryExampleInt32Double',['../classcs__unittest_1_1DictionaryExampleInt32Double.html',1,'cs_unittest']]],
  ['dictionaryexampleint32int16_181',['DictionaryExampleInt32Int16',['../classcs__unittest_1_1DictionaryExampleInt32Int16.html',1,'cs_unittest']]],
  ['dictionaryexampleint32int32_182',['DictionaryExampleInt32Int32',['../classcs__unittest_1_1DictionaryExampleInt32Int32.html',1,'cs_unittest']]],
  ['dictionaryexampleint32int64_183',['DictionaryExampleInt32Int64',['../classcs__unittest_1_1DictionaryExampleInt32Int64.html',1,'cs_unittest']]],
  ['dictionaryexampleint32sbyte_184',['DictionaryExampleInt32SByte',['../classcs__unittest_1_1DictionaryExampleInt32SByte.html',1,'cs_unittest']]],
  ['dictionaryexampleint32single_185',['DictionaryExampleInt32Single',['../classcs__unittest_1_1DictionaryExampleInt32Single.html',1,'cs_unittest']]],
  ['dictionaryexampleint32string_186',['DictionaryExampleInt32String',['../classcs__unittest_1_1DictionaryExampleInt32String.html',1,'cs_unittest']]],
  ['dictionaryexampleint32uint16_187',['DictionaryExampleInt32UInt16',['../classcs__unittest_1_1DictionaryExampleInt32UInt16.html',1,'cs_unittest']]],
  ['dictionaryexampleint32uint32_188',['DictionaryExampleInt32UInt32',['../classcs__unittest_1_1DictionaryExampleInt32UInt32.html',1,'cs_unittest']]],
  ['dictionaryexampleint32uint64_189',['DictionaryExampleInt32UInt64',['../classcs__unittest_1_1DictionaryExampleInt32UInt64.html',1,'cs_unittest']]],
  ['dictionaryexamplesbyte_190',['DictionaryExampleSByte',['../classcs__unittest_1_1DictionaryExampleSByte.html',1,'cs_unittest']]],
  ['dictionaryexamplesbytebyte_191',['DictionaryExampleSByteByte',['../classcs__unittest_1_1DictionaryExampleSByteByte.html',1,'cs_unittest']]],
  ['dictionaryexamplesbytedouble_192',['DictionaryExampleSByteDouble',['../classcs__unittest_1_1DictionaryExampleSByteDouble.html',1,'cs_unittest']]],
  ['dictionaryexamplesbyteint16_193',['DictionaryExampleSByteInt16',['../classcs__unittest_1_1DictionaryExampleSByteInt16.html',1,'cs_unittest']]],
  ['dictionaryexamplesbyteint32_194',['DictionaryExampleSByteInt32',['../classcs__unittest_1_1DictionaryExampleSByteInt32.html',1,'cs_unittest']]],
  ['dictionaryexamplesbyteint64_195',['DictionaryExampleSByteInt64',['../classcs__unittest_1_1DictionaryExampleSByteInt64.html',1,'cs_unittest']]],
  ['dictionaryexamplesbytesbyte_196',['DictionaryExampleSByteSByte',['../classcs__unittest_1_1DictionaryExampleSByteSByte.html',1,'cs_unittest']]],
  ['dictionaryexamplesbytesingle_197',['DictionaryExampleSByteSingle',['../classcs__unittest_1_1DictionaryExampleSByteSingle.html',1,'cs_unittest']]],
  ['dictionaryexamplesbytestring_198',['DictionaryExampleSByteString',['../classcs__unittest_1_1DictionaryExampleSByteString.html',1,'cs_unittest']]],
  ['dictionaryexamplesbyteuint16_199',['DictionaryExampleSByteUInt16',['../classcs__unittest_1_1DictionaryExampleSByteUInt16.html',1,'cs_unittest']]],
  ['dictionaryexamplesbyteuint32_200',['DictionaryExampleSByteUInt32',['../classcs__unittest_1_1DictionaryExampleSByteUInt32.html',1,'cs_unittest']]],
  ['dictionaryexamplesbyteuint64_201',['DictionaryExampleSByteUInt64',['../classcs__unittest_1_1DictionaryExampleSByteUInt64.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16_202',['DictionaryExampleUInt16',['../classcs__unittest_1_1DictionaryExampleUInt16.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16byte_203',['DictionaryExampleUInt16Byte',['../classcs__unittest_1_1DictionaryExampleUInt16Byte.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16double_204',['DictionaryExampleUInt16Double',['../classcs__unittest_1_1DictionaryExampleUInt16Double.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16int16_205',['DictionaryExampleUInt16Int16',['../classcs__unittest_1_1DictionaryExampleUInt16Int16.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16int32_206',['DictionaryExampleUInt16Int32',['../classcs__unittest_1_1DictionaryExampleUInt16Int32.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16int64_207',['DictionaryExampleUInt16Int64',['../classcs__unittest_1_1DictionaryExampleUInt16Int64.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16sbyte_208',['DictionaryExampleUInt16SByte',['../classcs__unittest_1_1DictionaryExampleUInt16SByte.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16single_209',['DictionaryExampleUInt16Single',['../classcs__unittest_1_1DictionaryExampleUInt16Single.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16string_210',['DictionaryExampleUInt16String',['../classcs__unittest_1_1DictionaryExampleUInt16String.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16uint16_211',['DictionaryExampleUInt16UInt16',['../classcs__unittest_1_1DictionaryExampleUInt16UInt16.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16uint32_212',['DictionaryExampleUInt16UInt32',['../classcs__unittest_1_1DictionaryExampleUInt16UInt32.html',1,'cs_unittest']]],
  ['dictionaryexampleuint16uint64_213',['DictionaryExampleUInt16UInt64',['../classcs__unittest_1_1DictionaryExampleUInt16UInt64.html',1,'cs_unittest']]],
  ['differentversionsiterator_214',['differentVersionsIterator',['../classdifferentVersionsIterator.html',1,'']]],
  ['direct_5fselfadjoint_5feigenvalues_215',['direct_selfadjoint_eigenvalues',['../structEigen_1_1internal_1_1direct__selfadjoint__eigenvalues.html',1,'Eigen::internal']]],
  ['direct_5fselfadjoint_5feigenvalues_3c_20solvertype_2c_202_2c_20false_20_3e_216',['direct_selfadjoint_eigenvalues&lt; SolverType, 2, false &gt;',['../structEigen_1_1internal_1_1direct__selfadjoint__eigenvalues_3_01SolverType_00_012_00_01false_01_4.html',1,'Eigen::internal']]],
  ['direct_5fselfadjoint_5feigenvalues_3c_20solvertype_2c_203_2c_20false_20_3e_217',['direct_selfadjoint_eigenvalues&lt; SolverType, 3, false &gt;',['../structEigen_1_1internal_1_1direct__selfadjoint__eigenvalues_3_01SolverType_00_013_00_01false_01_4.html',1,'Eigen::internal']]],
  ['direction_218',['direction',['../structdirection.html',1,'']]],
  ['directoryexcursion_219',['directoryexcursion',['../classxgboost_1_1testing_1_1DirectoryExcursion.html',1,'xgboost.testing.DirectoryExcursion'],['../classrelease-artifacts_1_1DirectoryExcursion.html',1,'release-artifacts.DirectoryExcursion'],['../classtest__utils_1_1DirectoryExcursion.html',1,'test_utils.DirectoryExcursion']]],
  ['disposable_220',['Disposable',['../classcs__unittest_1_1TestPooling_1_1Disposable.html',1,'cs_unittest::TestPooling']]],
  ['distinctctx_221',['DistinctCtx',['../structDistinctCtx.html',1,'']]],
  ['disttrainwithflinkexample_222',['DistTrainWithFlinkExample',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1flink_1_1DistTrainWithFlinkExample.html',1,'ml::dmlc::xgboost4j::java::example::flink']]],
  ['div_5fassign_5fop_223',['div_assign_op',['../structEigen_1_1internal_1_1div__assign__op.html',1,'Eigen::internal']]],
  ['diyfp_224',['DiyFp',['../structinternal_1_1DiyFp.html',1,'internal']]],
  ['dmatrix_225',['dmatrix',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1DMatrix.html',1,'ml.dmlc.xgboost4j.java.DMatrix'],['../classxgboost_1_1core_1_1DMatrix.html',1,'xgboost.core.DMatrix'],['../classxgboost_1_1DMatrix.html',1,'xgboost::DMatrix']]],
  ['dmatrixcache_226',['DMatrixCache',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20cache_20_3e_227',['DMatrixCache&lt; Cache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3amapcache_20_3e_228',['DMatrixCache&lt; ltr::MAPCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3andcgcache_20_3e_229',['DMatrixCache&lt; ltr::NDCGCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3aprecache_20_3e_230',['DMatrixCache&lt; ltr::PreCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20predictioncacheentry_20_3e_231',['DMatrixCache&lt; PredictionCacheEntry &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixproxy_232',['DMatrixProxy',['../classxgboost_1_1data_1_1DMatrixProxy.html',1,'xgboost::data']]],
  ['dmatrixtest_233',['dmatrixtest',['../classml_1_1dmlc_1_1xgboost4j_1_1gpu_1_1java_1_1DMatrixTest.html',1,'ml.dmlc.xgboost4j.gpu.java.DMatrixTest'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1DMatrixTest.html',1,'ml.dmlc.xgboost4j.java.DMatrixTest']]],
  ['docalcfeatprocessor_234',['DoCalcFeatProcessor',['../classDoCalcFeatProcessor.html',1,'']]],
  ['document_235',['Document',['../classcs__unittest_1_1Document.html',1,'cs_unittest']]],
  ['documentfeature_236',['DocumentFeature',['../classcs__test_1_1DocumentFeature.html',1,'cs_test']]],
  ['documentfeatureequalitycomparer_237',['DocumentFeatureEqualityComparer',['../classcs__test_1_1DocumentFeatureEqualityComparer.html',1,'cs_test']]],
  ['dot_5fnocheck_238',['dot_nocheck',['../structEigen_1_1internal_1_1dot__nocheck.html',1,'Eigen::internal']]],
  ['dot_5fnocheck_3c_20t_2c_20u_2c_20true_20_3e_239',['dot_nocheck&lt; T, U, true &gt;',['../structEigen_1_1internal_1_1dot__nocheck_3_01T_00_01U_00_01true_01_4.html',1,'Eigen::internal']]],
  ['double_240',['Double',['../classinternal_1_1Double.html',1,'internal']]],
  ['doublepacket_241',['DoublePacket',['../structEigen_1_1internal_1_1DoublePacket.html',1,'Eigen::internal']]],
  ['driver_242',['Driver',['../classxgboost_1_1tree_1_1Driver.html',1,'xgboost::tree']]],
  ['drugintakegenerator_243',['DrugIntakeGenerator',['../classDrugIntakeGenerator.html',1,'']]],
  ['drugsheatmapparams_244',['DrugsHeatMapParams',['../classDrugsHeatMapParams.html',1,'']]],
  ['dummy_245',['dummy',['../structEigen_1_1internal_1_1special__scalar__op__base_1_1dummy.html',1,'Eigen::internal::special_scalar_op_base']]],
  ['duplicateprocessor_246',['DuplicateProcessor',['../classDuplicateProcessor.html',1,'']]],
  ['dynam_247',['DynAM',['../classDynAM.html',1,'']]],
  ['dynamicsparsematrix_248',['DynamicSparseMatrix',['../classEigen_1_1DynamicSparseMatrix.html',1,'Eigen']]]
];
