var searchData=
[
  ['dart_0',['dart',['../classxgboost_1_1gbm_1_1Dart.html',1,'xgboost::gbm::Dart'],['../classLightGBM_1_1DART.html',1,'LightGBM::DART']]],
  ['darttrainparam_1',['DartTrainParam',['../structxgboost_1_1gbm_1_1DartTrainParam.html',1,'xgboost::gbm']]],
  ['daskdevicequantiledmatrix_2',['DaskDeviceQuantileDMatrix',['../classxgboost_1_1dask_1_1DaskDeviceQuantileDMatrix.html',1,'xgboost::dask']]],
  ['daskdmatrix_3',['DaskDMatrix',['../classxgboost_1_1dask_1_1DaskDMatrix.html',1,'xgboost::dask']]],
  ['daskpartitioniter_4',['DaskPartitionIter',['../classxgboost_1_1dask_1_1DaskPartitionIter.html',1,'xgboost::dask']]],
  ['daskquantiledmatrix_5',['DaskQuantileDMatrix',['../classxgboost_1_1dask_1_1DaskQuantileDMatrix.html',1,'xgboost::dask']]],
  ['daskscikitlearnbase_6',['DaskScikitLearnBase',['../classxgboost_1_1dask_1_1DaskScikitLearnBase.html',1,'xgboost::dask']]],
  ['daskxgbclassifier_7',['DaskXGBClassifier',['../classxgboost_1_1dask_1_1DaskXGBClassifier.html',1,'xgboost::dask']]],
  ['daskxgbranker_8',['DaskXGBRanker',['../classxgboost_1_1dask_1_1DaskXGBRanker.html',1,'xgboost::dask']]],
  ['daskxgbregressor_9',['DaskXGBRegressor',['../classxgboost_1_1dask_1_1DaskXGBRegressor.html',1,'xgboost::dask']]],
  ['daskxgbrfclassifier_10',['DaskXGBRFClassifier',['../classxgboost_1_1dask_1_1DaskXGBRFClassifier.html',1,'xgboost::dask']]],
  ['daskxgbrfregressor_11',['DaskXGBRFRegressor',['../classxgboost_1_1dask_1_1DaskXGBRFRegressor.html',1,'xgboost::dask']]],
  ['dataframe_12',['DataFrame',['../classlightgbm_1_1compat_1_1DataFrame.html',1,'lightgbm::compat']]],
  ['dataiter_13',['dataiter',['../classxgboost_1_1core_1_1DataIter.html',1,'xgboost.core.DataIter'],['../classdmlc_1_1DataIter.html',1,'dmlc::DataIter&lt; DType &gt;']]],
  ['dataiter_3c_20arrayadapterbatch_20_3e_14',['DataIter&lt; ArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20arrowcolumnarbatchvec_20_3e_15',['DataIter&lt; ArrowColumnarBatchVec &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20cscadapterbatch_20_3e_16',['DataIter&lt; CSCAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20cscarrayadapterbatch_20_3e_17',['DataIter&lt; CSCArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20csradapterbatch_20_3e_18',['DataIter&lt; CSRAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20csrarrayadapterbatch_20_3e_19',['DataIter&lt; CSRArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20datatableadapterbatch_20_3e_20',['DataIter&lt; DataTableAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20denseadapterbatch_20_3e_21',['DataIter&lt; DenseAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20fileadapterbatch_20_3e_22',['DataIter&lt; FileAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20rowblock_3c_20indextype_2c_20real_5ft_20_3e_20_3e_23',['DataIter&lt; RowBlock&lt; IndexType, real_t &gt; &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20rowblock_3c_20uint32_5ft_2c_20real_5ft_20_3e_20_3e_24',['DataIter&lt; RowBlock&lt; uint32_t, real_t &gt; &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiterproxy_25',['DataIterProxy',['../classxgboost_1_1data_1_1DataIterProxy.html',1,'xgboost::data']]],
  ['dataiterproxy_3c_20dataiterresetcallback_2c_20xgdmatrixcallbacknext_20_3e_26',['DataIterProxy&lt; DataIterResetCallback, XGDMatrixCallbackNext &gt;',['../classxgboost_1_1data_1_1DataIterProxy.html',1,'xgboost::data']]],
  ['dataloader_27',['dataloader',['../classCommonTestingTools_1_1DataLoader.html',1,'CommonTestingTools::DataLoader'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1util_1_1DataLoader.html',1,'ml.dmlc.xgboost4j.java.example.util.DataLoader']]],
  ['dataparalleltreelearner_28',['DataParallelTreeLearner',['../classLightGBM_1_1DataParallelTreeLearner.html',1,'LightGBM']]],
  ['datapartition_29',['DataPartition',['../classLightGBM_1_1DataPartition.html',1,'LightGBM']]],
  ['dataset_30',['dataset',['../classlightgbm_1_1basic_1_1Dataset.html',1,'lightgbm.basic.Dataset'],['../classLightGBM_1_1Dataset.html',1,'LightGBM::Dataset']]],
  ['datasetloader_31',['DatasetLoader',['../classLightGBM_1_1DatasetLoader.html',1,'LightGBM']]],
  ['datasplitmode_32',['DataSplitMode',['../classxgboost_1_1core_1_1DataSplitMode.html',1,'xgboost::core']]],
  ['datatable_33',['DataTable',['../classlightgbm_1_1compat_1_1DataTable.html',1,'lightgbm::compat']]],
  ['datatableadapter_34',['DataTableAdapter',['../classxgboost_1_1data_1_1DataTableAdapter.html',1,'xgboost::data']]],
  ['datatableadapterbatch_35',['DataTableAdapterBatch',['../classxgboost_1_1data_1_1DataTableAdapterBatch.html',1,'xgboost::data']]],
  ['datatype_36',['datatype',['../enumml_1_1dmlc_1_1xgboost4j_1_1java_1_1Communicator_1_1DataType.html',1,'ml.dmlc.xgboost4j.java.Communicator.DataType'],['../classMPI_1_1Datatype.html',1,'MPI::Datatype']]],
  ['datelogger_37',['DateLogger',['../classdmlc_1_1DateLogger.html',1,'dmlc']]],
  ['dbl_5fidx_38',['dbl_idx',['../structdbl__idx.html',1,'']]],
  ['dcgcalculator_39',['DCGCalculator',['../classLightGBM_1_1DCGCalculator.html',1,'LightGBM']]],
  ['decision_5ffunction_40',['decision_function',['../structdecision__function.html',1,'']]],
  ['decrement_5fsize_41',['decrement_size',['../structEigen_1_1internal_1_1decrement__size.html',1,'Eigen::internal']]],
  ['default_5fpacket_5ftraits_42',['default_packet_traits',['../structEigen_1_1internal_1_1default__packet__traits.html',1,'Eigen::internal']]],
  ['dense_43',['Dense',['../structEigen_1_1Dense.html',1,'Eigen']]],
  ['dense2dense_44',['Dense2Dense',['../structEigen_1_1internal_1_1Dense2Dense.html',1,'Eigen::internal']]],
  ['dense2triangular_45',['Dense2Triangular',['../structEigen_1_1internal_1_1Dense2Triangular.html',1,'Eigen::internal']]],
  ['dense4bitsbin_46',['Dense4bitsBin',['../classLightGBM_1_1Dense4bitsBin.html',1,'LightGBM']]],
  ['dense4bitsbiniterator_47',['Dense4bitsBinIterator',['../classLightGBM_1_1Dense4bitsBinIterator.html',1,'LightGBM']]],
  ['dense_5fassignment_5floop_48',['dense_assignment_loop',['../structEigen_1_1internal_1_1dense__assignment__loop.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20defaulttraversal_2c_20completeunrolling_20_3e_49',['dense_assignment_loop&lt; Kernel, DefaultTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01DefaultTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20defaulttraversal_2c_20innerunrolling_20_3e_50',['dense_assignment_loop&lt; Kernel, DefaultTraversal, InnerUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01DefaultTraversal_00_01InnerUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20defaulttraversal_2c_20nounrolling_20_3e_51',['dense_assignment_loop&lt; Kernel, DefaultTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01DefaultTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20innervectorizedtraversal_2c_20completeunrolling_20_3e_52',['dense_assignment_loop&lt; Kernel, InnerVectorizedTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01InnerVectorizedTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20innervectorizedtraversal_2c_20innerunrolling_20_3e_53',['dense_assignment_loop&lt; Kernel, InnerVectorizedTraversal, InnerUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01InnerVectorizedTraversal_00_01InnerUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20innervectorizedtraversal_2c_20nounrolling_20_3e_54',['dense_assignment_loop&lt; Kernel, InnerVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01InnerVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20lineartraversal_2c_20completeunrolling_20_3e_55',['dense_assignment_loop&lt; Kernel, LinearTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20lineartraversal_2c_20nounrolling_20_3e_56',['dense_assignment_loop&lt; Kernel, LinearTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20linearvectorizedtraversal_2c_20completeunrolling_20_3e_57',['dense_assignment_loop&lt; Kernel, LinearVectorizedTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearVectorizedTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20linearvectorizedtraversal_2c_20nounrolling_20_3e_58',['dense_assignment_loop&lt; Kernel, LinearVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01LinearVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fassignment_5floop_3c_20kernel_2c_20slicevectorizedtraversal_2c_20nounrolling_20_3e_59',['dense_assignment_loop&lt; Kernel, SliceVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1dense__assignment__loop_3_01Kernel_00_01SliceVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['dense_5fproduct_5fbase_60',['dense_product_base',['../classEigen_1_1internal_1_1dense__product__base.html',1,'Eigen::internal']]],
  ['dense_5fproduct_5fbase_3c_20lhs_2c_20rhs_2c_20option_2c_20innerproduct_20_3e_61',['dense_product_base&lt; Lhs, Rhs, Option, InnerProduct &gt;',['../classEigen_1_1internal_1_1dense__product__base_3_01Lhs_00_01Rhs_00_01Option_00_01InnerProduct_01_4.html',1,'Eigen::internal']]],
  ['dense_5fxpr_5fbase_62',['dense_xpr_base',['../structEigen_1_1internal_1_1dense__xpr__base.html',1,'Eigen::internal']]],
  ['dense_5fxpr_5fbase_3c_20derived_2c_20arrayxpr_20_3e_63',['dense_xpr_base&lt; Derived, ArrayXpr &gt;',['../structEigen_1_1internal_1_1dense__xpr__base_3_01Derived_00_01ArrayXpr_01_4.html',1,'Eigen::internal']]],
  ['dense_5fxpr_5fbase_3c_20derived_2c_20matrixxpr_20_3e_64',['dense_xpr_base&lt; Derived, MatrixXpr &gt;',['../structEigen_1_1internal_1_1dense__xpr__base_3_01Derived_00_01MatrixXpr_01_4.html',1,'Eigen::internal']]],
  ['denseadapter_65',['DenseAdapter',['../classxgboost_1_1data_1_1DenseAdapter.html',1,'xgboost::data']]],
  ['denseadapterbatch_66',['DenseAdapterBatch',['../classxgboost_1_1data_1_1DenseAdapterBatch.html',1,'xgboost::data']]],
  ['densebase_67',['DenseBase',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20arraywrapper_3c_20expressiontype_20_3e_20_3e_68',['DenseBase&lt; ArrayWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20homogeneous_3c_20matrixtype_2c_20_5fdirection_20_3e_20_3e_69',['DenseBase&lt; Homogeneous&lt; MatrixType, _Direction &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20matrixwrapper_3c_20expressiontype_20_3e_20_3e_70',['DenseBase&lt; MatrixWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebase_3c_20solve_3c_20decomposition_2c_20rhstype_20_3e_20_3e_71',['DenseBase&lt; Solve&lt; Decomposition, RhsType &gt; &gt;',['../classEigen_1_1DenseBase.html',1,'Eigen']]],
  ['densebin_72',['DenseBin',['../classLightGBM_1_1DenseBin.html',1,'LightGBM']]],
  ['densebiniterator_73',['DenseBinIterator',['../classLightGBM_1_1DenseBinIterator.html',1,'LightGBM']]],
  ['densecoeffsbase_74',['DenseCoeffsBase',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20arraywrapper_3c_20expressiontype_20_3e_20_3e_75',['DenseCoeffsBase&lt; ArrayWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20directaccessors_20_3e_76',['DenseCoeffsBase&lt; Derived, DirectAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20directwriteaccessors_20_3e_77',['DenseCoeffsBase&lt; Derived, DirectWriteAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectWriteAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20readonlyaccessors_20_3e_78',['DenseCoeffsBase&lt; Derived, ReadOnlyAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20derived_2c_20writeaccessors_20_3e_79',['DenseCoeffsBase&lt; Derived, WriteAccessors &gt;',['../classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20homogeneous_3c_20matrixtype_2c_20_5fdirection_20_3e_20_3e_80',['DenseCoeffsBase&lt; Homogeneous&lt; MatrixType, _Direction &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20matrixwrapper_3c_20expressiontype_20_3e_20_3e_81',['DenseCoeffsBase&lt; MatrixWrapper&lt; ExpressionType &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecoeffsbase_3c_20solve_3c_20decomposition_2c_20rhstype_20_3e_20_3e_82',['DenseCoeffsBase&lt; Solve&lt; Decomposition, RhsType &gt; &gt;',['../classEigen_1_1DenseCoeffsBase.html',1,'Eigen']]],
  ['densecolumniter_83',['DenseColumnIter',['../classxgboost_1_1common_1_1DenseColumnIter.html',1,'xgboost::common']]],
  ['denseshape_84',['DenseShape',['../structEigen_1_1DenseShape.html',1,'Eigen']]],
  ['densesparseproductreturntype_85',['DenseSparseProductReturnType',['../structEigen_1_1DenseSparseProductReturnType.html',1,'Eigen']]],
  ['densestorage_86',['DenseStorage',['../classEigen_1_1DenseStorage.html',1,'Eigen']]],
  ['densestorage_3c_20scalar_2c_20base_3a_3amaxsizeatcompiletime_2c_20base_3a_3arowsatcompiletime_2c_20base_3a_3acolsatcompiletime_2c_20options_20_3e_87',['DenseStorage&lt; Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options &gt;',['../classEigen_1_1DenseStorage.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_200_2c_200_2c_20_5foptions_20_3e_88',['DenseStorage&lt; T, 0, 0, 0, _Options &gt;',['../classEigen_1_1DenseStorage.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20_5frows_2c_20_5fcols_2c_20_5foptions_20_3e_89',['DenseStorage&lt; T, 0, _Rows, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01__Rows_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20_5frows_2c_20dynamic_2c_20_5foptions_20_3e_90',['DenseStorage&lt; T, 0, _Rows, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01__Rows_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20dynamic_2c_20_5fcols_2c_20_5foptions_20_3e_91',['DenseStorage&lt; T, 0, Dynamic, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01Dynamic_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_200_2c_20dynamic_2c_20dynamic_2c_20_5foptions_20_3e_92',['DenseStorage&lt; T, 0, Dynamic, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_010_00_01Dynamic_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20dynamic_2c_20_5frows_2c_20dynamic_2c_20_5foptions_20_3e_93',['DenseStorage&lt; T, Dynamic, _Rows, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Dynamic_00_01__Rows_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20dynamic_2c_20dynamic_2c_20_5fcols_2c_20_5foptions_20_3e_94',['DenseStorage&lt; T, Dynamic, Dynamic, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Dynamic_00_01Dynamic_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20dynamic_2c_20dynamic_2c_20dynamic_2c_20_5foptions_20_3e_95',['DenseStorage&lt; T, Dynamic, Dynamic, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Dynamic_00_01Dynamic_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20size_2c_20_5frows_2c_20dynamic_2c_20_5foptions_20_3e_96',['DenseStorage&lt; T, Size, _Rows, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Size_00_01__Rows_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20size_2c_20dynamic_2c_20_5fcols_2c_20_5foptions_20_3e_97',['DenseStorage&lt; T, Size, Dynamic, _Cols, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Size_00_01Dynamic_00_01__Cols_00_01__Options_01_4.html',1,'Eigen']]],
  ['densestorage_3c_20t_2c_20size_2c_20dynamic_2c_20dynamic_2c_20_5foptions_20_3e_98',['DenseStorage&lt; T, Size, Dynamic, Dynamic, _Options &gt;',['../classEigen_1_1DenseStorage_3_01T_00_01Size_00_01Dynamic_00_01Dynamic_00_01__Options_01_4.html',1,'Eigen']]],
  ['densetimesparseproduct_99',['DenseTimeSparseProduct',['../classEigen_1_1DenseTimeSparseProduct.html',1,'Eigen']]],
  ['densifyparser_100',['DensifyParser',['../classdmlc_1_1data_1_1DensifyParser.html',1,'dmlc::data']]],
  ['deprecatedgblinearmodelparam_101',['DeprecatedGBLinearModelParam',['../structxgboost_1_1gbm_1_1DeprecatedGBLinearModelParam.html',1,'xgboost::gbm']]],
  ['deque_3c_20t_2c_20eigen_5faligned_5fallocator_3c_20t_20_3e_20_3e_102',['deque&lt; T, EIGEN_ALIGNED_ALLOCATOR&lt; T &gt; &gt;',['../classstd_1_1deque_3_01T_00_01EIGEN__ALIGNED__ALLOCATOR_3_01T_01_4_01_4.html',1,'std']]],
  ['derivedclass_103',['DerivedClass',['../structxgboost_1_1common_1_1DerivedClass.html',1,'xgboost::common']]],
  ['detector_104',['detector',['../structdetail_1_1detector.html',1,'detail']]],
  ['detector_3c_20default_2c_20void_5ft_3c_20op_3c_20args_2e_2e_2e_20_3e_20_3e_2c_20op_2c_20args_2e_2e_2e_20_3e_105',['detector&lt; Default, void_t&lt; Op&lt; Args... &gt; &gt;, Op, Args... &gt;',['../structdetail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html',1,'detail']]],
  ['determinant_5fimpl_106',['determinant_impl',['../structEigen_1_1internal_1_1determinant__impl.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_201_20_3e_107',['determinant_impl&lt; Derived, 1 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_011_01_4.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_202_20_3e_108',['determinant_impl&lt; Derived, 2 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_012_01_4.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_203_20_3e_109',['determinant_impl&lt; Derived, 3 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_013_01_4.html',1,'Eigen::internal']]],
  ['determinant_5fimpl_3c_20derived_2c_204_20_3e_110',['determinant_impl&lt; Derived, 4 &gt;',['../structEigen_1_1internal_1_1determinant__impl_3_01Derived_00_014_01_4.html',1,'Eigen::internal']]],
  ['deviceauccache_111',['DeviceAUCCache',['../structxgboost_1_1metric_1_1DeviceAUCCache.html',1,'xgboost::metric']]],
  ['devicematrixoneapi_112',['DeviceMatrixOneAPI',['../structxgboost_1_1predictor_1_1DeviceMatrixOneAPI.html',1,'xgboost::predictor']]],
  ['devicemodeloneapi_113',['DeviceModelOneAPI',['../classxgboost_1_1predictor_1_1DeviceModelOneAPI.html',1,'xgboost::predictor']]],
  ['devicenodeoneapi_114',['DeviceNodeOneAPI',['../structxgboost_1_1predictor_1_1DeviceNodeOneAPI.html',1,'xgboost::predictor']]],
  ['deviceord_115',['DeviceOrd',['../structxgboost_1_1DeviceOrd.html',1,'xgboost']]],
  ['devicequantiledmatrix_116',['DeviceQuantileDMatrix',['../classxgboost_1_1core_1_1DeviceQuantileDMatrix.html',1,'xgboost::core']]],
  ['devicesym_117',['DeviceSym',['../structxgboost_1_1DeviceSym.html',1,'xgboost']]],
  ['dgnrtfeatureremvoer_118',['DgnrtFeatureRemvoer',['../classDgnrtFeatureRemvoer.html',1,'']]],
  ['diabetesfindergenerator_119',['DiabetesFinderGenerator',['../classDiabetesFinderGenerator.html',1,'']]],
  ['diagonal_120',['Diagonal',['../classEigen_1_1Diagonal.html',1,'Eigen']]],
  ['diagonal2dense_121',['Diagonal2Dense',['../structEigen_1_1internal_1_1Diagonal2Dense.html',1,'Eigen::internal']]],
  ['diagonal2sparse_122',['Diagonal2Sparse',['../structEigen_1_1internal_1_1Diagonal2Sparse.html',1,'Eigen::internal']]],
  ['diagonal_5fproduct_5fevaluator_5fbase_123',['diagonal_product_evaluator_base',['../structEigen_1_1internal_1_1diagonal__product__evaluator__base.html',1,'Eigen::internal']]],
  ['diagonal_5fproduct_5fevaluator_5fbase_3c_20lhs_2c_20rhs_3a_3adiagonalvectortype_2c_20product_3c_20lhs_2c_20rhs_2c_20lazyproduct_20_3e_2c_20ontheright_20_3e_124',['diagonal_product_evaluator_base&lt; Lhs, Rhs::DiagonalVectorType, Product&lt; Lhs, Rhs, LazyProduct &gt;, OnTheRight &gt;',['../structEigen_1_1internal_1_1diagonal__product__evaluator__base.html',1,'Eigen::internal']]],
  ['diagonal_5fproduct_5fevaluator_5fbase_3c_20rhs_2c_20lhs_3a_3adiagonalvectortype_2c_20product_3c_20lhs_2c_20rhs_2c_20lazyproduct_20_3e_2c_20ontheleft_20_3e_125',['diagonal_product_evaluator_base&lt; Rhs, Lhs::DiagonalVectorType, Product&lt; Lhs, Rhs, LazyProduct &gt;, OnTheLeft &gt;',['../structEigen_1_1internal_1_1diagonal__product__evaluator__base.html',1,'Eigen::internal']]],
  ['diagonalbase_126',['DiagonalBase',['../classEigen_1_1DiagonalBase.html',1,'Eigen']]],
  ['diagonalbase_3c_20diagonalmatrix_3c_20_5fscalar_2c_20sizeatcompiletime_2c_20maxsizeatcompiletime_20_3e_20_3e_127',['DiagonalBase&lt; DiagonalMatrix&lt; _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime &gt; &gt;',['../classEigen_1_1DiagonalBase.html',1,'Eigen']]],
  ['diagonalbase_3c_20diagonalwrapper_3c_20_5fdiagonalvectortype_20_3e_20_3e_128',['DiagonalBase&lt; DiagonalWrapper&lt; _DiagonalVectorType &gt; &gt;',['../classEigen_1_1DiagonalBase.html',1,'Eigen']]],
  ['diagonalindexreturntype_129',['DiagonalIndexReturnType',['../structEigen_1_1MatrixBase_1_1DiagonalIndexReturnType.html',1,'Eigen::MatrixBase']]],
  ['diagonalintreturntype_130',['DiagonalIntReturnType',['../structEigen_1_1internal_1_1BandMatrixBase_1_1DiagonalIntReturnType.html',1,'Eigen::internal::BandMatrixBase']]],
  ['diagonalmatrix_131',['DiagonalMatrix',['../classEigen_1_1DiagonalMatrix.html',1,'Eigen']]],
  ['diagonalpreconditioner_132',['DiagonalPreconditioner',['../classEigen_1_1DiagonalPreconditioner.html',1,'Eigen']]],
  ['diagonalproduct_133',['DiagonalProduct',['../classEigen_1_1DiagonalProduct.html',1,'Eigen']]],
  ['diagonalshape_134',['DiagonalShape',['../structEigen_1_1DiagonalShape.html',1,'Eigen']]],
  ['diagonalwrapper_135',['DiagonalWrapper',['../classEigen_1_1DiagonalWrapper.html',1,'Eigen']]],
  ['differentversionsiterator_136',['differentVersionsIterator',['../classdifferentVersionsIterator.html',1,'']]],
  ['direct_5fselfadjoint_5feigenvalues_137',['direct_selfadjoint_eigenvalues',['../structEigen_1_1internal_1_1direct__selfadjoint__eigenvalues.html',1,'Eigen::internal']]],
  ['direct_5fselfadjoint_5feigenvalues_3c_20solvertype_2c_202_2c_20false_20_3e_138',['direct_selfadjoint_eigenvalues&lt; SolverType, 2, false &gt;',['../structEigen_1_1internal_1_1direct__selfadjoint__eigenvalues_3_01SolverType_00_012_00_01false_01_4.html',1,'Eigen::internal']]],
  ['direct_5fselfadjoint_5feigenvalues_3c_20solvertype_2c_203_2c_20false_20_3e_139',['direct_selfadjoint_eigenvalues&lt; SolverType, 3, false &gt;',['../structEigen_1_1internal_1_1direct__selfadjoint__eigenvalues_3_01SolverType_00_013_00_01false_01_4.html',1,'Eigen::internal']]],
  ['directoryexcursion_140',['directoryexcursion',['../classrelease-artifacts_1_1DirectoryExcursion.html',1,'release-artifacts.DirectoryExcursion'],['../classtest__utils_1_1DirectoryExcursion.html',1,'test_utils.DirectoryExcursion'],['../classxgboost_1_1testing_1_1DirectoryExcursion.html',1,'xgboost.testing.DirectoryExcursion']]],
  ['disttrainwithflinkexample_141',['DistTrainWithFlinkExample',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1flink_1_1DistTrainWithFlinkExample.html',1,'ml::dmlc::xgboost4j::java::example::flink']]],
  ['div_5fassign_5fop_142',['div_assign_op',['../structEigen_1_1internal_1_1div__assign__op.html',1,'Eigen::internal']]],
  ['dmatrix_143',['dmatrix',['../classxgboost_1_1DMatrix.html',1,'xgboost::DMatrix'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1DMatrix.html',1,'ml.dmlc.xgboost4j.java.DMatrix'],['../classxgboost_1_1core_1_1DMatrix.html',1,'xgboost.core.DMatrix']]],
  ['dmatrixcache_144',['DMatrixCache',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20cache_20_3e_145',['DMatrixCache&lt; Cache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3amapcache_20_3e_146',['DMatrixCache&lt; ltr::MAPCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3andcgcache_20_3e_147',['DMatrixCache&lt; ltr::NDCGCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3aprecache_20_3e_148',['DMatrixCache&lt; ltr::PreCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20predictioncacheentry_20_3e_149',['DMatrixCache&lt; PredictionCacheEntry &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixproxy_150',['DMatrixProxy',['../classxgboost_1_1data_1_1DMatrixProxy.html',1,'xgboost::data']]],
  ['dmatrixtest_151',['dmatrixtest',['../classml_1_1dmlc_1_1xgboost4j_1_1gpu_1_1java_1_1DMatrixTest.html',1,'ml.dmlc.xgboost4j.gpu.java.DMatrixTest'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1DMatrixTest.html',1,'ml.dmlc.xgboost4j.java.DMatrixTest']]],
  ['docalcfeatprocessor_152',['DoCalcFeatProcessor',['../classDoCalcFeatProcessor.html',1,'']]],
  ['dot_5fnocheck_153',['dot_nocheck',['../structEigen_1_1internal_1_1dot__nocheck.html',1,'Eigen::internal']]],
  ['dot_5fnocheck_3c_20t_2c_20u_2c_20true_20_3e_154',['dot_nocheck&lt; T, U, true &gt;',['../structEigen_1_1internal_1_1dot__nocheck_3_01T_00_01U_00_01true_01_4.html',1,'Eigen::internal']]],
  ['doublepacket_155',['DoublePacket',['../structEigen_1_1internal_1_1DoublePacket.html',1,'Eigen::internal']]],
  ['driver_156',['Driver',['../classxgboost_1_1tree_1_1Driver.html',1,'xgboost::tree']]],
  ['drugintakegenerator_157',['DrugIntakeGenerator',['../classDrugIntakeGenerator.html',1,'']]],
  ['drugsheatmapparams_158',['DrugsHeatMapParams',['../classDrugsHeatMapParams.html',1,'']]],
  ['dummy_159',['dummy',['../structEigen_1_1internal_1_1special__scalar__op__base_1_1dummy.html',1,'Eigen::internal::special_scalar_op_base']]],
  ['duplicateprocessor_160',['DuplicateProcessor',['../classDuplicateProcessor.html',1,'']]],
  ['dynam_161',['DynAM',['../classDynAM.html',1,'']]],
  ['dynamicsparsematrix_162',['DynamicSparseMatrix',['../classEigen_1_1DynamicSparseMatrix.html',1,'Eigen']]]
];
