var searchData=
[
  ['rabitcommunicator_0',['RabitCommunicator',['../classxgboost_1_1collective_1_1RabitCommunicator.html',1,'xgboost::collective']]],
  ['rabitcontext_1',['RabitContext',['../classxgboost_1_1rabit_1_1RabitContext.html',1,'xgboost::rabit']]],
  ['rabittracker_2',['rabittracker',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1RabitTracker.html',1,'ml.dmlc.xgboost4j.java.RabitTracker'],['../classdmlc__tracker_1_1tracker_1_1RabitTracker.html',1,'dmlc_tracker.tracker.RabitTracker'],['../classxgboost_1_1tracker_1_1RabitTracker.html',1,'xgboost.tracker.RabitTracker']]],
  ['random_3',['random',['../classLightGBM_1_1Random.html',1,'LightGBM::Random'],['../classRandom.html',1,'Random']]],
  ['random_5fdefault_5fimpl_4',['random_default_impl',['../structEigen_1_1internal_1_1random__default__impl.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20false_2c_20false_20_3e_5',['random_default_impl&lt; Scalar, false, false &gt;',['../structEigen_1_1internal_1_1random__default__impl_3_01Scalar_00_01false_00_01false_01_4.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20false_2c_20true_20_3e_6',['random_default_impl&lt; Scalar, false, true &gt;',['../structEigen_1_1internal_1_1random__default__impl_3_01Scalar_00_01false_00_01true_01_4.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20numtraits_3c_20scalar_20_3e_3a_3aiscomplex_2c_20numtraits_3c_20scalar_20_3e_3a_3aisinteger_20_3e_7',['random_default_impl&lt; Scalar, NumTraits&lt; Scalar &gt;::IsComplex, NumTraits&lt; Scalar &gt;::IsInteger &gt;',['../structEigen_1_1internal_1_1random__default__impl.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20true_2c_20false_20_3e_8',['random_default_impl&lt; Scalar, true, false &gt;',['../structEigen_1_1internal_1_1random__default__impl_3_01Scalar_00_01true_00_01false_01_4.html',1,'Eigen::internal']]],
  ['random_5fimpl_9',['random_impl',['../structEigen_1_1internal_1_1random__impl.html',1,'Eigen::internal']]],
  ['random_5fimpl_3c_20bool_20_3e_10',['random_impl&lt; bool &gt;',['../structEigen_1_1internal_1_1random__impl_3_01bool_01_4.html',1,'Eigen::internal']]],
  ['random_5fpositive_5fwrapper_11',['random_positive_wrapper',['../classrandom__positive__wrapper.html',1,'']]],
  ['random_5fretval_12',['random_retval',['../structEigen_1_1internal_1_1random__retval.html',1,'Eigen::internal']]],
  ['random_5fweights_5fwrapper_13',['random_weights_wrapper',['../classrandom__weights__wrapper.html',1,'']]],
  ['randomdatagenerator_14',['RandomDataGenerator',['../classxgboost_1_1RandomDataGenerator.html',1,'xgboost']]],
  ['randomfeatureselector_15',['RandomFeatureSelector',['../classxgboost_1_1linear_1_1RandomFeatureSelector.html',1,'xgboost::linear']]],
  ['randomreplace_16',['RandomReplace',['../structxgboost_1_1tree_1_1RandomReplace.html',1,'xgboost::tree']]],
  ['randomsamplesgenerator_17',['RandomSamplesGenerator',['../classRandomSamplesGenerator.html',1,'']]],
  ['randomthreadlocalentry_18',['RandomThreadLocalEntry',['../structxgboost_1_1common_1_1RandomThreadLocalEntry.html',1,'xgboost::common']]],
  ['range_19',['Range',['../classxgboost_1_1common_1_1Range.html',1,'xgboost::common']]],
  ['range1d_20',['Range1d',['../classxgboost_1_1common_1_1Range1d.html',1,'xgboost::common']]],
  ['rangecalculator_21',['RangeCalculator',['../classRangeCalculator.html',1,'']]],
  ['rangefeatgenerator_22',['RangeFeatGenerator',['../classRangeFeatGenerator.html',1,'']]],
  ['rangestatus_23',['RangeStatus',['../structRangeStatus.html',1,'']]],
  ['rangetag_24',['RangeTag',['../structxgboost_1_1linalg_1_1detail_1_1RangeTag.html',1,'xgboost::linalg::detail']]],
  ['rankingcache_25',['RankingCache',['../classxgboost_1_1ltr_1_1RankingCache.html',1,'xgboost::ltr']]],
  ['rapidjson_26',['RapidJson',['../classRapidJson.html',1,'']]],
  ['ratiocalculator_27',['RatioCalculator',['../classRatioCalculator.html',1,'']]],
  ['rbitspolicy_28',['RBitsPolicy',['../structxgboost_1_1RBitsPolicy.html',1,'xgboost']]],
  ['rcv1cbeval_29',['Rcv1CbEval',['../classcs__test_1_1Rcv1CbEval.html',1,'cs_test']]],
  ['readstream_30',['ReadStream',['../classdmlc_1_1io_1_1s3_1_1ReadStream.html',1,'dmlc::io::s3']]],
  ['readstringstream_31',['ReadStringStream',['../structdmlc_1_1io_1_1s3_1_1ReadStringStream.html',1,'dmlc::io::s3']]],
  ['readwrapper_32',['ReadWrapper',['../structrabit_1_1c__api_1_1ReadWrapper.html',1,'rabit::c_api']]],
  ['real_5fdefault_5fimpl_33',['real_default_impl',['../structEigen_1_1internal_1_1real__default__impl.html',1,'Eigen::internal']]],
  ['real_5fdefault_5fimpl_3c_20scalar_2c_20true_20_3e_34',['real_default_impl&lt; Scalar, true &gt;',['../structEigen_1_1internal_1_1real__default__impl_3_01Scalar_00_01true_01_4.html',1,'Eigen::internal']]],
  ['real_5fimpl_35',['real_impl',['../structEigen_1_1internal_1_1real__impl.html',1,'Eigen::internal']]],
  ['real_5fref_5fimpl_36',['real_ref_impl',['../structEigen_1_1internal_1_1real__ref__impl.html',1,'Eigen::internal']]],
  ['real_5fref_5fretval_37',['real_ref_retval',['../structEigen_1_1internal_1_1real__ref__retval.html',1,'Eigen::internal']]],
  ['real_5fretval_38',['real_retval',['../structEigen_1_1internal_1_1real__retval.html',1,'Eigen::internal']]],
  ['reallocvector_39',['ReallocVector',['../classxgboost_1_1common_1_1ReallocVector.html',1,'xgboost::common']]],
  ['realqz_40',['RealQZ',['../classEigen_1_1RealQZ.html',1,'Eigen']]],
  ['realqz_3c_20matrixtype_20_3e_41',['RealQZ&lt; MatrixType &gt;',['../classEigen_1_1RealQZ.html',1,'Eigen']]],
  ['realschur_42',['RealSchur',['../classEigen_1_1RealSchur.html',1,'Eigen']]],
  ['realschur_3c_20matrixtype_20_3e_43',['RealSchur&lt; MatrixType &gt;',['../classEigen_1_1RealSchur.html',1,'Eigen']]],
  ['rebind_44',['rebind',['../structxgboost_1_1common_1_1cuda_1_1pinned__allocator_1_1rebind.html',1,'xgboost::common::cuda::pinned_allocator&lt; T &gt;::rebind&lt; U &gt;'],['../structxgboost_1_1common_1_1cuda_1_1pinned__allocator_3_01void_01_4_1_1rebind.html',1,'xgboost::common::cuda::pinned_allocator&lt; void &gt;::rebind'],['../structEigen_1_1aligned__allocator__indirection_1_1rebind.html',1,'Eigen::aligned_allocator_indirection&lt; T &gt;::rebind&lt; U &gt;'],['../structEigen_1_1aligned__allocator_1_1rebind.html',1,'Eigen::aligned_allocator&lt; T &gt;::rebind&lt; U &gt;']]],
  ['recall_5ftree_45',['recall_tree',['../structrecall__tree__ns_1_1recall__tree.html',1,'recall_tree_ns']]],
  ['recordbatchesiteradapter_46',['RecordBatchesIterAdapter',['../classxgboost_1_1data_1_1RecordBatchesIterAdapter.html',1,'xgboost::data']]],
  ['recorddata_47',['RecordData',['../classRecordData.html',1,'']]],
  ['recordiochunkreader_48',['RecordIOChunkReader',['../classdmlc_1_1RecordIOChunkReader.html',1,'dmlc']]],
  ['recordioreader_49',['RecordIOReader',['../classdmlc_1_1RecordIOReader.html',1,'dmlc']]],
  ['recordiosplitter_50',['RecordIOSplitter',['../classdmlc_1_1io_1_1RecordIOSplitter.html',1,'dmlc::io']]],
  ['recordiowriter_51',['RecordIOWriter',['../classdmlc_1_1RecordIOWriter.html',1,'dmlc']]],
  ['recursivehalvingmap_52',['RecursiveHalvingMap',['../classLightGBM_1_1RecursiveHalvingMap.html',1,'LightGBM']]],
  ['redux_5fevaluator_53',['redux_evaluator',['../classEigen_1_1internal_1_1redux__evaluator.html',1,'Eigen::internal']]],
  ['redux_5fimpl_54',['redux_impl',['../structEigen_1_1internal_1_1redux__impl.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20defaulttraversal_2c_20completeunrolling_20_3e_55',['redux_impl&lt; Func, Derived, DefaultTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01DefaultTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20defaulttraversal_2c_20nounrolling_20_3e_56',['redux_impl&lt; Func, Derived, DefaultTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01DefaultTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20linearvectorizedtraversal_2c_20completeunrolling_20_3e_57',['redux_impl&lt; Func, Derived, LinearVectorizedTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01LinearVectorizedTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20linearvectorizedtraversal_2c_20nounrolling_20_3e_58',['redux_impl&lt; Func, Derived, LinearVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01LinearVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20slicevectorizedtraversal_2c_20unrolling_20_3e_59',['redux_impl&lt; Func, Derived, SliceVectorizedTraversal, Unrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01SliceVectorizedTraversal_00_01Unrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_60',['redux_novec_unroller',['../structEigen_1_1internal_1_1redux__novec__unroller.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_3c_20func_2c_20derived_2c_200_2c_20derived_3a_3asizeatcompiletime_20_3e_61',['redux_novec_unroller&lt; Func, Derived, 0, Derived::SizeAtCompileTime &gt;',['../structEigen_1_1internal_1_1redux__novec__unroller.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_3c_20func_2c_20derived_2c_20start_2c_200_20_3e_62',['redux_novec_unroller&lt; Func, Derived, Start, 0 &gt;',['../structEigen_1_1internal_1_1redux__novec__unroller_3_01Func_00_01Derived_00_01Start_00_010_01_4.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_3c_20func_2c_20derived_2c_20start_2c_201_20_3e_63',['redux_novec_unroller&lt; Func, Derived, Start, 1 &gt;',['../structEigen_1_1internal_1_1redux__novec__unroller_3_01Func_00_01Derived_00_01Start_00_011_01_4.html',1,'Eigen::internal']]],
  ['redux_5ftraits_64',['redux_traits',['../structEigen_1_1internal_1_1redux__traits.html',1,'Eigen::internal']]],
  ['redux_5fvec_5funroller_65',['redux_vec_unroller',['../structEigen_1_1internal_1_1redux__vec__unroller.html',1,'Eigen::internal']]],
  ['redux_5fvec_5funroller_3c_20func_2c_20derived_2c_20start_2c_201_20_3e_66',['redux_vec_unroller&lt; Func, Derived, Start, 1 &gt;',['../structEigen_1_1internal_1_1redux__vec__unroller_3_01Func_00_01Derived_00_01Start_00_011_01_4.html',1,'Eigen::internal']]],
  ['reduxreturntype_67',['ReduxReturnType',['../structEigen_1_1VectorwiseOp_1_1ReduxReturnType.html',1,'Eigen::VectorwiseOp']]],
  ['ref_68',['Ref',['../classEigen_1_1Ref.html',1,'Eigen']]],
  ['ref_3c_20const_20matrixtype_20_3e_69',['Ref&lt; const MatrixType &gt;',['../classEigen_1_1Ref.html',1,'Eigen']]],
  ['ref_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_70',['Ref&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01const_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20const_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_71',['Ref&lt; const SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01const_01SparseVector_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20const_20tplainobjecttype_2c_20options_2c_20stridetype_20_3e_72',['Ref&lt; const TPlainObjectType, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01const_01TPlainObjectType_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20const_20umfpackmatrixtype_2c_20standardcompressedformat_20_3e_73',['Ref&lt; const UmfpackMatrixType, StandardCompressedFormat &gt;',['../classEigen_1_1Ref.html',1,'Eigen']]],
  ['ref_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_74',['Ref&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_75',['Ref&lt; SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01SparseVector_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_5fselector_76',['ref_selector',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20expressiontype_20_3e_77',['ref_selector&lt; ExpressionType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20lhs_20_3e_78',['ref_selector&lt; Lhs &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20lhstype_20_3e_79',['ref_selector&lt; LhsType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20matrixtype_20_3e_80',['ref_selector&lt; MatrixType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20rhs_20_3e_81',['ref_selector&lt; Rhs &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20rhstype_20_3e_82',['ref_selector&lt; RhsType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20xprtype_20_3e_83',['ref_selector&lt; XprType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['refbase_84',['RefBase',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20const_20matrixtype_2c_20options_2c_20stridetype_20_3e_20_3e_85',['RefBase&lt; Ref&lt; const MatrixType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20const_20tplainobjecttype_2c_20options_2c_20stridetype_20_3e_20_3e_86',['RefBase&lt; Ref&lt; const TPlainObjectType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20const_20umfpackmatrixtype_2c_20options_2c_20stridetype_20_3e_20_3e_87',['RefBase&lt; Ref&lt; const UmfpackMatrixType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20plainobjecttype_2c_20options_2c_20stridetype_20_3e_20_3e_88',['RefBase&lt; Ref&lt; PlainObjectType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['reflinkvector_89',['RefLinkVector',['../structrabit_1_1engine_1_1AllreduceBase_1_1RefLinkVector.html',1,'rabit::engine::AllreduceBase']]],
  ['refresolve_90',['RefResolve',['../classcs__unittest_1_1TestJsonDictClass_1_1RefResolve.html',1,'cs_unittest::TestJsonDictClass']]],
  ['refresourceview_91',['RefResourceView',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20columntype_20_3e_92',['RefResourceView&lt; ColumnType &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20std_3a_3asize_5ft_20_3e_93',['RefResourceView&lt; std::size_t &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20std_3a_3auint8_5ft_20_3e_94',['RefResourceView&lt; std::uint8_t &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['registry_95',['Registry',['../classdmlc_1_1Registry.html',1,'dmlc']]],
  ['registrydecisionranges_96',['RegistryDecisionRanges',['../classRegistryDecisionRanges.html',1,'']]],
  ['registryevent_97',['RegistryEvent',['../classRegistryEvent.html',1,'']]],
  ['registrysignal_98',['RegistrySignal',['../classRegistrySignal.html',1,'']]],
  ['registrysignaland_99',['RegistrySignalAnd',['../classRegistrySignalAnd.html',1,'']]],
  ['registrysignalany_100',['RegistrySignalAny',['../classRegistrySignalAny.html',1,'']]],
  ['registrysignaldrug_101',['RegistrySignalDrug',['../classRegistrySignalDrug.html',1,'']]],
  ['registrysignalrange_102',['RegistrySignalRange',['../classRegistrySignalRange.html',1,'']]],
  ['registrysignalset_103',['RegistrySignalSet',['../classRegistrySignalSet.html',1,'']]],
  ['reglossobjoneapi_104',['RegLossObjOneAPI',['../classxgboost_1_1obj_1_1RegLossObjOneAPI.html',1,'xgboost::obj']]],
  ['reglossparamoneapi_105',['RegLossParamOneAPI',['../structxgboost_1_1obj_1_1RegLossParamOneAPI.html',1,'xgboost::obj']]],
  ['regression_5fparams_106',['Regression_Params',['../classRegression__Params.html',1,'']]],
  ['regressionfairloss_107',['RegressionFairLoss',['../classLightGBM_1_1RegressionFairLoss.html',1,'LightGBM']]],
  ['regressiongammaloss_108',['RegressionGammaLoss',['../classLightGBM_1_1RegressionGammaLoss.html',1,'LightGBM']]],
  ['regressionhuberloss_109',['RegressionHuberLoss',['../classLightGBM_1_1RegressionHuberLoss.html',1,'LightGBM']]],
  ['regressionl1loss_110',['RegressionL1loss',['../classLightGBM_1_1RegressionL1loss.html',1,'LightGBM']]],
  ['regressionl2loss_111',['RegressionL2loss',['../classLightGBM_1_1RegressionL2loss.html',1,'LightGBM']]],
  ['regressionmapeloss_112',['RegressionMAPELOSS',['../classLightGBM_1_1RegressionMAPELOSS.html',1,'LightGBM']]],
  ['regressionmetric_113',['RegressionMetric',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20fairlossmetric_20_3e_114',['RegressionMetric&lt; FairLossMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20gammadeviancemetric_20_3e_115',['RegressionMetric&lt; GammaDevianceMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20gammametric_20_3e_116',['RegressionMetric&lt; GammaMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20huberlossmetric_20_3e_117',['RegressionMetric&lt; HuberLossMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20l1metric_20_3e_118',['RegressionMetric&lt; L1Metric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20l2metric_20_3e_119',['RegressionMetric&lt; L2Metric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20mapemetric_20_3e_120',['RegressionMetric&lt; MAPEMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20poissonmetric_20_3e_121',['RegressionMetric&lt; PoissonMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20quantilemetric_20_3e_122',['RegressionMetric&lt; QuantileMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20rmsemetric_20_3e_123',['RegressionMetric&lt; RMSEMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20tweediemetric_20_3e_124',['RegressionMetric&lt; TweedieMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionpoissonloss_125',['RegressionPoissonLoss',['../classLightGBM_1_1RegressionPoissonLoss.html',1,'LightGBM']]],
  ['regressionquantileloss_126',['RegressionQuantileloss',['../classLightGBM_1_1RegressionQuantileloss.html',1,'LightGBM']]],
  ['regressiontweedieloss_127',['RegressionTweedieLoss',['../classLightGBM_1_1RegressionTweedieLoss.html',1,'LightGBM']]],
  ['regtree_128',['RegTree',['../classxgboost_1_1RegTree.html',1,'xgboost']]],
  ['reldatacv_129',['RelDataCV',['../classxgboost_1_1testing_1_1data_1_1RelDataCV.html',1,'xgboost::testing::data']]],
  ['remoteschemadocumentprovider_130',['RemoteSchemaDocumentProvider',['../classRemoteSchemaDocumentProvider.html',1,'']]],
  ['remove_5fall_131',['remove_all',['../structEigen_1_1internal_1_1remove__all.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20const_20t_20_3e_132',['remove_all&lt; const T &gt;',['../structEigen_1_1internal_1_1remove__all_3_01const_01T_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20_26_20_3e_133',['remove_all&lt; T &amp; &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01_6_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20_2a_20_3e_134',['remove_all&lt; T * &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01_5_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20const_20_26_20_3e_135',['remove_all&lt; T const &amp; &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01const_01_6_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20const_20_2a_20_3e_136',['remove_all&lt; T const * &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01const_01_5_01_4.html',1,'Eigen::internal']]],
  ['remove_5fconst_137',['remove_const',['../structEigen_1_1internal_1_1remove__const.html',1,'Eigen::internal']]],
  ['remove_5fconst_3c_20const_20t_20_3e_138',['remove_const&lt; const T &gt;',['../structEigen_1_1internal_1_1remove__const_3_01const_01T_01_4.html',1,'Eigen::internal']]],
  ['remove_5fconst_3c_20const_20t_5b_5d_3e_139',['remove_const&lt; const T[]&gt;',['../structEigen_1_1internal_1_1remove__const_3_01const_01T_0f_0e_4.html',1,'Eigen::internal']]],
  ['remove_5fconst_3c_20const_20t_5bsize_5d_3e_140',['remove_const&lt; const T[Size]&gt;',['../structEigen_1_1internal_1_1remove__const_3_01const_01T_0fSize_0e_4.html',1,'Eigen::internal']]],
  ['remove_5fpointer_141',['remove_pointer',['../structEigen_1_1internal_1_1remove__pointer.html',1,'Eigen::internal']]],
  ['remove_5fpointer_3c_20t_20_2a_20_3e_142',['remove_pointer&lt; T * &gt;',['../structEigen_1_1internal_1_1remove__pointer_3_01T_01_5_01_4.html',1,'Eigen::internal']]],
  ['remove_5fpointer_3c_20t_20_2aconst_20_3e_143',['remove_pointer&lt; T *const &gt;',['../structEigen_1_1internal_1_1remove__pointer_3_01T_01_5const_01_4.html',1,'Eigen::internal']]],
  ['remove_5freference_144',['remove_reference',['../structEigen_1_1internal_1_1remove__reference.html',1,'Eigen::internal']]],
  ['remove_5freference_3c_20t_20_26_20_3e_145',['remove_reference&lt; T &amp; &gt;',['../structEigen_1_1internal_1_1remove__reference_3_01T_01_6_01_4.html',1,'Eigen::internal']]],
  ['remove_5fstats_146',['remove_stats',['../classremove__stats.html',1,'']]],
  ['renamectx_147',['RenameCtx',['../structRenameCtx.html',1,'']]],
  ['renametoken_148',['RenameToken',['../structRenameToken.html',1,'']]],
  ['repaggregatesignal_149',['RepAggregateSignal',['../classRepAggregateSignal.html',1,'']]],
  ['repaggregationperiod_150',['RepAggregationPeriod',['../classRepAggregationPeriod.html',1,'']]],
  ['repbasicoutliercleaner_151',['RepBasicOutlierCleaner',['../classRepBasicOutlierCleaner.html',1,'']]],
  ['repbasicrangecleaner_152',['RepBasicRangeCleaner',['../classRepBasicRangeCleaner.html',1,'']]],
  ['repcalcsimplesignals_153',['RepCalcSimpleSignals',['../classRepCalcSimpleSignals.html',1,'']]],
  ['repcategorydescenders_154',['RepCategoryDescenders',['../classRepCategoryDescenders.html',1,'']]],
  ['repcheckreq_155',['RepCheckReq',['../classRepCheckReq.html',1,'']]],
  ['repclearsignalbydiag_156',['RepClearSignalByDiag',['../classRepClearSignalByDiag.html',1,'']]],
  ['repcombinesignals_157',['RepCombineSignals',['../classRepCombineSignals.html',1,'']]],
  ['repconfiguredoutliercleaner_158',['RepConfiguredOutlierCleaner',['../classRepConfiguredOutlierCleaner.html',1,'']]],
  ['repcreatebitsignal_159',['RepCreateBitSignal',['../classRepCreateBitSignal.html',1,'']]],
  ['repcreateregistry_160',['RepCreateRegistry',['../classRepCreateRegistry.html',1,'']]],
  ['repfilterbychannel_161',['RepFilterByChannel',['../classRepFilterByChannel.html',1,'']]],
  ['rephistorylimit_162',['RepHistoryLimit',['../classRepHistoryLimit.html',1,'']]],
  ['replicate_163',['Replicate',['../classEigen_1_1Replicate.html',1,'Eigen']]],
  ['repmultiprocessor_164',['RepMultiProcessor',['../classRepMultiProcessor.html',1,'']]],
  ['repnbrsoutliercleaner_165',['RepNbrsOutlierCleaner',['../classRepNbrsOutlierCleaner.html',1,'']]],
  ['repnumericnoiser_166',['RepNumericNoiser',['../classRepNumericNoiser.html',1,'']]],
  ['repositoryhandle_167',['RepositoryHandle',['../classRepositoryHandle.html',1,'']]],
  ['reppanelcompleter_168',['RepPanelCompleter',['../classRepPanelCompleter.html',1,'']]],
  ['repprocessor_169',['RepProcessor',['../classRepProcessor.html',1,'']]],
  ['repreoderchannels_170',['RepReoderChannels',['../classRepReoderChannels.html',1,'']]],
  ['reprulebasedoutliercleaner_171',['RepRuleBasedOutlierCleaner',['../classRepRuleBasedOutlierCleaner.html',1,'']]],
  ['repsignalrate_172',['RepSignalRate',['../classRepSignalRate.html',1,'']]],
  ['repsimvalhandler_173',['RepSimValHandler',['../classRepSimValHandler.html',1,'']]],
  ['repsplitsignal_174',['RepSplitSignal',['../classRepSplitSignal.html',1,'']]],
  ['requiredsignalfilter_175',['RequiredSignalFilter',['../classRequiredSignalFilter.html',1,'']]],
  ['resamplemissingprocessor_176',['ResampleMissingProcessor',['../classResampleMissingProcessor.html',1,'']]],
  ['resetcontroller_177',['ResetController',['../classVW_1_1Azure_1_1Worker_1_1ResetController.html',1,'VW::Azure::Worker']]],
  ['resourcehandler_178',['ResourceHandler',['../classxgboost_1_1common_1_1ResourceHandler.html',1,'xgboost::common']]],
  ['result_5fof_179',['result_of',['../structEigen_1_1internal_1_1result__of.html',1,'Eigen::internal']]],
  ['result_5fof_3c_20func_28argtype_29_3e_180',['result_of&lt; Func(ArgType)&gt;',['../structEigen_1_1internal_1_1result__of_3_01Func_07ArgType_08_4.html',1,'Eigen::internal']]],
  ['result_5fof_3c_20func_28argtype0_2c_20argtype1_29_3e_181',['result_of&lt; Func(ArgType0, ArgType1)&gt;',['../structEigen_1_1internal_1_1result__of_3_01Func_07ArgType0_00_01ArgType1_08_4.html',1,'Eigen::internal']]],
  ['result_5fof_3c_20scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_20_3e_28scalar_2c_20scalar_29_3e_182',['result_of&lt; scalar_cmp_op&lt; Scalar, Cmp &gt;(Scalar, Scalar)&gt;',['../structEigen_1_1internal_1_1result__of_3_01scalar__cmp__op_3_01Scalar_00_01Cmp_01_4_07Scalar_00_01Scalar_08_4.html',1,'Eigen::internal']]],
  ['returnbyvalue_183',['ReturnByValue',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20fullpivhouseholderqrmatrixqreturntype_3c_20matrixtype_20_3e_20_3e_184',['ReturnByValue&lt; FullPivHouseholderQRMatrixQReturnType&lt; MatrixType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20hessenbergdecompositionmatrixhreturntype_3c_20matrixtype_20_3e_20_3e_185',['ReturnByValue&lt; HessenbergDecompositionMatrixHReturnType&lt; MatrixType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20homogeneous_5fleft_5fproduct_5fimpl_3c_20homogeneous_3c_20matrixtype_2c_20vertical_20_3e_2c_20lhs_20_3e_20_3e_186',['ReturnByValue&lt; homogeneous_left_product_impl&lt; Homogeneous&lt; MatrixType, Vertical &gt;, Lhs &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20homogeneous_5fright_5fproduct_5fimpl_3c_20homogeneous_3c_20matrixtype_2c_20horizontal_20_3e_2c_20rhs_20_3e_20_3e_187',['ReturnByValue&lt; homogeneous_right_product_impl&lt; Homogeneous&lt; MatrixType, Horizontal &gt;, Rhs &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20image_5fretval_5fbase_3c_20_5fdecompositiontype_20_3e_20_3e_188',['ReturnByValue&lt; image_retval_base&lt; _DecompositionType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20image_5fretval_5fbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e_20_3e_189',['ReturnByValue&lt; image_retval_base&lt; FullPivLU&lt; _MatrixType &gt; &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20kernel_5fretval_5fbase_3c_20_5fdecompositiontype_20_3e_20_3e_190',['ReturnByValue&lt; kernel_retval_base&lt; _DecompositionType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20kernel_5fretval_5fbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e_20_3e_191',['ReturnByValue&lt; kernel_retval_base&lt; FullPivLU&lt; _MatrixType &gt; &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20sparseqr_5fqproduct_3c_20sparseqrtype_2c_20derived_20_3e_20_3e_192',['ReturnByValue&lt; SparseQR_QProduct&lt; SparseQRType, Derived &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20spqr_5fqproduct_3c_20spqrtype_2c_20derived_20_3e_20_3e_193',['ReturnByValue&lt; SPQR_QProduct&lt; SPQRType, Derived &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20triangular_5fsolve_5fretval_3c_20side_2c_20triangulartype_2c_20rhs_20_3e_20_3e_194',['ReturnByValue&lt; triangular_solve_retval&lt; Side, TriangularType, Rhs &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20tridiagonalizationmatrixtreturntype_3c_20matrixtype_20_3e_20_3e_195',['ReturnByValue&lt; TridiagonalizationMatrixTReturnType&lt; MatrixType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returning_196',['Returning',['../structReturning.html',1,'']]],
  ['returntype_197',['returntype',['../structrabit_1_1engine_1_1AllreduceBase_1_1ReturnType.html',1,'rabit::engine::AllreduceBase::ReturnType'],['../structEigen_1_1VectorwiseOp_1_1ReturnType.html',1,'Eigen::VectorwiseOp&lt; ExpressionType, Direction &gt;::ReturnType&lt; Functor, Scalar_ &gt;']]],
  ['reusablespace_198',['ReusableSpace',['../structReusableSpace.html',1,'']]],
  ['reverse_199',['Reverse',['../classEigen_1_1Reverse.html',1,'Eigen']]],
  ['reverse_5fpacket_5fcond_200',['reverse_packet_cond',['../structEigen_1_1internal_1_1reverse__packet__cond.html',1,'Eigen::internal']]],
  ['reverse_5fpacket_5fcond_3c_20packettype_2c_20false_20_3e_201',['reverse_packet_cond&lt; PacketType, false &gt;',['../structEigen_1_1internal_1_1reverse__packet__cond_3_01PacketType_00_01false_01_4.html',1,'Eigen::internal']]],
  ['reverseinneriterator_202',['reverseinneriterator',['../classEigen_1_1internal_1_1unary__evaluator_3_01Transpose_3_01ArgType_01_4_00_01IteratorBased_01_4_1_1ReverseInnerIterator.html',1,'Eigen::internal::unary_evaluator&lt; Transpose&lt; ArgType &gt;, IteratorBased &gt;::ReverseInnerIterator'],['../classEigen_1_1SparseCompressedBase_1_1ReverseInnerIterator.html',1,'Eigen::SparseCompressedBase&lt; Derived &gt;::ReverseInnerIterator'],['../classEigen_1_1TriangularViewImpl_3_01MatrixType_00_01Mode_00_01Sparse_01_4_1_1ReverseInnerIterator.html',1,'Eigen::TriangularViewImpl&lt; MatrixType, Mode, Sparse &gt;::ReverseInnerIterator']]],
  ['rf_203',['RF',['../classLightGBM_1_1RF.html',1,'LightGBM']]],
  ['rmmallocator_204',['RMMAllocator',['../classxgboost_1_1RMMAllocator.html',1,'xgboost']]],
  ['rmsemetric_205',['RMSEMetric',['../classLightGBM_1_1RMSEMetric.html',1,'LightGBM']]],
  ['roc_5fand_5ffilter_5fparams_206',['ROC_And_Filter_Params',['../structROC__And__Filter__Params.html',1,'']]],
  ['roc_5fparams_207',['ROC_Params',['../classROC__Params.html',1,'']]],
  ['rotation2d_208',['Rotation2D',['../classEigen_1_1Rotation2D.html',1,'Eigen']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_209',['rotation_base_generic_product_selector',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector.html',1,'Eigen::internal']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_3c_20rotationderived_2c_20diagonalmatrix_3c_20scalar_2c_20dim_2c_20maxdim_20_3e_2c_20false_20_3e_210',['rotation_base_generic_product_selector&lt; RotationDerived, DiagonalMatrix&lt; Scalar, Dim, MaxDim &gt;, false &gt;',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector_3_01RotationDerived_00_01Dce6ab4d4618a8a7d711ee4fd66ebeba4.html',1,'Eigen::internal']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_3c_20rotationderived_2c_20matrixtype_2c_20false_20_3e_211',['rotation_base_generic_product_selector&lt; RotationDerived, MatrixType, false &gt;',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector_3_01RotationDerived_00_01MatrixType_00_01false_01_4.html',1,'Eigen::internal']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_3c_20rotationderived_2c_20othervectortype_2c_20true_20_3e_212',['rotation_base_generic_product_selector&lt; RotationDerived, OtherVectorType, true &gt;',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector_3_01RotationDerived_00_01OtherVectorType_00_01true_01_4.html',1,'Eigen::internal']]],
  ['rotationbase_213',['RotationBase',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20angleaxis_3c_20_5fscalar_20_3e_2c_203_20_3e_214',['RotationBase&lt; AngleAxis&lt; _Scalar &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20derived_2c_203_20_3e_215',['RotationBase&lt; Derived, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20map_3c_20const_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_2c_203_20_3e_216',['RotationBase&lt; Map&lt; const Quaternion&lt; _Scalar &gt;, _Options &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20map_3c_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_2c_203_20_3e_217',['RotationBase&lt; Map&lt; Quaternion&lt; _Scalar &gt;, _Options &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20quaternion_3c_20_5fscalar_2c_20_5foptions_20_3e_2c_203_20_3e_218',['RotationBase&lt; Quaternion&lt; _Scalar, _Options &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20rotation2d_3c_20_5fscalar_20_3e_2c_202_20_3e_219',['RotationBase&lt; Rotation2D&lt; _Scalar &gt;, 2 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['round_5fimpl_220',['round_impl',['../structEigen_1_1internal_1_1round__impl.html',1,'Eigen::internal']]],
  ['round_5fretval_221',['round_retval',['../structEigen_1_1internal_1_1round__retval.html',1,'Eigen::internal']]],
  ['row_222',['Row',['../classdmlc_1_1Row.html',1,'dmlc']]],
  ['rowblock_223',['RowBlock',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20indextype_2c_20real_5ft_20_3e_224',['RowBlock&lt; IndexType, real_t &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20uint32_5ft_20_3e_225',['RowBlock&lt; uint32_t &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20uint32_5ft_2c_20float_20_3e_226',['RowBlock&lt; uint32_t, float &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblockcontainer_227',['RowBlockContainer',['../structdmlc_1_1data_1_1RowBlockContainer.html',1,'dmlc::data']]],
  ['rowblockcontainer_3c_20indextype_2c_20real_5ft_20_3e_228',['RowBlockContainer&lt; IndexType, real_t &gt;',['../structdmlc_1_1data_1_1RowBlockContainer.html',1,'dmlc::data']]],
  ['rowblockiter_229',['RowBlockIter',['../classdmlc_1_1RowBlockIter.html',1,'dmlc']]],
  ['rowblockiter_3c_20indextype_2c_20real_5ft_20_3e_230',['RowBlockIter&lt; IndexType, real_t &gt;',['../classdmlc_1_1RowBlockIter.html',1,'dmlc']]],
  ['rowloadinfo_231',['RowLoadInfo',['../structRowLoadInfo.html',1,'']]],
  ['rowset_232',['RowSet',['../structRowSet.html',1,'']]],
  ['rowsetchunk_233',['RowSetChunk',['../structRowSetChunk.html',1,'']]],
  ['rowsetcollection_234',['RowSetCollection',['../classxgboost_1_1common_1_1RowSetCollection.html',1,'xgboost::common']]],
  ['rowsetentry_235',['RowSetEntry',['../structRowSetEntry.html',1,'']]],
  ['rtreenodestat_236',['RTreeNodeStat',['../structxgboost_1_1RTreeNodeStat.html',1,'xgboost']]],
  ['runtimeflags_237',['RuntimeFlags',['../structxgboost_1_1common_1_1RuntimeFlags.html',1,'xgboost::common']]],
  ['ryupowlogutils_238',['RyuPowLogUtils',['../structxgboost_1_1detail_1_1RyuPowLogUtils.html',1,'xgboost::detail']]],
  ['ryuprinter_239',['RyuPrinter',['../classxgboost_1_1detail_1_1RyuPrinter.html',1,'xgboost::detail']]]
];
