var searchData=
[
  ['handler_0',['handler',['../structdmlc_1_1serializer_1_1Handler.html',1,'dmlc::serializer::Handler&lt; T &gt;'],['../structdmlc_1_1lua__stack_1_1Handler.html',1,'dmlc::lua_stack::Handler&lt; T &gt;'],['../classrapidjson_1_1Handler.html',1,'Handler']]],
  ['handler_3c_20xgboost_3a_3aentry_20_3e_1',['Handler&lt; xgboost::Entry &gt;',['../structdmlc_1_1serializer_1_1Handler_3_01xgboost_1_1Entry_01_4.html',1,'dmlc::serializer']]],
  ['handlerterminateatendarray_2',['HandlerTerminateAtEndArray',['../structHandlerTerminateAtEndArray.html',1,'']]],
  ['handlerterminateatendobject_3',['HandlerTerminateAtEndObject',['../structHandlerTerminateAtEndObject.html',1,'']]],
  ['handlerterminateatstartarray_4',['HandlerTerminateAtStartArray',['../structHandlerTerminateAtStartArray.html',1,'']]],
  ['handlerterminateatstartobject_5',['HandlerTerminateAtStartObject',['../structHandlerTerminateAtStartObject.html',1,'']]],
  ['handleseprecord_6',['handleSepRecord',['../structhandleSepRecord.html',1,'']]],
  ['handleseprecord_3c_20tuple_2c_200_20_3e_7',['handleSepRecord&lt; Tuple, 0 &gt;',['../structhandleSepRecord_3_01Tuple_00_010_01_4.html',1,'']]],
  ['handlesinglepos_8',['handleSinglePos',['../structhandleSinglePos.html',1,'']]],
  ['has_5fdirect_5faccess_9',['has_direct_access',['../structEigen_1_1internal_1_1has__direct__access.html',1,'Eigen::internal']]],
  ['has_5ffrom_5fjson_10',['has_from_json',['../structdetail_1_1has__from__json.html',1,'detail']]],
  ['has_5ffrom_5fjson_3c_20basicjsontype_2c_20t_2c_20enable_5fif_5ft_3c_20_21is_5fbasic_5fjson_3c_20t_20_3e_3a_3avalue_20_3e_20_3e_11',['has_from_json&lt; BasicJsonType, T, enable_if_t&lt; !is_basic_json&lt; T &gt;::value &gt; &gt;',['../structdetail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html',1,'detail']]],
  ['has_5fkey_5fcompare_12',['has_key_compare',['../structdetail_1_1has__key__compare.html',1,'detail']]],
  ['has_5fnon_5fdefault_5ffrom_5fjson_13',['has_non_default_from_json',['../structdetail_1_1has__non__default__from__json.html',1,'detail']]],
  ['has_5fnon_5fdefault_5ffrom_5fjson_3c_20basicjsontype_2c_20t_2c_20enable_5fif_5ft_3c_20_21is_5fbasic_5fjson_3c_20t_20_3e_3a_3avalue_20_3e_20_3e_14',['has_non_default_from_json&lt; BasicJsonType, T, enable_if_t&lt; !is_basic_json&lt; T &gt;::value &gt; &gt;',['../structdetail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_912047717fa07cfa9d99fe9eafcf1e11e.html',1,'detail']]],
  ['has_5fnone_15',['has_none',['../structEigen_1_1internal_1_1has__none.html',1,'Eigen::internal']]],
  ['has_5fsaveload_16',['has_saveload',['../structdmlc_1_1has__saveload.html',1,'dmlc']]],
  ['has_5fstd_5fresult_5ftype_17',['has_std_result_type',['../structEigen_1_1internal_1_1has__std__result__type.html',1,'Eigen::internal']]],
  ['has_5fto_5fjson_18',['has_to_json',['../structdetail_1_1has__to__json.html',1,'detail']]],
  ['has_5fto_5fjson_3c_20basicjsontype_2c_20t_2c_20enable_5fif_5ft_3c_20_21is_5fbasic_5fjson_3c_20t_20_3e_3a_3avalue_20_3e_20_3e_19',['has_to_json&lt; BasicJsonType, T, enable_if_t&lt; !is_basic_json&lt; T &gt;::value &gt; &gt;',['../structdetail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html',1,'detail']]],
  ['has_5ftr1_5fresult_20',['has_tr1_result',['../structEigen_1_1internal_1_1has__tr1__result.html',1,'Eigen::internal']]],
  ['hasarbitraryparamsdict_21',['HasArbitraryParamsDict',['../classxgboost_1_1spark_1_1params_1_1HasArbitraryParamsDict.html',1,'xgboost::spark::params']]],
  ['hasbasemargincol_22',['HasBaseMarginCol',['../classxgboost_1_1spark_1_1params_1_1HasBaseMarginCol.html',1,'xgboost::spark::params']]],
  ['hascontribpredictioncol_23',['HasContribPredictionCol',['../classxgboost_1_1spark_1_1params_1_1HasContribPredictionCol.html',1,'xgboost::spark::params']]],
  ['hasenablesparsedataoptim_24',['HasEnableSparseDataOptim',['../classxgboost_1_1spark_1_1params_1_1HasEnableSparseDataOptim.html',1,'xgboost::spark::params']]],
  ['hasfeaturescols_25',['HasFeaturesCols',['../classxgboost_1_1spark_1_1params_1_1HasFeaturesCols.html',1,'xgboost::spark::params']]],
  ['hash_26',['hash',['../structxgboost_1_1IntrusivePtr_1_1Hash.html',1,'xgboost::IntrusivePtr&lt; T &gt;::Hash'],['../structxgboost_1_1DMatrixCache_1_1Hash.html',1,'xgboost::DMatrixCache&lt; CacheT &gt;::Hash'],['../structHash.html',1,'Hash']]],
  ['hash_3c_20nlohmann_3a_3anlohmann_5fbasic_5fjson_5ftpl_20_3e_27',['hash&lt; nlohmann::NLOHMANN_BASIC_JSON_TPL &gt;',['../structstd_1_1hash_3_01nlohmann_1_1NLOHMANN__BASIC__JSON__TPL_01_4.html',1,'std']]],
  ['hash_3c_20xgboost_3a_3aintrusiveptr_3c_20t_20_3e_20_3e_28',['hash&lt; xgboost::IntrusivePtr&lt; T &gt; &gt;',['../structstd_1_1hash_3_01xgboost_1_1IntrusivePtr_3_01T_01_4_01_4.html',1,'std']]],
  ['hash_5felem_29',['hash_elem',['../structv__hashmap_1_1hash__elem.html',1,'v_hashmap']]],
  ['hashelem_30',['HashElem',['../structHashElem.html',1,'']]],
  ['hasher_31',['Hasher',['../classinternal_1_1Hasher.html',1,'internal']]],
  ['hashfunction_32',['hashfunction',['../structEffected__Field_1_1HashFunction.html',1,'Effected_Field::HashFunction'],['../structjson__req__export_1_1HashFunction.html',1,'json_req_export::HashFunction']]],
  ['hashutils_33',['HashUtils',['../classMultiWorldTesting_1_1HashUtils.html',1,'MultiWorldTesting']]],
  ['hasqueryidcol_34',['HasQueryIdCol',['../classxgboost_1_1spark_1_1params_1_1HasQueryIdCol.html',1,'xgboost::spark::params']]],
  ['hdfsfilesystem_35',['HDFSFileSystem',['../classdmlc_1_1io_1_1HDFSFileSystem.html',1,'dmlc::io']]],
  ['hdfsstream_36',['HDFSStream',['../classdmlc_1_1io_1_1HDFSStream.html',1,'dmlc::io']]],
  ['heap_5felem_37',['heap_elem',['../structheap__elem.html',1,'']]],
  ['hessenbergdecomposition_38',['HessenbergDecomposition',['../classEigen_1_1HessenbergDecomposition.html',1,'Eigen']]],
  ['hessenbergdecomposition_3c_20matrixtype_20_3e_39',['HessenbergDecomposition&lt; MatrixType &gt;',['../classEigen_1_1HessenbergDecomposition.html',1,'Eigen']]],
  ['hessenbergdecompositionmatrixhreturntype_40',['HessenbergDecompositionMatrixHReturnType',['../structEigen_1_1internal_1_1HessenbergDecompositionMatrixHReturnType.html',1,'Eigen::internal']]],
  ['hiddenindexinfo_41',['HiddenIndexInfo',['../structHiddenIndexInfo.html',1,'']]],
  ['hingeloss_42',['hingeloss',['../classhingeloss.html',1,'']]],
  ['histcollection_43',['HistCollection',['../classxgboost_1_1common_1_1HistCollection.html',1,'xgboost::common']]],
  ['histevaluator_44',['HistEvaluator',['../classxgboost_1_1tree_1_1HistEvaluator.html',1,'xgboost::tree']]],
  ['histmakertrainparam_45',['HistMakerTrainParam',['../structxgboost_1_1tree_1_1HistMakerTrainParam.html',1,'xgboost::tree']]],
  ['histmultievaluator_46',['HistMultiEvaluator',['../classxgboost_1_1tree_1_1HistMultiEvaluator.html',1,'xgboost::tree']]],
  ['histogrambinentry_47',['HistogramBinEntry',['../structLightGBM_1_1HistogramBinEntry.html',1,'LightGBM']]],
  ['histogrambuilder_48',['HistogramBuilder',['../classxgboost_1_1tree_1_1HistogramBuilder.html',1,'xgboost::tree']]],
  ['histogramcuts_49',['HistogramCuts',['../classxgboost_1_1common_1_1HistogramCuts.html',1,'xgboost::common']]],
  ['histogrampool_50',['HistogramPool',['../classLightGBM_1_1HistogramPool.html',1,'LightGBM']]],
  ['histupdater_51',['HistUpdater',['../classxgboost_1_1tree_1_1HistUpdater.html',1,'xgboost::tree']]],
  ['holder_52',['Holder',['../structVW_1_1Holder.html',1,'VW']]],
  ['holder_3c_20features_5fvalue_5findex_5fiterator_20_3e_53',['Holder&lt; features_value_index_iterator &gt;',['../structVW_1_1Holder.html',1,'VW']]],
  ['homogeneous_54',['Homogeneous',['../classEigen_1_1Homogeneous.html',1,'Eigen']]],
  ['homogeneous_5fleft_5fproduct_5fimpl_55',['homogeneous_left_product_impl',['../structEigen_1_1internal_1_1homogeneous__left__product__impl.html',1,'Eigen::internal']]],
  ['homogeneous_5fleft_5fproduct_5fimpl_3c_20homogeneous_3c_20matrixtype_2c_20vertical_20_3e_2c_20lhs_20_3e_56',['homogeneous_left_product_impl&lt; Homogeneous&lt; MatrixType, Vertical &gt;, Lhs &gt;',['../structEigen_1_1internal_1_1homogeneous__left__product__impl_3_01Homogeneous_3_01MatrixType_00_01Vertical_01_4_00_01Lhs_01_4.html',1,'Eigen::internal']]],
  ['homogeneous_5fleft_5fproduct_5frefactoring_5fhelper_57',['homogeneous_left_product_refactoring_helper',['../structEigen_1_1internal_1_1homogeneous__left__product__refactoring__helper.html',1,'Eigen::internal']]],
  ['homogeneous_5fright_5fproduct_5fimpl_58',['homogeneous_right_product_impl',['../structEigen_1_1internal_1_1homogeneous__right__product__impl.html',1,'Eigen::internal']]],
  ['homogeneous_5fright_5fproduct_5fimpl_3c_20homogeneous_3c_20matrixtype_2c_20horizontal_20_3e_2c_20rhs_20_3e_59',['homogeneous_right_product_impl&lt; Homogeneous&lt; MatrixType, Horizontal &gt;, Rhs &gt;',['../structEigen_1_1internal_1_1homogeneous__right__product__impl_3_01Homogeneous_3_01MatrixType_00_01Horizontal_01_4_00_01Rhs_01_4.html',1,'Eigen::internal']]],
  ['homogeneous_5fright_5fproduct_5frefactoring_5fhelper_60',['homogeneous_right_product_refactoring_helper',['../structEigen_1_1internal_1_1homogeneous__right__product__refactoring__helper.html',1,'Eigen::internal']]],
  ['homogeneousshape_61',['HomogeneousShape',['../structEigen_1_1HomogeneousShape.html',1,'Eigen']]],
  ['hostdevicevector_62',['HostDeviceVector',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20bst_5ffloat_20_3e_63',['HostDeviceVector&lt; bst_float &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20bst_5fgroup_5ft_20_3e_64',['HostDeviceVector&lt; bst_group_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20bst_5frow_5ft_20_3e_65',['HostDeviceVector&lt; bst_row_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20double_20_3e_66',['HostDeviceVector&lt; double &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20featuretype_20_3e_67',['HostDeviceVector&lt; FeatureType &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20float_20_3e_68',['HostDeviceVector&lt; float &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20int_20_3e_69',['HostDeviceVector&lt; int &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20int32_5ft_20_3e_70',['HostDeviceVector&lt; int32_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20std_3a_3asize_5ft_20_3e_71',['HostDeviceVector&lt; std::size_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20std_3a_3auint8_5ft_20_3e_72',['HostDeviceVector&lt; std::uint8_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20uint32_5ft_20_3e_73',['HostDeviceVector&lt; uint32_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20xgboost_3a_3adetail_3a_3agradientpairinternal_20_3e_74',['HostDeviceVector&lt; xgboost::detail::GradientPairInternal &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20xgboost_3a_3aentry_20_3e_75',['HostDeviceVector&lt; xgboost::Entry &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevectorimpl_76',['HostDeviceVectorImpl',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20bst_5ffloat_20_3e_77',['HostDeviceVectorImpl&lt; bst_float &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20bst_5fgroup_5ft_20_3e_78',['HostDeviceVectorImpl&lt; bst_group_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20bst_5frow_5ft_20_3e_79',['HostDeviceVectorImpl&lt; bst_row_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20double_20_3e_80',['HostDeviceVectorImpl&lt; double &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20featuretype_20_3e_81',['HostDeviceVectorImpl&lt; FeatureType &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20float_20_3e_82',['HostDeviceVectorImpl&lt; float &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20int_20_3e_83',['HostDeviceVectorImpl&lt; int &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20int32_5ft_20_3e_84',['HostDeviceVectorImpl&lt; int32_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20std_3a_3asize_5ft_20_3e_85',['HostDeviceVectorImpl&lt; std::size_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20std_3a_3auint8_5ft_20_3e_86',['HostDeviceVectorImpl&lt; std::uint8_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20uint32_5ft_20_3e_87',['HostDeviceVectorImpl&lt; uint32_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20xgboost_3a_3adetail_3a_3agradientpairinternal_20_3e_88',['HostDeviceVectorImpl&lt; xgboost::detail::GradientPairInternal &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20xgboost_3a_3aentry_20_3e_89',['HostDeviceVectorImpl&lt; xgboost::Entry &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostsketchcontainer_90',['HostSketchContainer',['../classxgboost_1_1common_1_1HostSketchContainer.html',1,'xgboost::common']]],
  ['hostsparsepageview_91',['HostSparsePageView',['../structxgboost_1_1HostSparsePageView.html',1,'xgboost']]],
  ['householder_5fqr_5finplace_5fblocked_92',['householder_qr_inplace_blocked',['../structEigen_1_1internal_1_1householder__qr__inplace__blocked.html',1,'Eigen::internal']]],
  ['householderqr_93',['HouseholderQR',['../classEigen_1_1HouseholderQR.html',1,'Eigen']]],
  ['householderqr_3c_20matrixtype_20_3e_94',['HouseholderQR&lt; MatrixType &gt;',['../classEigen_1_1HouseholderQR.html',1,'Eigen']]],
  ['householderqr_3c_20transposetypewithsamestorageorder_20_3e_95',['HouseholderQR&lt; TransposeTypeWithSameStorageOrder &gt;',['../classEigen_1_1HouseholderQR.html',1,'Eigen']]],
  ['householdersequence_96',['HouseholderSequence',['../classEigen_1_1HouseholderSequence.html',1,'Eigen']]],
  ['householdersequenceshape_97',['HouseholderSequenceShape',['../structEigen_1_1internal_1_1HouseholderSequenceShape.html',1,'Eigen::internal']]],
  ['hseq_5fside_5fdependent_5fimpl_98',['hseq_side_dependent_impl',['../structEigen_1_1internal_1_1hseq__side__dependent__impl.html',1,'Eigen::internal']]],
  ['hseq_5fside_5fdependent_5fimpl_3c_20vectorstype_2c_20coeffstype_2c_20ontheright_20_3e_99',['hseq_side_dependent_impl&lt; VectorsType, CoeffsType, OnTheRight &gt;',['../structEigen_1_1internal_1_1hseq__side__dependent__impl_3_01VectorsType_00_01CoeffsType_00_01OnTheRight_01_4.html',1,'Eigen::internal']]],
  ['httpreadstream_100',['HttpReadStream',['../classdmlc_1_1io_1_1s3_1_1HttpReadStream.html',1,'dmlc::io::s3']]],
  ['huberlossmetric_101',['HuberLossMetric',['../classLightGBM_1_1HuberLossMetric.html',1,'LightGBM']]],
  ['hyperoptimizer_102',['HyperOptimizer',['../classvw-hyperopt_1_1HyperOptimizer.html',1,'vw-hyperopt']]],
  ['hyperoptspaceconstructor_103',['HyperoptSpaceConstructor',['../classvw-hyperopt_1_1HyperoptSpaceConstructor.html',1,'vw-hyperopt']]],
  ['hyperplane_104',['Hyperplane',['../classEigen_1_1Hyperplane.html',1,'Eigen']]],
  ['hypot_5fimpl_105',['hypot_impl',['../structEigen_1_1internal_1_1hypot__impl.html',1,'Eigen::internal']]],
  ['hypot_5fretval_106',['hypot_retval',['../structEigen_1_1internal_1_1hypot__retval.html',1,'Eigen::internal']]]
];
