var searchData=
[
  ['rabitcommunicator_0',['RabitCommunicator',['../classxgboost_1_1collective_1_1RabitCommunicator.html',1,'xgboost::collective']]],
  ['rabitcontext_1',['RabitContext',['../classxgboost_1_1rabit_1_1RabitContext.html',1,'xgboost::rabit']]],
  ['rabittracker_2',['rabittracker',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1RabitTracker.html',1,'ml.dmlc.xgboost4j.java.RabitTracker'],['../classdmlc__tracker_1_1tracker_1_1RabitTracker.html',1,'dmlc_tracker.tracker.RabitTracker'],['../classxgboost_1_1tracker_1_1RabitTracker.html',1,'xgboost.tracker.RabitTracker']]],
  ['random_3',['Random',['../classLightGBM_1_1Random.html',1,'LightGBM']]],
  ['random_5fdefault_5fimpl_4',['random_default_impl',['../structEigen_1_1internal_1_1random__default__impl.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20false_2c_20false_20_3e_5',['random_default_impl&lt; Scalar, false, false &gt;',['../structEigen_1_1internal_1_1random__default__impl_3_01Scalar_00_01false_00_01false_01_4.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20false_2c_20true_20_3e_6',['random_default_impl&lt; Scalar, false, true &gt;',['../structEigen_1_1internal_1_1random__default__impl_3_01Scalar_00_01false_00_01true_01_4.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20numtraits_3c_20scalar_20_3e_3a_3aiscomplex_2c_20numtraits_3c_20scalar_20_3e_3a_3aisinteger_20_3e_7',['random_default_impl&lt; Scalar, NumTraits&lt; Scalar &gt;::IsComplex, NumTraits&lt; Scalar &gt;::IsInteger &gt;',['../structEigen_1_1internal_1_1random__default__impl.html',1,'Eigen::internal']]],
  ['random_5fdefault_5fimpl_3c_20scalar_2c_20true_2c_20false_20_3e_8',['random_default_impl&lt; Scalar, true, false &gt;',['../structEigen_1_1internal_1_1random__default__impl_3_01Scalar_00_01true_00_01false_01_4.html',1,'Eigen::internal']]],
  ['random_5fimpl_9',['random_impl',['../structEigen_1_1internal_1_1random__impl.html',1,'Eigen::internal']]],
  ['random_5fimpl_3c_20bool_20_3e_10',['random_impl&lt; bool &gt;',['../structEigen_1_1internal_1_1random__impl_3_01bool_01_4.html',1,'Eigen::internal']]],
  ['random_5fretval_11',['random_retval',['../structEigen_1_1internal_1_1random__retval.html',1,'Eigen::internal']]],
  ['randomdatagenerator_12',['RandomDataGenerator',['../classxgboost_1_1RandomDataGenerator.html',1,'xgboost']]],
  ['randomfeatureselector_13',['RandomFeatureSelector',['../classxgboost_1_1linear_1_1RandomFeatureSelector.html',1,'xgboost::linear']]],
  ['randomreplace_14',['RandomReplace',['../structxgboost_1_1tree_1_1RandomReplace.html',1,'xgboost::tree']]],
  ['randomsamplesgenerator_15',['RandomSamplesGenerator',['../classRandomSamplesGenerator.html',1,'']]],
  ['randomthreadlocalentry_16',['RandomThreadLocalEntry',['../structxgboost_1_1common_1_1RandomThreadLocalEntry.html',1,'xgboost::common']]],
  ['range_17',['Range',['../classxgboost_1_1common_1_1Range.html',1,'xgboost::common']]],
  ['range1d_18',['Range1d',['../classxgboost_1_1common_1_1Range1d.html',1,'xgboost::common']]],
  ['rangecalculator_19',['RangeCalculator',['../classRangeCalculator.html',1,'']]],
  ['rangefeatgenerator_20',['RangeFeatGenerator',['../classRangeFeatGenerator.html',1,'']]],
  ['rangestatus_21',['RangeStatus',['../structRangeStatus.html',1,'']]],
  ['rangetag_22',['RangeTag',['../structxgboost_1_1linalg_1_1detail_1_1RangeTag.html',1,'xgboost::linalg::detail']]],
  ['rankingcache_23',['RankingCache',['../classxgboost_1_1ltr_1_1RankingCache.html',1,'xgboost::ltr']]],
  ['ratiocalculator_24',['RatioCalculator',['../classRatioCalculator.html',1,'']]],
  ['rbitspolicy_25',['RBitsPolicy',['../structxgboost_1_1RBitsPolicy.html',1,'xgboost']]],
  ['readstream_26',['ReadStream',['../classdmlc_1_1io_1_1s3_1_1ReadStream.html',1,'dmlc::io::s3']]],
  ['readstringstream_27',['ReadStringStream',['../structdmlc_1_1io_1_1s3_1_1ReadStringStream.html',1,'dmlc::io::s3']]],
  ['readwrapper_28',['ReadWrapper',['../structrabit_1_1c__api_1_1ReadWrapper.html',1,'rabit::c_api']]],
  ['real_5fdefault_5fimpl_29',['real_default_impl',['../structEigen_1_1internal_1_1real__default__impl.html',1,'Eigen::internal']]],
  ['real_5fdefault_5fimpl_3c_20scalar_2c_20true_20_3e_30',['real_default_impl&lt; Scalar, true &gt;',['../structEigen_1_1internal_1_1real__default__impl_3_01Scalar_00_01true_01_4.html',1,'Eigen::internal']]],
  ['real_5fimpl_31',['real_impl',['../structEigen_1_1internal_1_1real__impl.html',1,'Eigen::internal']]],
  ['real_5fref_5fimpl_32',['real_ref_impl',['../structEigen_1_1internal_1_1real__ref__impl.html',1,'Eigen::internal']]],
  ['real_5fref_5fretval_33',['real_ref_retval',['../structEigen_1_1internal_1_1real__ref__retval.html',1,'Eigen::internal']]],
  ['real_5fretval_34',['real_retval',['../structEigen_1_1internal_1_1real__retval.html',1,'Eigen::internal']]],
  ['reallocvector_35',['ReallocVector',['../classxgboost_1_1common_1_1ReallocVector.html',1,'xgboost::common']]],
  ['realqz_36',['RealQZ',['../classEigen_1_1RealQZ.html',1,'Eigen']]],
  ['realqz_3c_20matrixtype_20_3e_37',['RealQZ&lt; MatrixType &gt;',['../classEigen_1_1RealQZ.html',1,'Eigen']]],
  ['realschur_38',['RealSchur',['../classEigen_1_1RealSchur.html',1,'Eigen']]],
  ['realschur_3c_20matrixtype_20_3e_39',['RealSchur&lt; MatrixType &gt;',['../classEigen_1_1RealSchur.html',1,'Eigen']]],
  ['rebind_40',['rebind',['../structEigen_1_1aligned__allocator_1_1rebind.html',1,'Eigen::aligned_allocator&lt; T &gt;::rebind&lt; U &gt;'],['../structEigen_1_1aligned__allocator__indirection_1_1rebind.html',1,'Eigen::aligned_allocator_indirection&lt; T &gt;::rebind&lt; U &gt;'],['../structxgboost_1_1common_1_1cuda_1_1pinned__allocator_1_1rebind.html',1,'xgboost::common::cuda::pinned_allocator&lt; T &gt;::rebind&lt; U &gt;'],['../structxgboost_1_1common_1_1cuda_1_1pinned__allocator_3_01void_01_4_1_1rebind.html',1,'xgboost::common::cuda::pinned_allocator&lt; void &gt;::rebind']]],
  ['recordbatchesiteradapter_41',['RecordBatchesIterAdapter',['../classxgboost_1_1data_1_1RecordBatchesIterAdapter.html',1,'xgboost::data']]],
  ['recorddata_42',['RecordData',['../classRecordData.html',1,'']]],
  ['recordiochunkreader_43',['RecordIOChunkReader',['../classdmlc_1_1RecordIOChunkReader.html',1,'dmlc']]],
  ['recordioreader_44',['RecordIOReader',['../classdmlc_1_1RecordIOReader.html',1,'dmlc']]],
  ['recordiosplitter_45',['RecordIOSplitter',['../classdmlc_1_1io_1_1RecordIOSplitter.html',1,'dmlc::io']]],
  ['recordiowriter_46',['RecordIOWriter',['../classdmlc_1_1RecordIOWriter.html',1,'dmlc']]],
  ['recursivehalvingmap_47',['RecursiveHalvingMap',['../classLightGBM_1_1RecursiveHalvingMap.html',1,'LightGBM']]],
  ['redux_5fevaluator_48',['redux_evaluator',['../classEigen_1_1internal_1_1redux__evaluator.html',1,'Eigen::internal']]],
  ['redux_5fimpl_49',['redux_impl',['../structEigen_1_1internal_1_1redux__impl.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20defaulttraversal_2c_20completeunrolling_20_3e_50',['redux_impl&lt; Func, Derived, DefaultTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01DefaultTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20defaulttraversal_2c_20nounrolling_20_3e_51',['redux_impl&lt; Func, Derived, DefaultTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01DefaultTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20linearvectorizedtraversal_2c_20completeunrolling_20_3e_52',['redux_impl&lt; Func, Derived, LinearVectorizedTraversal, CompleteUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01LinearVectorizedTraversal_00_01CompleteUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20linearvectorizedtraversal_2c_20nounrolling_20_3e_53',['redux_impl&lt; Func, Derived, LinearVectorizedTraversal, NoUnrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01LinearVectorizedTraversal_00_01NoUnrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fimpl_3c_20func_2c_20derived_2c_20slicevectorizedtraversal_2c_20unrolling_20_3e_54',['redux_impl&lt; Func, Derived, SliceVectorizedTraversal, Unrolling &gt;',['../structEigen_1_1internal_1_1redux__impl_3_01Func_00_01Derived_00_01SliceVectorizedTraversal_00_01Unrolling_01_4.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_55',['redux_novec_unroller',['../structEigen_1_1internal_1_1redux__novec__unroller.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_3c_20func_2c_20derived_2c_200_2c_20derived_3a_3asizeatcompiletime_20_3e_56',['redux_novec_unroller&lt; Func, Derived, 0, Derived::SizeAtCompileTime &gt;',['../structEigen_1_1internal_1_1redux__novec__unroller.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_3c_20func_2c_20derived_2c_20start_2c_200_20_3e_57',['redux_novec_unroller&lt; Func, Derived, Start, 0 &gt;',['../structEigen_1_1internal_1_1redux__novec__unroller_3_01Func_00_01Derived_00_01Start_00_010_01_4.html',1,'Eigen::internal']]],
  ['redux_5fnovec_5funroller_3c_20func_2c_20derived_2c_20start_2c_201_20_3e_58',['redux_novec_unroller&lt; Func, Derived, Start, 1 &gt;',['../structEigen_1_1internal_1_1redux__novec__unroller_3_01Func_00_01Derived_00_01Start_00_011_01_4.html',1,'Eigen::internal']]],
  ['redux_5ftraits_59',['redux_traits',['../structEigen_1_1internal_1_1redux__traits.html',1,'Eigen::internal']]],
  ['redux_5fvec_5funroller_60',['redux_vec_unroller',['../structEigen_1_1internal_1_1redux__vec__unroller.html',1,'Eigen::internal']]],
  ['redux_5fvec_5funroller_3c_20func_2c_20derived_2c_20start_2c_201_20_3e_61',['redux_vec_unroller&lt; Func, Derived, Start, 1 &gt;',['../structEigen_1_1internal_1_1redux__vec__unroller_3_01Func_00_01Derived_00_01Start_00_011_01_4.html',1,'Eigen::internal']]],
  ['reduxreturntype_62',['ReduxReturnType',['../structEigen_1_1VectorwiseOp_1_1ReduxReturnType.html',1,'Eigen::VectorwiseOp']]],
  ['ref_63',['Ref',['../classEigen_1_1Ref.html',1,'Eigen']]],
  ['ref_3c_20const_20matrixtype_20_3e_64',['Ref&lt; const MatrixType &gt;',['../classEigen_1_1Ref.html',1,'Eigen']]],
  ['ref_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_65',['Ref&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01const_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20const_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_66',['Ref&lt; const SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01const_01SparseVector_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20const_20tplainobjecttype_2c_20options_2c_20stridetype_20_3e_67',['Ref&lt; const TPlainObjectType, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01const_01TPlainObjectType_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20const_20umfpackmatrixtype_2c_20standardcompressedformat_20_3e_68',['Ref&lt; const UmfpackMatrixType, StandardCompressedFormat &gt;',['../classEigen_1_1Ref.html',1,'Eigen']]],
  ['ref_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_69',['Ref&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_3c_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_70',['Ref&lt; SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../classEigen_1_1Ref_3_01SparseVector_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html',1,'Eigen']]],
  ['ref_5fselector_71',['ref_selector',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20expressiontype_20_3e_72',['ref_selector&lt; ExpressionType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20lhs_20_3e_73',['ref_selector&lt; Lhs &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20lhstype_20_3e_74',['ref_selector&lt; LhsType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20matrixtype_20_3e_75',['ref_selector&lt; MatrixType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20rhs_20_3e_76',['ref_selector&lt; Rhs &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20rhstype_20_3e_77',['ref_selector&lt; RhsType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['ref_5fselector_3c_20xprtype_20_3e_78',['ref_selector&lt; XprType &gt;',['../structEigen_1_1internal_1_1ref__selector.html',1,'Eigen::internal']]],
  ['refbase_79',['RefBase',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20const_20matrixtype_2c_20options_2c_20stridetype_20_3e_20_3e_80',['RefBase&lt; Ref&lt; const MatrixType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20const_20tplainobjecttype_2c_20options_2c_20stridetype_20_3e_20_3e_81',['RefBase&lt; Ref&lt; const TPlainObjectType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20const_20umfpackmatrixtype_2c_20options_2c_20stridetype_20_3e_20_3e_82',['RefBase&lt; Ref&lt; const UmfpackMatrixType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['refbase_3c_20ref_3c_20plainobjecttype_2c_20options_2c_20stridetype_20_3e_20_3e_83',['RefBase&lt; Ref&lt; PlainObjectType, Options, StrideType &gt; &gt;',['../classEigen_1_1RefBase.html',1,'Eigen']]],
  ['reflinkvector_84',['RefLinkVector',['../structrabit_1_1engine_1_1AllreduceBase_1_1RefLinkVector.html',1,'rabit::engine::AllreduceBase']]],
  ['refresourceview_85',['RefResourceView',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20columntype_20_3e_86',['RefResourceView&lt; ColumnType &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20std_3a_3asize_5ft_20_3e_87',['RefResourceView&lt; std::size_t &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20std_3a_3auint8_5ft_20_3e_88',['RefResourceView&lt; std::uint8_t &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['registry_89',['Registry',['../classdmlc_1_1Registry.html',1,'dmlc']]],
  ['registrydecisionranges_90',['RegistryDecisionRanges',['../classRegistryDecisionRanges.html',1,'']]],
  ['registryevent_91',['RegistryEvent',['../classRegistryEvent.html',1,'']]],
  ['registrysignal_92',['RegistrySignal',['../classRegistrySignal.html',1,'']]],
  ['registrysignaland_93',['RegistrySignalAnd',['../classRegistrySignalAnd.html',1,'']]],
  ['registrysignalany_94',['RegistrySignalAny',['../classRegistrySignalAny.html',1,'']]],
  ['registrysignaldrug_95',['RegistrySignalDrug',['../classRegistrySignalDrug.html',1,'']]],
  ['registrysignalrange_96',['RegistrySignalRange',['../classRegistrySignalRange.html',1,'']]],
  ['registrysignalset_97',['RegistrySignalSet',['../classRegistrySignalSet.html',1,'']]],
  ['reglossobjoneapi_98',['RegLossObjOneAPI',['../classxgboost_1_1obj_1_1RegLossObjOneAPI.html',1,'xgboost::obj']]],
  ['reglossparamoneapi_99',['RegLossParamOneAPI',['../structxgboost_1_1obj_1_1RegLossParamOneAPI.html',1,'xgboost::obj']]],
  ['regression_5fparams_100',['Regression_Params',['../classRegression__Params.html',1,'']]],
  ['regressionfairloss_101',['RegressionFairLoss',['../classLightGBM_1_1RegressionFairLoss.html',1,'LightGBM']]],
  ['regressiongammaloss_102',['RegressionGammaLoss',['../classLightGBM_1_1RegressionGammaLoss.html',1,'LightGBM']]],
  ['regressionhuberloss_103',['RegressionHuberLoss',['../classLightGBM_1_1RegressionHuberLoss.html',1,'LightGBM']]],
  ['regressionl1loss_104',['RegressionL1loss',['../classLightGBM_1_1RegressionL1loss.html',1,'LightGBM']]],
  ['regressionl2loss_105',['RegressionL2loss',['../classLightGBM_1_1RegressionL2loss.html',1,'LightGBM']]],
  ['regressionmapeloss_106',['RegressionMAPELOSS',['../classLightGBM_1_1RegressionMAPELOSS.html',1,'LightGBM']]],
  ['regressionmetric_107',['RegressionMetric',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20fairlossmetric_20_3e_108',['RegressionMetric&lt; FairLossMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20gammadeviancemetric_20_3e_109',['RegressionMetric&lt; GammaDevianceMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20gammametric_20_3e_110',['RegressionMetric&lt; GammaMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20huberlossmetric_20_3e_111',['RegressionMetric&lt; HuberLossMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20l1metric_20_3e_112',['RegressionMetric&lt; L1Metric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20l2metric_20_3e_113',['RegressionMetric&lt; L2Metric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20mapemetric_20_3e_114',['RegressionMetric&lt; MAPEMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20poissonmetric_20_3e_115',['RegressionMetric&lt; PoissonMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20quantilemetric_20_3e_116',['RegressionMetric&lt; QuantileMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20rmsemetric_20_3e_117',['RegressionMetric&lt; RMSEMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20tweediemetric_20_3e_118',['RegressionMetric&lt; TweedieMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionpoissonloss_119',['RegressionPoissonLoss',['../classLightGBM_1_1RegressionPoissonLoss.html',1,'LightGBM']]],
  ['regressionquantileloss_120',['RegressionQuantileloss',['../classLightGBM_1_1RegressionQuantileloss.html',1,'LightGBM']]],
  ['regressiontweedieloss_121',['RegressionTweedieLoss',['../classLightGBM_1_1RegressionTweedieLoss.html',1,'LightGBM']]],
  ['regtree_122',['RegTree',['../classxgboost_1_1RegTree.html',1,'xgboost']]],
  ['reldatacv_123',['RelDataCV',['../classxgboost_1_1testing_1_1data_1_1RelDataCV.html',1,'xgboost::testing::data']]],
  ['remove_5fall_124',['remove_all',['../structEigen_1_1internal_1_1remove__all.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20const_20t_20_3e_125',['remove_all&lt; const T &gt;',['../structEigen_1_1internal_1_1remove__all_3_01const_01T_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20_26_20_3e_126',['remove_all&lt; T &amp; &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01_6_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20_2a_20_3e_127',['remove_all&lt; T * &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01_5_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20const_20_26_20_3e_128',['remove_all&lt; T const &amp; &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01const_01_6_01_4.html',1,'Eigen::internal']]],
  ['remove_5fall_3c_20t_20const_20_2a_20_3e_129',['remove_all&lt; T const * &gt;',['../structEigen_1_1internal_1_1remove__all_3_01T_01const_01_5_01_4.html',1,'Eigen::internal']]],
  ['remove_5fconst_130',['remove_const',['../structEigen_1_1internal_1_1remove__const.html',1,'Eigen::internal']]],
  ['remove_5fconst_3c_20const_20t_20_3e_131',['remove_const&lt; const T &gt;',['../structEigen_1_1internal_1_1remove__const_3_01const_01T_01_4.html',1,'Eigen::internal']]],
  ['remove_5fconst_3c_20const_20t_5b_5d_3e_132',['remove_const&lt; const T[]&gt;',['../structEigen_1_1internal_1_1remove__const_3_01const_01T_0f_0e_4.html',1,'Eigen::internal']]],
  ['remove_5fconst_3c_20const_20t_5bsize_5d_3e_133',['remove_const&lt; const T[Size]&gt;',['../structEigen_1_1internal_1_1remove__const_3_01const_01T_0fSize_0e_4.html',1,'Eigen::internal']]],
  ['remove_5fpointer_134',['remove_pointer',['../structEigen_1_1internal_1_1remove__pointer.html',1,'Eigen::internal']]],
  ['remove_5fpointer_3c_20t_20_2a_20_3e_135',['remove_pointer&lt; T * &gt;',['../structEigen_1_1internal_1_1remove__pointer_3_01T_01_5_01_4.html',1,'Eigen::internal']]],
  ['remove_5fpointer_3c_20t_20_2aconst_20_3e_136',['remove_pointer&lt; T *const &gt;',['../structEigen_1_1internal_1_1remove__pointer_3_01T_01_5const_01_4.html',1,'Eigen::internal']]],
  ['remove_5freference_137',['remove_reference',['../structEigen_1_1internal_1_1remove__reference.html',1,'Eigen::internal']]],
  ['remove_5freference_3c_20t_20_26_20_3e_138',['remove_reference&lt; T &amp; &gt;',['../structEigen_1_1internal_1_1remove__reference_3_01T_01_6_01_4.html',1,'Eigen::internal']]],
  ['remove_5fstats_139',['remove_stats',['../classremove__stats.html',1,'']]],
  ['repaggregatesignal_140',['RepAggregateSignal',['../classRepAggregateSignal.html',1,'']]],
  ['repaggregationperiod_141',['RepAggregationPeriod',['../classRepAggregationPeriod.html',1,'']]],
  ['repbasicoutliercleaner_142',['RepBasicOutlierCleaner',['../classRepBasicOutlierCleaner.html',1,'']]],
  ['repbasicrangecleaner_143',['RepBasicRangeCleaner',['../classRepBasicRangeCleaner.html',1,'']]],
  ['repcalcsimplesignals_144',['RepCalcSimpleSignals',['../classRepCalcSimpleSignals.html',1,'']]],
  ['repcategorydescenders_145',['RepCategoryDescenders',['../classRepCategoryDescenders.html',1,'']]],
  ['repcheckreq_146',['RepCheckReq',['../classRepCheckReq.html',1,'']]],
  ['repclearsignalbydiag_147',['RepClearSignalByDiag',['../classRepClearSignalByDiag.html',1,'']]],
  ['repcombinesignals_148',['RepCombineSignals',['../classRepCombineSignals.html',1,'']]],
  ['repconfiguredoutliercleaner_149',['RepConfiguredOutlierCleaner',['../classRepConfiguredOutlierCleaner.html',1,'']]],
  ['repcreatebitsignal_150',['RepCreateBitSignal',['../classRepCreateBitSignal.html',1,'']]],
  ['repcreateregistry_151',['RepCreateRegistry',['../classRepCreateRegistry.html',1,'']]],
  ['repfilterbychannel_152',['RepFilterByChannel',['../classRepFilterByChannel.html',1,'']]],
  ['rephistorylimit_153',['RepHistoryLimit',['../classRepHistoryLimit.html',1,'']]],
  ['replicate_154',['Replicate',['../classEigen_1_1Replicate.html',1,'Eigen']]],
  ['repmultiprocessor_155',['RepMultiProcessor',['../classRepMultiProcessor.html',1,'']]],
  ['repnbrsoutliercleaner_156',['RepNbrsOutlierCleaner',['../classRepNbrsOutlierCleaner.html',1,'']]],
  ['repnumericnoiser_157',['RepNumericNoiser',['../classRepNumericNoiser.html',1,'']]],
  ['repositoryhandle_158',['RepositoryHandle',['../classRepositoryHandle.html',1,'']]],
  ['reppanelcompleter_159',['RepPanelCompleter',['../classRepPanelCompleter.html',1,'']]],
  ['repprocessor_160',['RepProcessor',['../classRepProcessor.html',1,'']]],
  ['repreoderchannels_161',['RepReoderChannels',['../classRepReoderChannels.html',1,'']]],
  ['reprulebasedoutliercleaner_162',['RepRuleBasedOutlierCleaner',['../classRepRuleBasedOutlierCleaner.html',1,'']]],
  ['repsignalrate_163',['RepSignalRate',['../classRepSignalRate.html',1,'']]],
  ['repsimvalhandler_164',['RepSimValHandler',['../classRepSimValHandler.html',1,'']]],
  ['repsplitsignal_165',['RepSplitSignal',['../classRepSplitSignal.html',1,'']]],
  ['requiredsignalfilter_166',['RequiredSignalFilter',['../classRequiredSignalFilter.html',1,'']]],
  ['resamplemissingprocessor_167',['ResampleMissingProcessor',['../classResampleMissingProcessor.html',1,'']]],
  ['resourcehandler_168',['ResourceHandler',['../classxgboost_1_1common_1_1ResourceHandler.html',1,'xgboost::common']]],
  ['result_5fof_169',['result_of',['../structEigen_1_1internal_1_1result__of.html',1,'Eigen::internal']]],
  ['result_5fof_3c_20func_28argtype_29_3e_170',['result_of&lt; Func(ArgType)&gt;',['../structEigen_1_1internal_1_1result__of_3_01Func_07ArgType_08_4.html',1,'Eigen::internal']]],
  ['result_5fof_3c_20func_28argtype0_2c_20argtype1_29_3e_171',['result_of&lt; Func(ArgType0, ArgType1)&gt;',['../structEigen_1_1internal_1_1result__of_3_01Func_07ArgType0_00_01ArgType1_08_4.html',1,'Eigen::internal']]],
  ['result_5fof_3c_20scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_20_3e_28scalar_2c_20scalar_29_3e_172',['result_of&lt; scalar_cmp_op&lt; Scalar, Cmp &gt;(Scalar, Scalar)&gt;',['../structEigen_1_1internal_1_1result__of_3_01scalar__cmp__op_3_01Scalar_00_01Cmp_01_4_07Scalar_00_01Scalar_08_4.html',1,'Eigen::internal']]],
  ['returnbyvalue_173',['ReturnByValue',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20fullpivhouseholderqrmatrixqreturntype_3c_20matrixtype_20_3e_20_3e_174',['ReturnByValue&lt; FullPivHouseholderQRMatrixQReturnType&lt; MatrixType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20hessenbergdecompositionmatrixhreturntype_3c_20matrixtype_20_3e_20_3e_175',['ReturnByValue&lt; HessenbergDecompositionMatrixHReturnType&lt; MatrixType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20homogeneous_5fleft_5fproduct_5fimpl_3c_20homogeneous_3c_20matrixtype_2c_20vertical_20_3e_2c_20lhs_20_3e_20_3e_176',['ReturnByValue&lt; homogeneous_left_product_impl&lt; Homogeneous&lt; MatrixType, Vertical &gt;, Lhs &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20homogeneous_5fright_5fproduct_5fimpl_3c_20homogeneous_3c_20matrixtype_2c_20horizontal_20_3e_2c_20rhs_20_3e_20_3e_177',['ReturnByValue&lt; homogeneous_right_product_impl&lt; Homogeneous&lt; MatrixType, Horizontal &gt;, Rhs &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20image_5fretval_5fbase_3c_20_5fdecompositiontype_20_3e_20_3e_178',['ReturnByValue&lt; image_retval_base&lt; _DecompositionType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20image_5fretval_5fbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e_20_3e_179',['ReturnByValue&lt; image_retval_base&lt; FullPivLU&lt; _MatrixType &gt; &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20kernel_5fretval_5fbase_3c_20_5fdecompositiontype_20_3e_20_3e_180',['ReturnByValue&lt; kernel_retval_base&lt; _DecompositionType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20kernel_5fretval_5fbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e_20_3e_181',['ReturnByValue&lt; kernel_retval_base&lt; FullPivLU&lt; _MatrixType &gt; &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20sparseqr_5fqproduct_3c_20sparseqrtype_2c_20derived_20_3e_20_3e_182',['ReturnByValue&lt; SparseQR_QProduct&lt; SparseQRType, Derived &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20spqr_5fqproduct_3c_20spqrtype_2c_20derived_20_3e_20_3e_183',['ReturnByValue&lt; SPQR_QProduct&lt; SPQRType, Derived &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20triangular_5fsolve_5fretval_3c_20side_2c_20triangulartype_2c_20rhs_20_3e_20_3e_184',['ReturnByValue&lt; triangular_solve_retval&lt; Side, TriangularType, Rhs &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returnbyvalue_3c_20tridiagonalizationmatrixtreturntype_3c_20matrixtype_20_3e_20_3e_185',['ReturnByValue&lt; TridiagonalizationMatrixTReturnType&lt; MatrixType &gt; &gt;',['../classEigen_1_1ReturnByValue.html',1,'Eigen']]],
  ['returntype_186',['returntype',['../structEigen_1_1VectorwiseOp_1_1ReturnType.html',1,'Eigen::VectorwiseOp&lt; ExpressionType, Direction &gt;::ReturnType&lt; Functor, Scalar_ &gt;'],['../structrabit_1_1engine_1_1AllreduceBase_1_1ReturnType.html',1,'rabit::engine::AllreduceBase::ReturnType']]],
  ['reverse_187',['Reverse',['../classEigen_1_1Reverse.html',1,'Eigen']]],
  ['reverse_5fpacket_5fcond_188',['reverse_packet_cond',['../structEigen_1_1internal_1_1reverse__packet__cond.html',1,'Eigen::internal']]],
  ['reverse_5fpacket_5fcond_3c_20packettype_2c_20false_20_3e_189',['reverse_packet_cond&lt; PacketType, false &gt;',['../structEigen_1_1internal_1_1reverse__packet__cond_3_01PacketType_00_01false_01_4.html',1,'Eigen::internal']]],
  ['reverseinneriterator_190',['reverseinneriterator',['../classEigen_1_1internal_1_1unary__evaluator_3_01Transpose_3_01ArgType_01_4_00_01IteratorBased_01_4_1_1ReverseInnerIterator.html',1,'Eigen::internal::unary_evaluator&lt; Transpose&lt; ArgType &gt;, IteratorBased &gt;::ReverseInnerIterator'],['../classEigen_1_1SparseCompressedBase_1_1ReverseInnerIterator.html',1,'Eigen::SparseCompressedBase&lt; Derived &gt;::ReverseInnerIterator'],['../classEigen_1_1TriangularViewImpl_3_01MatrixType_00_01Mode_00_01Sparse_01_4_1_1ReverseInnerIterator.html',1,'Eigen::TriangularViewImpl&lt; MatrixType, Mode, Sparse &gt;::ReverseInnerIterator']]],
  ['rf_191',['RF',['../classLightGBM_1_1RF.html',1,'LightGBM']]],
  ['rmmallocator_192',['RMMAllocator',['../classxgboost_1_1RMMAllocator.html',1,'xgboost']]],
  ['rmsemetric_193',['RMSEMetric',['../classLightGBM_1_1RMSEMetric.html',1,'LightGBM']]],
  ['roc_5fand_5ffilter_5fparams_194',['ROC_And_Filter_Params',['../structROC__And__Filter__Params.html',1,'']]],
  ['roc_5fparams_195',['ROC_Params',['../classROC__Params.html',1,'']]],
  ['rotation2d_196',['Rotation2D',['../classEigen_1_1Rotation2D.html',1,'Eigen']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_197',['rotation_base_generic_product_selector',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector.html',1,'Eigen::internal']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_3c_20rotationderived_2c_20diagonalmatrix_3c_20scalar_2c_20dim_2c_20maxdim_20_3e_2c_20false_20_3e_198',['rotation_base_generic_product_selector&lt; RotationDerived, DiagonalMatrix&lt; Scalar, Dim, MaxDim &gt;, false &gt;',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector_3_01RotationDerived_00_01Dce6ab4d4618a8a7d711ee4fd66ebeba4.html',1,'Eigen::internal']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_3c_20rotationderived_2c_20matrixtype_2c_20false_20_3e_199',['rotation_base_generic_product_selector&lt; RotationDerived, MatrixType, false &gt;',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector_3_01RotationDerived_00_01MatrixType_00_01false_01_4.html',1,'Eigen::internal']]],
  ['rotation_5fbase_5fgeneric_5fproduct_5fselector_3c_20rotationderived_2c_20othervectortype_2c_20true_20_3e_200',['rotation_base_generic_product_selector&lt; RotationDerived, OtherVectorType, true &gt;',['../structEigen_1_1internal_1_1rotation__base__generic__product__selector_3_01RotationDerived_00_01OtherVectorType_00_01true_01_4.html',1,'Eigen::internal']]],
  ['rotationbase_201',['RotationBase',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20angleaxis_3c_20_5fscalar_20_3e_2c_203_20_3e_202',['RotationBase&lt; AngleAxis&lt; _Scalar &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20derived_2c_203_20_3e_203',['RotationBase&lt; Derived, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20map_3c_20const_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_2c_203_20_3e_204',['RotationBase&lt; Map&lt; const Quaternion&lt; _Scalar &gt;, _Options &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20map_3c_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_2c_203_20_3e_205',['RotationBase&lt; Map&lt; Quaternion&lt; _Scalar &gt;, _Options &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20quaternion_3c_20_5fscalar_2c_20_5foptions_20_3e_2c_203_20_3e_206',['RotationBase&lt; Quaternion&lt; _Scalar, _Options &gt;, 3 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20rotation2d_3c_20_5fscalar_20_3e_2c_202_20_3e_207',['RotationBase&lt; Rotation2D&lt; _Scalar &gt;, 2 &gt;',['../classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['round_5fimpl_208',['round_impl',['../structEigen_1_1internal_1_1round__impl.html',1,'Eigen::internal']]],
  ['round_5fretval_209',['round_retval',['../structEigen_1_1internal_1_1round__retval.html',1,'Eigen::internal']]],
  ['row_210',['Row',['../classdmlc_1_1Row.html',1,'dmlc']]],
  ['rowblock_211',['RowBlock',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20indextype_2c_20real_5ft_20_3e_212',['RowBlock&lt; IndexType, real_t &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20uint32_5ft_20_3e_213',['RowBlock&lt; uint32_t &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20uint32_5ft_2c_20float_20_3e_214',['RowBlock&lt; uint32_t, float &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblockcontainer_215',['RowBlockContainer',['../structdmlc_1_1data_1_1RowBlockContainer.html',1,'dmlc::data']]],
  ['rowblockcontainer_3c_20indextype_2c_20real_5ft_20_3e_216',['RowBlockContainer&lt; IndexType, real_t &gt;',['../structdmlc_1_1data_1_1RowBlockContainer.html',1,'dmlc::data']]],
  ['rowblockiter_217',['RowBlockIter',['../classdmlc_1_1RowBlockIter.html',1,'dmlc']]],
  ['rowblockiter_3c_20indextype_2c_20real_5ft_20_3e_218',['RowBlockIter&lt; IndexType, real_t &gt;',['../classdmlc_1_1RowBlockIter.html',1,'dmlc']]],
  ['rowsetcollection_219',['RowSetCollection',['../classxgboost_1_1common_1_1RowSetCollection.html',1,'xgboost::common']]],
  ['rtreenodestat_220',['RTreeNodeStat',['../structxgboost_1_1RTreeNodeStat.html',1,'xgboost']]],
  ['runtimeflags_221',['RuntimeFlags',['../structxgboost_1_1common_1_1RuntimeFlags.html',1,'xgboost::common']]],
  ['ryupowlogutils_222',['RyuPowLogUtils',['../structxgboost_1_1detail_1_1RyuPowLogUtils.html',1,'xgboost::detail']]],
  ['ryuprinter_223',['RyuPrinter',['../classxgboost_1_1detail_1_1RyuPrinter.html',1,'xgboost::detail']]]
];
