var searchData=
[
  ['v_5farray_0',['v_array',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20act_5fscore_20_3e_1',['v_array&lt; act_score &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20action_20_3e_2',['v_array&lt; action &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20action_5fscore_20_3e_3',['v_array&lt; action_score &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20action_5fscore_3a_3aaction_5fscore_20_3e_4',['v_array&lt; ACTION_SCORE::action_score &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20audit_5fstrings_5fptr_20_3e_5',['v_array&lt; audit_strings_ptr &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20beam_3a_3abeam_5felement_3c_20t_20_3e_20_3e_6',['v_array&lt; Beam::beam_element&lt; T &gt; &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20bool_20_3e_7',['v_array&lt; bool &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20branch_20_3e_8',['v_array&lt; branch &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20cb_3a_3acb_5fclass_20_3e_9',['v_array&lt; CB::cb_class &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20cb_3a_3alabel_20_3e_10',['v_array&lt; CB::label &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20char_20_3e_11',['v_array&lt; char &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20cost_5fsensitive_3a_3alabel_20_3e_12',['v_array&lt; COST_SENSITIVE::label &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20cost_5fsensitive_3a_3awclass_20_3e_13',['v_array&lt; COST_SENSITIVE::wclass &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20direction_20_3e_14',['v_array&lt; direction &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20example_20_2a_20_3e_15',['v_array&lt; example * &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20example_20_3e_16',['v_array&lt; example &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20feature_20_3e_17',['v_array&lt; feature &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20feature_5findex_20_3e_18',['v_array&lt; feature_index &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20feature_5fvalue_20_3e_19',['v_array&lt; feature_value &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20float_20_3e_20',['v_array&lt; float &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20int_20_3e_21',['v_array&lt; int &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20int32_5ft_20_3e_22',['v_array&lt; int32_t &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20learner_3a_3alearner_20_2a_28_2a_29_28vw_20_26_29_3e_23',['v_array&lt; LEARNER::learner *(*)(vw &amp;)&gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20lq_5fdata_20_3e_24',['v_array&lt; lq_data &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20mwt_3a_3apolicy_5fdata_20_3e_25',['v_array&lt; MWT::policy_data &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20namespace_3c_20audit_20_3e_20_3e_26',['v_array&lt; Namespace&lt; audit &gt; &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20namespace_5findex_20_3e_27',['v_array&lt; namespace_index &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20node_20_3e_28',['v_array&lt; node &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20node_5fpred_20_3e_29',['v_array&lt; node_pred &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20pair_3c_20action_2c_20float_20_3e_20_3e_30',['v_array&lt; pair&lt; action, float &gt; &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20pair_3c_20branch_2c_20string_20_2a_20_3e_20_3e_31',['v_array&lt; pair&lt; branch, string * &gt; &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20pair_3c_20float_2c_20size_5ft_20_3e_20_3e_32',['v_array&lt; pair&lt; float, size_t &gt; &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20ptag_20_3e_33',['v_array&lt; ptag &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20recall_5ftree_5fns_3a_3anode_20_3e_34',['v_array&lt; recall_tree_ns::node &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20recall_5ftree_5fns_3a_3anode_5fpred_20_3e_35',['v_array&lt; recall_tree_ns::node_pred &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20search_3a_3aaction_5frepr_20_3e_36',['v_array&lt; Search::action_repr &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20search_3a_3ascored_5faction_20_3e_37',['v_array&lt; Search::scored_action &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20size_5ft_20_3e_38',['v_array&lt; size_t &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20substring_20_3e_39',['v_array&lt; substring &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20svm_5fexample_20_2a_20_3e_40',['v_array&lt; svm_example * &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20uint32_5ft_20_3e_41',['v_array&lt; uint32_t &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20uint64_5ft_20_3e_42',['v_array&lt; uint64_t &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20unsigned_20char_20_3e_43',['v_array&lt; unsigned char &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20v_5farray_20_3e_44',['v_array&lt; v_array &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20v_5farray_3c_20pair_3c_20cost_5fsensitive_3a_3awclass_20_26_2c_20bool_20_3e_20_3e_20_3e_45',['v_array&lt; v_array&lt; pair&lt; COST_SENSITIVE::wclass &amp;, bool &gt; &gt; &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20v_5farray_3c_20search_3a_3aaction_5fcache_20_3e_20_2a_20_3e_46',['v_array&lt; v_array&lt; Search::action_cache &gt; * &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20v_5farray_3c_20v_5farray_3c_20uint32_5ft_20_3e_20_3e_20_3e_47',['v_array&lt; v_array&lt; v_array&lt; uint32_t &gt; &gt; &gt;',['../structv__array.html',1,'']]],
  ['v_5farray_3c_20v_5fhashmap_3a_3ahash_5felem_20_3e_48',['v_array&lt; v_hashmap::hash_elem &gt;',['../structv__array.html',1,'']]],
  ['v_5fhashmap_49',['v_hashmap',['../classv__hashmap.html',1,'']]],
  ['v_5fhashmap_3c_20size_5ft_2c_20features_20_3e_50',['v_hashmap&lt; size_t, features &gt;',['../classv__hashmap.html',1,'']]],
  ['v_5fhashmap_3c_20substring_2c_20uint64_5ft_20_3e_51',['v_hashmap&lt; substring, uint64_t &gt;',['../classv__hashmap.html',1,'']]],
  ['v_5fhashmap_3c_20unsigned_20char_20_2a_2c_20search_3a_3ascored_5faction_20_3e_52',['v_hashmap&lt; unsigned char *, Search::scored_action &gt;',['../classv__hashmap.html',1,'']]],
  ['val_5fidx_53',['val_idx',['../structval__idx.html',1,'']]],
  ['valind_54',['ValInd',['../structValInd.html',1,'']]],
  ['value_55',['value',['../classxgboost_1_1Value.html',1,'xgboost::Value'],['../classjson11_1_1Value.html',1,'json11::Value&lt; tag, T &gt;']]],
  ['value_3c_20json_3a_3aarray_2c_20json_3a_3aarray_20_3e_56',['Value&lt; Json::ARRAY, Json::array &gt;',['../classjson11_1_1Value.html',1,'json11']]],
  ['value_3c_20json_3a_3abool_2c_20bool_20_3e_57',['Value&lt; Json::BOOL, bool &gt;',['../classjson11_1_1Value.html',1,'json11']]],
  ['value_3c_20json_3a_3anul_2c_20nullstruct_20_3e_58',['Value&lt; Json::NUL, NullStruct &gt;',['../classjson11_1_1Value.html',1,'json11']]],
  ['value_3c_20json_3a_3anumber_2c_20double_20_3e_59',['Value&lt; Json::NUMBER, double &gt;',['../classjson11_1_1Value.html',1,'json11']]],
  ['value_3c_20json_3a_3anumber_2c_20int_20_3e_60',['Value&lt; Json::NUMBER, int &gt;',['../classjson11_1_1Value.html',1,'json11']]],
  ['value_3c_20json_3a_3aobject_2c_20json_3a_3aobject_20_3e_61',['Value&lt; Json::OBJECT, Json::object &gt;',['../classjson11_1_1Value.html',1,'json11']]],
  ['value_3c_20json_3a_3astring_2c_20string_20_3e_62',['Value&lt; Json::STRING, string &gt;',['../classjson11_1_1Value.html',1,'json11']]],
  ['value_5fin_5frange_5fof_5fimpl1_63',['value_in_range_of_impl1',['../structdetail_1_1value__in__range__of__impl1.html',1,'detail']]],
  ['value_5fin_5frange_5fof_5fimpl1_3c_20oftype_2c_20t_2c_20false_20_3e_64',['value_in_range_of_impl1&lt; OfType, T, false &gt;',['../structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01false_01_4.html',1,'detail']]],
  ['value_5fin_5frange_5fof_5fimpl1_3c_20oftype_2c_20t_2c_20true_20_3e_65',['value_in_range_of_impl1&lt; OfType, T, true &gt;',['../structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01true_01_4.html',1,'detail']]],
  ['value_5fin_5frange_5fof_5fimpl2_66',['value_in_range_of_impl2',['../structdetail_1_1value__in__range__of__impl2.html',1,'detail']]],
  ['value_5fin_5frange_5fof_5fimpl2_3c_20oftype_2c_20t_2c_20false_2c_20false_20_3e_67',['value_in_range_of_impl2&lt; OfType, T, false, false &gt;',['../structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01false_01_4.html',1,'detail']]],
  ['value_5fin_5frange_5fof_5fimpl2_3c_20oftype_2c_20t_2c_20false_2c_20true_20_3e_68',['value_in_range_of_impl2&lt; OfType, T, false, true &gt;',['../structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01true_01_4.html',1,'detail']]],
  ['value_5fin_5frange_5fof_5fimpl2_3c_20oftype_2c_20t_2c_20true_2c_20false_20_3e_69',['value_in_range_of_impl2&lt; OfType, T, true, false &gt;',['../structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01false_01_4.html',1,'detail']]],
  ['value_5fin_5frange_5fof_5fimpl2_3c_20oftype_2c_20t_2c_20true_2c_20true_20_3e_70',['value_in_range_of_impl2&lt; OfType, T, true, true &gt;',['../structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01true_01_4.html',1,'detail']]],
  ['valuecleanerparams_71',['ValueCleanerParams',['../classValueCleanerParams.html',1,'']]],
  ['valueintcomparer_72',['ValueIntComparer',['../structValueIntComparer.html',1,'']]],
  ['valuenewstat4ctx_73',['ValueNewStat4Ctx',['../structValueNewStat4Ctx.html',1,'']]],
  ['variable_5fif_5fdynamic_74',['variable_if_dynamic',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5frows_20_3e_75',['variable_if_dynamic&lt; Index, _Rows &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5fsubs_20_3e_76',['variable_if_dynamic&lt; Index, _Subs &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5fsupers_20_3e_77',['variable_if_dynamic&lt; Index, _Supers &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3acolsatcompiletime_20_3e_78',['variable_if_dynamic&lt; Index, ArgType::ColsAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3acolsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_79',['variable_if_dynamic&lt; Index, ArgType::ColsAtCompileTime==1 ? 0 :Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3arowsatcompiletime_20_3e_80',['variable_if_dynamic&lt; Index, ArgType::RowsAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3arowsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_81',['variable_if_dynamic&lt; Index, ArgType::RowsAtCompileTime==1 ? 0 :Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20colfactor_20_3e_82',['variable_if_dynamic&lt; Index, ColFactor &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20colsatcompiletime_20_3e_83',['variable_if_dynamic&lt; Index, ColsAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20derived_3a_3aisvectoratcompiletime_3f0_3adynamic_20_3e_84',['variable_if_dynamic&lt; Index, Derived::IsVectorAtCompileTime?0:Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20innerstrideatcompiletime_20_3e_85',['variable_if_dynamic&lt; Index, InnerStrideAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20isvectoratcompiletime_20_3f_200_20_3aint_28isrowmajor_29_20_3f_20colsatcompiletime_20_3arowsatcompiletime_20_3e_86',['variable_if_dynamic&lt; Index, IsVectorAtCompileTime ? 0 :int(IsRowMajor) ? ColsAtCompileTime :RowsAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20outersize_20_3e_87',['variable_if_dynamic&lt; Index, OuterSize &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20outerstrideatcompiletime_20_3e_88',['variable_if_dynamic&lt; Index, OuterStrideAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20reversecol_20_3f_20argtype_3a_3acolsatcompiletime_20_3a1_20_3e_89',['variable_if_dynamic&lt; Index, ReverseCol ? ArgType::ColsAtCompileTime :1 &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20reverserow_20_3f_20argtype_3a_3arowsatcompiletime_20_3a1_20_3e_90',['variable_if_dynamic&lt; Index, ReverseRow ? ArgType::RowsAtCompileTime :1 &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rowfactor_20_3e_91',['variable_if_dynamic&lt; Index, RowFactor &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rows_20_3e_92',['variable_if_dynamic&lt; Index, Rows &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rowsatcompiletime_20_3e_93',['variable_if_dynamic&lt; Index, RowsAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20subs_20_3e_94',['variable_if_dynamic&lt; Index, Subs &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20supers_20_3e_95',['variable_if_dynamic&lt; Index, Supers &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3acolsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_96',['variable_if_dynamic&lt; Index, XprType::ColsAtCompileTime==1 ? 0 :Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3arowsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_97',['variable_if_dynamic&lt; Index, XprType::RowsAtCompileTime==1 ? 0 :Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20colsatcompiletime_20_3e_98',['variable_if_dynamic&lt; StorageIndex, ColsAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20rowsatcompiletime_20_3e_99',['variable_if_dynamic&lt; StorageIndex, RowsAtCompileTime &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20xprtype_3a_3acolsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_100',['variable_if_dynamic&lt; StorageIndex, XprType::ColsAtCompileTime==1 ? 0 :Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20xprtype_3a_3arowsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_101',['variable_if_dynamic&lt; StorageIndex, XprType::RowsAtCompileTime==1 ? 0 :Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20t_2c_20dynamic_20_3e_102',['variable_if_dynamic&lt; T, Dynamic &gt;',['../classEigen_1_1internal_1_1variable__if__dynamic_3_01T_00_01Dynamic_01_4.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_103',['variable_if_dynamicindex',['../classEigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20index_2c_20diagindex_20_3e_104',['variable_if_dynamicindex&lt; Index, DiagIndex &gt;',['../classEigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20index_2c_20xprtype_3a_3adiagindex_20_3e_105',['variable_if_dynamicindex&lt; Index, XprType::DiagIndex &gt;',['../classEigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20t_2c_20dynamicindex_20_3e_106',['variable_if_dynamicindex&lt; T, DynamicIndex &gt;',['../classEigen_1_1internal_1_1variable__if__dynamicindex_3_01T_00_01DynamicIndex_01_4.html',1,'Eigen::internal']]],
  ['vdbe_107',['Vdbe',['../structVdbe.html',1,'']]],
  ['vdbecursor_108',['VdbeCursor',['../structVdbeCursor.html',1,'']]],
  ['vdbeframe_109',['VdbeFrame',['../structVdbeFrame.html',1,'']]],
  ['vdbeop_110',['VdbeOp',['../structVdbeOp.html',1,'']]],
  ['vdbeoplist_111',['VdbeOpList',['../structVdbeOpList.html',1,'']]],
  ['vdbesorter_112',['VdbeSorter',['../structVdbeSorter.html',1,'']]],
  ['vecmoments_113',['VecMoments',['../classVecMoments.html',1,'']]],
  ['vector_3c_20t_2c_20eigen_5faligned_5fallocator_3c_20t_20_3e_20_3e_114',['vector&lt; T, EIGEN_ALIGNED_ALLOCATOR&lt; T &gt; &gt;',['../classstd_1_1vector_3_01T_00_01EIGEN__ALIGNED__ALLOCATOR_3_01T_01_4_01_4.html',1,'std']]],
  ['vector_5fser_115',['VECTOR_SER',['../structVECTOR__SER.html',1,'']]],
  ['vectorblock_116',['VectorBlock',['../classEigen_1_1VectorBlock.html',1,'Eigen']]],
  ['vectorwise_5freverse_5finplace_5fimpl_117',['vectorwise_reverse_inplace_impl',['../structEigen_1_1internal_1_1vectorwise__reverse__inplace__impl.html',1,'Eigen::internal']]],
  ['vectorwise_5freverse_5finplace_5fimpl_3c_20horizontal_20_3e_118',['vectorwise_reverse_inplace_impl&lt; Horizontal &gt;',['../structEigen_1_1internal_1_1vectorwise__reverse__inplace__impl_3_01Horizontal_01_4.html',1,'Eigen::internal']]],
  ['vectorwise_5freverse_5finplace_5fimpl_3c_20vertical_20_3e_119',['vectorwise_reverse_inplace_impl&lt; Vertical &gt;',['../structEigen_1_1internal_1_1vectorwise__reverse__inplace__impl_3_01Vertical_01_4.html',1,'Eigen::internal']]],
  ['vectorwiseop_120',['VectorwiseOp',['../classEigen_1_1VectorwiseOp.html',1,'Eigen']]],
  ['version_121',['Version',['../structxgboost_1_1Version.html',1,'xgboost']]],
  ['version_5fstruct_122',['version_struct',['../structversion__struct.html',1,'']]],
  ['versioniterator_123',['versionIterator',['../classversionIterator.html',1,'']]],
  ['virtualfilereader_124',['VirtualFileReader',['../structLightGBM_1_1VirtualFileReader.html',1,'LightGBM']]],
  ['virtualfilewriter_125',['VirtualFileWriter',['../structLightGBM_1_1VirtualFileWriter.html',1,'LightGBM']]],
  ['visitor_5fevaluator_126',['visitor_evaluator',['../classEigen_1_1internal_1_1visitor__evaluator.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_127',['visitor_impl',['../structEigen_1_1internal_1_1visitor__impl.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_3c_20visitor_2c_20derived_2c_201_20_3e_128',['visitor_impl&lt; Visitor, Derived, 1 &gt;',['../structEigen_1_1internal_1_1visitor__impl_3_01Visitor_00_01Derived_00_011_01_4.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_3c_20visitor_2c_20derived_2c_20dynamic_20_3e_129',['visitor_impl&lt; Visitor, Derived, Dynamic &gt;',['../structEigen_1_1internal_1_1visitor__impl_3_01Visitor_00_01Derived_00_01Dynamic_01_4.html',1,'Eigen::internal']]],
  ['visualleakdetector_130',['VisualLeakDetector',['../classVLD_1_1VisualLeakDetector.html',1,'VLD']]],
  ['vml_5fassign_5ftraits_131',['vml_assign_traits',['../classEigen_1_1internal_1_1vml__assign__traits.html',1,'Eigen::internal']]],
  ['votingparalleltreelearner_132',['VotingParallelTreeLearner',['../classLightGBM_1_1VotingParallelTreeLearner.html',1,'LightGBM']]],
  ['vowpalwabbit_133',['VowpalWabbit',['../classVW_1_1VowpalWabbit.html',1,'VW']]],
  ['vowpalwabbit_3c_20texample_20_3e_134',['VowpalWabbit&lt; TExample &gt;',['../classVW_1_1VowpalWabbit.html',1,'VW']]],
  ['vowpalwabbit_3c_20vw_3a_3avowpalwabbitmultiworldtesting_3a_3alearnedvsconstantpolicy_20_3e_135',['VowpalWabbit&lt; VW::VowpalWabbitMultiworldTesting::LearnedVsConstantPolicy &gt;',['../classVW_1_1VowpalWabbit.html',1,'VW']]],
  ['vowpalwabbitargumentdisagreementexception_136',['VowpalWabbitArgumentDisagreementException',['../classVW_1_1VowpalWabbitArgumentDisagreementException.html',1,'VW']]],
  ['vowpalwabbitarguments_137',['VowpalWabbitArguments',['../classVW_1_1VowpalWabbitArguments.html',1,'VW']]],
  ['vowpalwabbitasync_138',['VowpalWabbitAsync',['../classVW_1_1VowpalWabbitAsync.html',1,'VW']]],
  ['vowpalwabbitdecisionserviceinteractionheader_139',['VowpalWabbitDecisionServiceInteractionHeader',['../classVW_1_1VowpalWabbitDecisionServiceInteractionHeader.html',1,'VW']]],
  ['vowpalwabbitdefaultmarshaller_140',['VowpalWabbitDefaultMarshaller',['../classVW_1_1Serializer_1_1VowpalWabbitDefaultMarshaller.html',1,'VW::Serializer']]],
  ['vowpalwabbitdynamic_141',['VowpalWabbitDynamic',['../classVW_1_1VowpalWabbitDynamic.html',1,'VW']]],
  ['vowpalwabbitexample_142',['VowpalWabbitExample',['../classVW_1_1VowpalWabbitExample.html',1,'VW']]],
  ['vowpalwabbitexamplecollection_143',['VowpalWabbitExampleCollection',['../classVW_1_1VowpalWabbitExampleCollection.html',1,'VW']]],
  ['vowpalwabbitexception_144',['VowpalWabbitException',['../classVW_1_1VowpalWabbitException.html',1,'VW']]],
  ['vowpalwabbitfeature_145',['VowpalWabbitFeature',['../structVW_1_1VowpalWabbitFeature.html',1,'VW']]],
  ['vowpalwabbitinterface_146',['VowpalWabbitInterface',['../classVW_1_1VowpalWabbitInterface.html',1,'VW']]],
  ['vowpalwabbitjson_147',['VowpalWabbitJson',['../classVW_1_1VowpalWabbitJson.html',1,'VW']]],
  ['vowpalwabbitjsonbuilder_148',['VowpalWabbitJsonBuilder',['../classVW_1_1Serializer_1_1VowpalWabbitJsonBuilder.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonexception_149',['VowpalWabbitJsonException',['../classVW_1_1Serializer_1_1VowpalWabbitJsonException.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonoptimizedserializable_150',['VowpalWabbitJsonOptimizedSerializable',['../classVW_1_1Serializer_1_1VowpalWabbitJsonOptimizedSerializable.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonparsecontext_151',['VowpalWabbitJsonParseContext',['../classVW_1_1Serializer_1_1VowpalWabbitJsonParseContext.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonparsestate_152',['VowpalWabbitJsonParseState',['../classVW_1_1Serializer_1_1VowpalWabbitJsonParseState.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonreferenceresolver_153',['VowpalWabbitJsonReferenceResolver',['../classVW_1_1Serializer_1_1VowpalWabbitJsonReferenceResolver.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonserializable_154',['VowpalWabbitJsonSerializable',['../classVW_1_1Serializer_1_1VowpalWabbitJsonSerializable.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonserializer_155',['VowpalWabbitJsonSerializer',['../classVW_1_1Serializer_1_1VowpalWabbitJsonSerializer.html',1,'VW::Serializer']]],
  ['vowpalwabbitjsonthreadedprediction_156',['VowpalWabbitJsonThreadedPrediction',['../classVW_1_1VowpalWabbitJsonThreadedPrediction.html',1,'VW']]],
  ['vowpalwabbitlistenertoevents_157',['VowpalWabbitListenerToEvents',['../classcs__unittest_1_1VowpalWabbitListenerToEvents.html',1,'cs_unittest']]],
  ['vowpalwabbitlistenertoevents_3c_20data_20_3e_158',['VowpalWabbitListenerToEvents&lt; Data &gt;',['../classcs__unittest_1_1VowpalWabbitListenerToEvents.html',1,'cs_unittest']]],
  ['vowpalwabbitmarshalcontext_159',['VowpalWabbitMarshalContext',['../classVW_1_1Serializer_1_1VowpalWabbitMarshalContext.html',1,'VW::Serializer']]],
  ['vowpalwabbitmodel_160',['VowpalWabbitModel',['../classVW_1_1VowpalWabbitModel.html',1,'VW']]],
  ['vowpalwabbitmultilineexamplecollection_161',['VowpalWabbitMultiLineExampleCollection',['../classVW_1_1VowpalWabbitMultiLineExampleCollection.html',1,'VW']]],
  ['vowpalwabbitmultiworldtesting_162',['VowpalWabbitMultiworldTesting',['../classVW_1_1VowpalWabbitMultiworldTesting.html',1,'VW']]],
  ['vowpalwabbitnamespace_163',['VowpalWabbitNamespace',['../structVW_1_1VowpalWabbitNamespace.html',1,'VW']]],
  ['vowpalwabbitperformancestatistics_164',['VowpalWabbitPerformanceStatistics',['../classVW_1_1VowpalWabbitPerformanceStatistics.html',1,'VW']]],
  ['vowpalwabbitscalar_165',['VowpalWabbitScalar',['../structVW_1_1VowpalWabbitScalar.html',1,'VW']]],
  ['vowpalwabbitserializationexception_166',['VowpalWabbitSerializationException',['../classVW_1_1VowpalWabbitSerializationException.html',1,'VW']]],
  ['vowpalwabbitsettings_167',['VowpalWabbitSettings',['../classVW_1_1VowpalWabbitSettings.html',1,'VW']]],
  ['vowpalwabbitsingleexampleserializer_168',['VowpalWabbitSingleExampleSerializer',['../classVW_1_1Serializer_1_1VowpalWabbitSingleExampleSerializer.html',1,'VW::Serializer']]],
  ['vowpalwabbitsingleexampleserializer_3c_20tactiondependentfeature_20_3e_169',['VowpalWabbitSingleExampleSerializer&lt; TActionDependentFeature &gt;',['../classVW_1_1Serializer_1_1VowpalWabbitSingleExampleSerializer.html',1,'VW::Serializer']]],
  ['vowpalwabbitsingleexampleserializercompiler_170',['VowpalWabbitSingleExampleSerializerCompiler',['../classVW_1_1Serializer_1_1VowpalWabbitSingleExampleSerializerCompiler.html',1,'VW::Serializer']]],
  ['vowpalwabbitsingleexampleserializercompiler_3c_20tactiondependentfeature_20_3e_171',['VowpalWabbitSingleExampleSerializerCompiler&lt; TActionDependentFeature &gt;',['../classVW_1_1Serializer_1_1VowpalWabbitSingleExampleSerializerCompiler.html',1,'VW::Serializer']]],
  ['vowpalwabbitsinglelineexamplecollection_172',['VowpalWabbitSingleLineExampleCollection',['../classVW_1_1VowpalWabbitSingleLineExampleCollection.html',1,'VW']]],
  ['vowpalwabbitstderrperformancestatistics_173',['VowpalWabbitStdErrPerformanceStatistics',['../classcs__unittest_1_1VowpalWabbitStdErrPerformanceStatistics.html',1,'cs_unittest']]],
  ['vowpalwabbitsweep_174',['VowpalWabbitSweep',['../classVW_1_1VowpalWabbitSweep.html',1,'VW']]],
  ['vowpalwabbitthreadedlearning_175',['VowpalWabbitThreadedLearning',['../classVW_1_1VowpalWabbitThreadedLearning.html',1,'VW']]],
  ['vowpalwabbitthreadedprediction_176',['VowpalWabbitThreadedPrediction',['../classVW_1_1VowpalWabbitThreadedPrediction.html',1,'VW']]],
  ['vowpalwabbitthreadedpredictionbase_177',['VowpalWabbitThreadedPredictionBase',['../classVW_1_1VowpalWabbitThreadedPredictionBase.html',1,'VW']]],
  ['vowpalwabbitthreadedpredictionbase_3c_20vowpalwabbit_20_3e_178',['VowpalWabbitThreadedPredictionBase&lt; VowpalWabbit &gt;',['../classVW_1_1VowpalWabbitThreadedPredictionBase.html',1,'VW']]],
  ['vowpalwabbitthreadedpredictionbase_3c_20vowpalwabbit_3c_20texample_20_3e_20_3e_179',['VowpalWabbitThreadedPredictionBase&lt; VowpalWabbit&lt; TExample &gt; &gt;',['../classVW_1_1VowpalWabbitThreadedPredictionBase.html',1,'VW']]],
  ['vowpalwabbitthreadedpredictionbase_3c_20vowpalwabbit_3c_20texample_2c_20tactiondependentfeature_20_3e_20_3e_180',['VowpalWabbitThreadedPredictionBase&lt; VowpalWabbit&lt; TExample, TActionDependentFeature &gt; &gt;',['../classVW_1_1VowpalWabbitThreadedPredictionBase.html',1,'VW']]],
  ['vowpalwabbitthreadedpredictionbase_3c_20vowpalwabbitjson_20_3e_181',['VowpalWabbitThreadedPredictionBase&lt; VowpalWabbitJson &gt;',['../classVW_1_1VowpalWabbitThreadedPredictionBase.html',1,'VW']]],
  ['vtabctx_182',['VtabCtx',['../structVtabCtx.html',1,'']]],
  ['vtable_183',['VTable',['../structVTable.html',1,'']]],
  ['vw_184',['vw',['../classvowpalwabbit_1_1pyvw_1_1vw.html',1,'vowpalwabbit.pyvw.vw'],['../classvowpalwabbit_1_1sklearn__vw_1_1VW.html',1,'vowpalwabbit.sklearn_vw.VW'],['../classvowpalWabbit_1_1VW.html',1,'vowpalWabbit.VW'],['../structvw.html',1,'vw']]],
  ['vw_5fargument_5fdisagreement_5fexception_185',['vw_argument_disagreement_exception',['../classVW_1_1vw__argument__disagreement__exception.html',1,'VW']]],
  ['vw_5fexception_186',['vw_exception',['../classVW_1_1vw__exception.html',1,'VW']]],
  ['vw_5fnamespace_187',['vw_namespace',['../structvw__namespace.html',1,'']]],
  ['vw_5fostream_188',['vw_ostream',['../classvw__ostream.html',1,'']]],
  ['vw_5frecorder_189',['vw_recorder',['../structvw__recorder.html',1,'']]],
  ['vw_5fscorer_190',['vw_scorer',['../classvw__scorer.html',1,'']]],
  ['vwactionprobslearner_191',['VWActionProbsLearner',['../classvowpalWabbit_1_1learner_1_1VWActionProbsLearner.html',1,'vowpalWabbit::learner']]],
  ['vwactionprobslearnertest_192',['VWActionProbsLearnerTest',['../classvowpalWabbit_1_1learner_1_1VWActionProbsLearnerTest.html',1,'vowpalWabbit::learner']]],
  ['vwactionscoreslearner_193',['VWActionScoresLearner',['../classvowpalWabbit_1_1learner_1_1VWActionScoresLearner.html',1,'vowpalWabbit::learner']]],
  ['vwactionscoreslearnertest_194',['VWActionScoresLearnerTest',['../classvowpalWabbit_1_1learner_1_1VWActionScoresLearnerTest.html',1,'vowpalWabbit::learner']]],
  ['vwbuildext_195',['VWBuildExt',['../classsetup_1_1VWBuildExt.html',1,'setup']]],
  ['vwclassifier_196',['VWClassifier',['../classvowpalwabbit_1_1sklearn__vw_1_1VWClassifier.html',1,'vowpalwabbit::sklearn_vw']]],
  ['vwinstanceex_197',['VWInstanceEx',['../classcs__test_1_1Program_1_1VWInstanceEx.html',1,'cs_test::Program']]],
  ['vwlearner_198',['VWLearner',['../interfacevowpalWabbit_1_1learner_1_1VWLearner.html',1,'vowpalWabbit::learner']]],
  ['vwlearners_199',['VWLearners',['../classvowpalWabbit_1_1learner_1_1VWLearners.html',1,'vowpalWabbit::learner']]],
  ['vwlearnerstest_200',['VWLearnersTest',['../classvowpalWabbit_1_1learner_1_1VWLearnersTest.html',1,'vowpalWabbit::learner']]],
  ['vwmulticlasslearner_201',['VWMulticlassLearner',['../classvowpalWabbit_1_1learner_1_1VWMulticlassLearner.html',1,'vowpalWabbit::learner']]],
  ['vwmulticlasslearnertest_202',['VWMulticlassLearnerTest',['../classvowpalWabbit_1_1learner_1_1VWMulticlassLearnerTest.html',1,'vowpalWabbit::learner']]],
  ['vwmultilabelslearner_203',['VWMultilabelsLearner',['../classvowpalWabbit_1_1learner_1_1VWMultilabelsLearner.html',1,'vowpalWabbit::learner']]],
  ['vwmultilabelslearnertest_204',['VWMultilabelsLearnerTest',['../classvowpalWabbit_1_1learner_1_1VWMultilabelsLearnerTest.html',1,'vowpalWabbit::learner']]],
  ['vwproblearner_205',['VWProbLearner',['../classvowpalWabbit_1_1learner_1_1VWProbLearner.html',1,'vowpalWabbit::learner']]],
  ['vwproblearnertest_206',['VWProbLearnerTest',['../classvowpalWabbit_1_1learner_1_1VWProbLearnerTest.html',1,'vowpalWabbit::learner']]],
  ['vwreaderhandler_207',['VWReaderHandler',['../structVWReaderHandler.html',1,'']]],
  ['vwregressor_208',['VWRegressor',['../classvowpalwabbit_1_1sklearn__vw_1_1VWRegressor.html',1,'vowpalwabbit::sklearn_vw']]],
  ['vwscalarlearner_209',['VWScalarLearner',['../classvowpalWabbit_1_1learner_1_1VWScalarLearner.html',1,'vowpalWabbit::learner']]],
  ['vwscalarlearnertest_210',['VWScalarLearnerTest',['../classvowpalWabbit_1_1learner_1_1VWScalarLearnerTest.html',1,'vowpalWabbit::learner']]],
  ['vwscalarslearner_211',['VWScalarsLearner',['../classvowpalWabbit_1_1learner_1_1VWScalarsLearner.html',1,'vowpalWabbit::learner']]],
  ['vwscalarslearnertest_212',['VWScalarsLearnerTest',['../classvowpalWabbit_1_1learner_1_1VWScalarsLearnerTest.html',1,'vowpalWabbit::learner']]],
  ['vwtesthelper_213',['VWTestHelper',['../classvowpalWabbit_1_1VWTestHelper.html',1,'vowpalWabbit']]],
  ['vwtypedlearner_214',['VWTypedLearner',['../interfacevowpalWabbit_1_1learner_1_1VWTypedLearner.html',1,'vowpalWabbit::learner']]],
  ['vxworksfileid_215',['vxworksFileId',['../structvxworksFileId.html',1,'']]]
];
