var searchData=
[
  ['namecontext_0',['NameContext',['../structNameContext.html',1,'']]],
  ['namedlabels_1',['namedlabels',['../classnamedlabels.html',1,'']]],
  ['namespace_2',['namespace',['../classpredict__on__matrix_1_1Namespace.html',1,'predict_on_matrix.Namespace'],['../structNamespace.html',1,'Namespace&lt; audit &gt;'],['../classVW_1_1Serializer_1_1Intermediate_1_1Namespace.html',1,'VW.Serializer.Intermediate.Namespace']]],
  ['namespace1_3',['Namespace1',['../classcs__unittest_1_1Namespace1.html',1,'cs_unittest']]],
  ['namespace2_4',['Namespace2',['../classcs__unittest_1_1Namespace2.html',1,'cs_unittest']]],
  ['namespace_5fid_5',['namespace_id',['../classvowpalwabbit_1_1pyvw_1_1namespace__id.html',1,'vowpalwabbit::pyvw']]],
  ['naturalordering_6',['NaturalOrdering',['../classEigen_1_1NaturalOrdering.html',1,'Eigen']]],
  ['ncolsblockxpr_7',['NColsBlockXpr',['../structNColsBlockXpr.html',1,'']]],
  ['ndcgcache_8',['NDCGCache',['../classxgboost_1_1ltr_1_1NDCGCache.html',1,'xgboost::ltr']]],
  ['ndcgmetric_9',['NDCGMetric',['../classLightGBM_1_1NDCGMetric.html',1,'LightGBM']]],
  ['negation_10',['negation',['../structdetail_1_1negation.html',1,'detail']]],
  ['nestbyvalue_11',['NestByValue',['../classEigen_1_1NestByValue.html',1,'Eigen']]],
  ['nested_5feval_12',['nested_eval',['../structEigen_1_1internal_1_1nested__eval.html',1,'Eigen::internal']]],
  ['nested_5feval_3c_20diagcoefftype_2c_20sparsexprtype_3a_3aisrowmajor_3fsparsexprtype_3a_3arowsatcompiletime_3asparsexprtype_3a_3acolsatcompiletime_20_3e_13',['nested_eval&lt; DiagCoeffType, SparseXprType::IsRowMajor?SparseXprType::RowsAtCompileTime:SparseXprType::ColsAtCompileTime &gt;',['../structEigen_1_1internal_1_1nested__eval.html',1,'Eigen::internal']]],
  ['nested_5feval_3c_20returnbyvalue_3c_20derived_20_3e_2c_20n_2c_20plainobject_20_3e_14',['nested_eval&lt; ReturnByValue&lt; Derived &gt;, n, PlainObject &gt;',['../structEigen_1_1internal_1_1nested__eval_3_01ReturnByValue_3_01Derived_01_4_00_01n_00_01PlainObject_01_4.html',1,'Eigen::internal']]],
  ['neteval_15',['NetEval',['../classNetEval.html',1,'']]],
  ['netstruct_16',['netStruct',['../structnetStruct.html',1,'']]],
  ['network_17',['Network',['../classLightGBM_1_1Network.html',1,'LightGBM']]],
  ['neuronstruct_18',['neuronStruct',['../structneuronStruct.html',1,'']]],
  ['nextfile_19',['NextFile',['../classWikiExtractor_1_1NextFile.html',1,'WikiExtractor']]],
  ['nextstr_20',['nextstr',['../structnextstr.html',1,'']]],
  ['nips2015tutorial_21',['NIPS2015Tutorial',['../classcs__test_1_1NIPS2015Tutorial.html',1,'cs_test']]],
  ['nn_22',['nn',['../structnn.html',1,'']]],
  ['no_5fassignment_5foperator_23',['no_assignment_operator',['../classEigen_1_1internal_1_1no__assignment__operator.html',1,'Eigen::internal']]],
  ['noalias_24',['NoAlias',['../classEigen_1_1NoAlias.html',1,'Eigen']]],
  ['node_25',['node',['../structNode.html',1,'Node'],['../structnode.html',1,'node'],['../structrecall__tree__ns_1_1node.html',1,'recall_tree_ns::node'],['../classxgboost_1_1RegTree_1_1Node.html',1,'xgboost::RegTree::Node'],['../classjson__parser_1_1Node.html',1,'json_parser.Node']]],
  ['node_5fpred_26',['node_pred',['../classnode__pred.html',1,'node_pred'],['../structrecall__tree__ns_1_1node__pred.html',1,'recall_tree_ns::node_pred']]],
  ['node_5fsocks_27',['node_socks',['../structnode__socks.html',1,'']]],
  ['nodeentry_28',['NodeEntry',['../structxgboost_1_1tree_1_1ColMaker_1_1NodeEntry.html',1,'xgboost::tree::ColMaker']]],
  ['nodeinfo_29',['NodeInfo',['../classNodeInfo.html',1,'']]],
  ['nodevalue_30',['NodeValue',['../unionxgboost_1_1predictor_1_1DeviceNodeOneAPI_1_1NodeValue.html',1,'xgboost::predictor::DeviceNodeOneAPI']]],
  ['nometainfo_31',['NoMetaInfo',['../classxgboost_1_1data_1_1detail_1_1NoMetaInfo.html',1,'xgboost::data::detail']]],
  ['noncopyable_32',['noncopyable',['../classEigen_1_1internal_1_1noncopyable.html',1,'Eigen::internal']]],
  ['nonesuch_33',['nonesuch',['../structdetail_1_1nonesuch.html',1,'detail']]],
  ['noopcommunicator_34',['NoOpCommunicator',['../classxgboost_1_1collective_1_1NoOpCommunicator.html',1,'xgboost::collective']]],
  ['norm1_5fdefault_5fimpl_35',['norm1_default_impl',['../structEigen_1_1internal_1_1norm1__default__impl.html',1,'Eigen::internal']]],
  ['norm1_5fdefault_5fimpl_3c_20scalar_2c_20false_20_3e_36',['norm1_default_impl&lt; Scalar, false &gt;',['../structEigen_1_1internal_1_1norm1__default__impl_3_01Scalar_00_01false_01_4.html',1,'Eigen::internal']]],
  ['norm1_5fdefault_5fimpl_3c_20scalar_2c_20numtraits_3c_20scalar_20_3e_3a_3aiscomplex_20_3e_37',['norm1_default_impl&lt; Scalar, NumTraits&lt; Scalar &gt;::IsComplex &gt;',['../structEigen_1_1internal_1_1norm1__default__impl.html',1,'Eigen::internal']]],
  ['norm1_5fimpl_38',['norm1_impl',['../structEigen_1_1internal_1_1norm1__impl.html',1,'Eigen::internal']]],
  ['norm1_5fretval_39',['norm1_retval',['../structEigen_1_1internal_1_1norm1__retval.html',1,'Eigen::internal']]],
  ['norm_5fdata_40',['norm_data',['../structGD_1_1norm__data.html',1,'GD']]],
  ['normaldistribution_41',['NormalDistribution',['../structxgboost_1_1common_1_1NormalDistribution.html',1,'xgboost::common']]],
  ['nrowsblockxpr_42',['NRowsBlockXpr',['../structNRowsBlockXpr.html',1,'']]],
  ['nthvaluectx_43',['NthValueCtx',['../structNthValueCtx.html',1,'']]],
  ['ntilectx_44',['NtileCtx',['../structNtileCtx.html',1,'']]],
  ['nullopt_5ft_45',['nullopt_t',['../structdmlc_1_1nullopt__t.html',1,'dmlc']]],
  ['nullstream_46',['NullStream',['../structNullStream.html',1,'']]],
  ['nullstruct_47',['NullStruct',['../structjson11_1_1NullStruct.html',1,'json11']]],
  ['number_48',['Number',['../unionGenericValue_1_1Number.html',1,'GenericValue']]],
  ['numbersasstringshandler_49',['NumbersAsStringsHandler',['../structNumbersAsStringsHandler.html',1,'']]],
  ['numberutils_50',['NumberUtils',['../classMultiWorldTesting_1_1NumberUtils.html',1,'MultiWorldTesting']]],
  ['numericexamplebyte_51',['NumericExampleByte',['../classcs__unittest_1_1NumericExampleByte.html',1,'cs_unittest']]],
  ['numericexamplebytearray_52',['NumericExampleByteArray',['../classcs__unittest_1_1NumericExampleByteArray.html',1,'cs_unittest']]],
  ['numericexamplebytearrayanchor_53',['NumericExampleByteArrayAnchor',['../classcs__unittest_1_1NumericExampleByteArrayAnchor.html',1,'cs_unittest']]],
  ['numericexampledouble_54',['NumericExampleDouble',['../classcs__unittest_1_1NumericExampleDouble.html',1,'cs_unittest']]],
  ['numericexampledoublearray_55',['NumericExampleDoubleArray',['../classcs__unittest_1_1NumericExampleDoubleArray.html',1,'cs_unittest']]],
  ['numericexampledoublearrayanchor_56',['NumericExampleDoubleArrayAnchor',['../classcs__unittest_1_1NumericExampleDoubleArrayAnchor.html',1,'cs_unittest']]],
  ['numericexampleint16_57',['NumericExampleInt16',['../classcs__unittest_1_1NumericExampleInt16.html',1,'cs_unittest']]],
  ['numericexampleint16array_58',['NumericExampleInt16Array',['../classcs__unittest_1_1NumericExampleInt16Array.html',1,'cs_unittest']]],
  ['numericexampleint16arrayanchor_59',['NumericExampleInt16ArrayAnchor',['../classcs__unittest_1_1NumericExampleInt16ArrayAnchor.html',1,'cs_unittest']]],
  ['numericexampleint32_60',['NumericExampleInt32',['../classcs__unittest_1_1NumericExampleInt32.html',1,'cs_unittest']]],
  ['numericexampleint32array_61',['NumericExampleInt32Array',['../classcs__unittest_1_1NumericExampleInt32Array.html',1,'cs_unittest']]],
  ['numericexampleint32arrayanchor_62',['NumericExampleInt32ArrayAnchor',['../classcs__unittest_1_1NumericExampleInt32ArrayAnchor.html',1,'cs_unittest']]],
  ['numericexampleint64_63',['NumericExampleInt64',['../classcs__unittest_1_1NumericExampleInt64.html',1,'cs_unittest']]],
  ['numericexampleint64array_64',['NumericExampleInt64Array',['../classcs__unittest_1_1NumericExampleInt64Array.html',1,'cs_unittest']]],
  ['numericexampleint64arrayanchor_65',['NumericExampleInt64ArrayAnchor',['../classcs__unittest_1_1NumericExampleInt64ArrayAnchor.html',1,'cs_unittest']]],
  ['numericexamplesbyte_66',['NumericExampleSByte',['../classcs__unittest_1_1NumericExampleSByte.html',1,'cs_unittest']]],
  ['numericexamplesbytearray_67',['NumericExampleSByteArray',['../classcs__unittest_1_1NumericExampleSByteArray.html',1,'cs_unittest']]],
  ['numericexamplesbytearrayanchor_68',['NumericExampleSByteArrayAnchor',['../classcs__unittest_1_1NumericExampleSByteArrayAnchor.html',1,'cs_unittest']]],
  ['numericexamplesingle_69',['NumericExampleSingle',['../classcs__unittest_1_1NumericExampleSingle.html',1,'cs_unittest']]],
  ['numericexamplesinglearray_70',['NumericExampleSingleArray',['../classcs__unittest_1_1NumericExampleSingleArray.html',1,'cs_unittest']]],
  ['numericexamplesinglearrayanchor_71',['NumericExampleSingleArrayAnchor',['../classcs__unittest_1_1NumericExampleSingleArrayAnchor.html',1,'cs_unittest']]],
  ['numericexampleuint16_72',['NumericExampleUInt16',['../classcs__unittest_1_1NumericExampleUInt16.html',1,'cs_unittest']]],
  ['numericexampleuint16array_73',['NumericExampleUInt16Array',['../classcs__unittest_1_1NumericExampleUInt16Array.html',1,'cs_unittest']]],
  ['numericexampleuint16arrayanchor_74',['NumericExampleUInt16ArrayAnchor',['../classcs__unittest_1_1NumericExampleUInt16ArrayAnchor.html',1,'cs_unittest']]],
  ['numericexampleuint32_75',['NumericExampleUInt32',['../classcs__unittest_1_1NumericExampleUInt32.html',1,'cs_unittest']]],
  ['numericexampleuint32array_76',['NumericExampleUInt32Array',['../classcs__unittest_1_1NumericExampleUInt32Array.html',1,'cs_unittest']]],
  ['numericexampleuint32arrayanchor_77',['NumericExampleUInt32ArrayAnchor',['../classcs__unittest_1_1NumericExampleUInt32ArrayAnchor.html',1,'cs_unittest']]],
  ['numericexampleuint64_78',['NumericExampleUInt64',['../classcs__unittest_1_1NumericExampleUInt64.html',1,'cs_unittest']]],
  ['numericexampleuint64array_79',['NumericExampleUInt64Array',['../classcs__unittest_1_1NumericExampleUInt64Array.html',1,'cs_unittest']]],
  ['numericexampleuint64arrayanchor_80',['NumericExampleUInt64ArrayAnchor',['../classcs__unittest_1_1NumericExampleUInt64ArrayAnchor.html',1,'cs_unittest']]],
  ['numericlimits_81',['NumericLimits',['../structxgboost_1_1NumericLimits.html',1,'xgboost']]],
  ['numericlimits_3c_20float_20_3e_82',['NumericLimits&lt; float &gt;',['../structxgboost_1_1NumericLimits_3_01float_01_4.html',1,'xgboost']]],
  ['numericlimits_3c_20int64_5ft_20_3e_83',['NumericLimits&lt; int64_t &gt;',['../structxgboost_1_1NumericLimits_3_01int64__t_01_4.html',1,'xgboost']]],
  ['numpyarrayiterfortest_84',['NumpyArrayIterForTest',['../classxgboost_1_1NumpyArrayIterForTest.html',1,'xgboost']]],
  ['numtraits_85',['NumTraits',['../structEigen_1_1NumTraits.html',1,'Eigen']]],
  ['numtraits_3c_20array_3c_20scalar_2c_20rows_2c_20cols_2c_20options_2c_20maxrows_2c_20maxcols_20_3e_20_3e_86',['NumTraits&lt; Array&lt; Scalar, Rows, Cols, Options, MaxRows, MaxCols &gt; &gt;',['../structEigen_1_1NumTraits_3_01Array_3_01Scalar_00_01Rows_00_01Cols_00_01Options_00_01MaxRows_00_01MaxCols_01_4_01_4.html',1,'Eigen']]],
  ['numtraits_3c_20double_20_3e_87',['NumTraits&lt; double &gt;',['../structEigen_1_1NumTraits_3_01double_01_4.html',1,'Eigen']]],
  ['numtraits_3c_20float_20_3e_88',['NumTraits&lt; float &gt;',['../structEigen_1_1NumTraits_3_01float_01_4.html',1,'Eigen']]],
  ['numtraits_3c_20long_20double_20_3e_89',['NumTraits&lt; long double &gt;',['../structEigen_1_1NumTraits_3_01long_01double_01_4.html',1,'Eigen']]],
  ['numtraits_3c_20scalar_20_3e_90',['NumTraits&lt; Scalar &gt;',['../structEigen_1_1NumTraits.html',1,'Eigen']]],
  ['numtraits_3c_20std_3a_3acomplex_3c_20_5freal_20_3e_20_3e_91',['NumTraits&lt; std::complex&lt; _Real &gt; &gt;',['../structEigen_1_1NumTraits_3_01std_1_1complex_3_01__Real_01_4_01_4.html',1,'Eigen']]],
  ['numtraits_3c_20typenamematrixtype_3a_3ascalar_20_3e_92',['NumTraits&lt; typenameMatrixType::Scalar &gt;',['../structEigen_1_1NumTraits.html',1,'Eigen']]]
];
